### ISSUE TITLE
Best way to ensure consistent OpenMP environment

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#377] opened 2016-08-05 15:29 UTC
I am writing a library to be coupled in a larger application. Other portions of this application could in principle be changing the OpenMP environment, leading to the error: 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos::OpenMP parallel_for ERROR: Initialized but threads modified inappropriately
```

Could my above hypothesis about why this error is occurring be correct, or is this likely due to something else?

If it sounds reasonable, then:

I can think of a couple of options:
- Call Kokkos initialize and finalize before and after every call into my library
  - That would almost assuredly work but sounds very expensive.
- Enforce a consistent OpenMP environment by at every call into my library
  - Does Kokkos already have functionality for this?
  - What about if I have a different execution space (not a concern at the moment but could be in the future).

**Comment by hcedwar** [comment] 2016-08-05 16:08
The error occurs when `omp_get_max_threads()` changes between between Kokkos initialization and any attempt to use the Kokkos::OpenMP execution space.  Best thing to do is set the number of openmp threads at the beginning of `main`  (environment variables, command line arguments, explicit call to `omp_set_num_threads`) then initialize Kokkos, then don't change the number of openmp threads.  
There are dangers with changing the number of threads during execution.  The underlying thread pool may start/kill threads which is expensive.  The thread-to-core affinity may change which will hurt NUMA thread-data affinity.  Thread local storage will become ambiguous and the `omp_get_thread_num()` affinity to actual thread could change.  Just not a good idea to tempt fate.

**Comment by nmhamster** [comment] 2016-08-05 16:11
@hcedwar the issue is that *some* of our kernels may run more efficiently with < than max threads. For instance, I did a study for the Non-Conventional Computer Architectures group which showed that on Ivy Bridge SpMV was better at 1/2 of the total cores in the system for performance and energy consumption but that dot-products and vector scaling kernels were better at all cores. I'm not sure what Kokkos should *restrict* versus what is just advisory.

**Comment by hcedwar** [comment] 2016-08-05 16:14
How did you insure when you, at runtime, halved the number of threads that you got the right threads on the right cores?

**Comment by nmhamster** [comment] 2016-08-05 16:39
The CPU affinity mask is applied at the process level, so it continues to enforce which cores the threads are assigned to. In this case the runtime just cuts back and the fills from the mask forward with the same policy (I think there can be a distinction between maximum threads and the number of threads logically etc here). This was using Intel. Note that we were running one MPI rank per socket, affinity set to use the socket (so we are also always within a NUMA region). It worked as you expect it to work in a naive sense.

I agree that we need to be quite careful, particularly if we have made assumption relating to thread pools etc, but there may be cases when we want to allow this kind of behavior as well. More likely to be needed moving forward if we get into difficult spots with energy consumption, busy-waits etc.

We could consider maintaining the full set of threads, parking some up and then logically dispatching to fewer as a way to achieve something similar. There are definitely some tradeoffs here.

**Comment by dholladay00** [comment] 2016-08-05 17:10
So, is the suggestion to call Kokkos initialize and finalize before and after each call, or to reset (if needed) the number of threads before each call?

**Comment by hcedwar** [comment] 2016-08-05 17:11
Suggestion is to avoid resetting the number of threads during execution.

**Comment by mhoemmen** [comment] 2016-08-05 17:13
> For instance, I did a study for the Non-Conventional Computer Architectures group which showed that on Ivy Bridge SpMV was better at 1/2 of the total cores in the system for performance and energy consumption but that dot-products and vector scaling kernels were better at all cores.

Seems like the right thing for KokkosKernels to do would be to take an optional execution space instance over which to run the kernel.  I would rather do that than force some possibly unsupported thing like changing the number of OpenMP threads.

**Comment by ambrad** [comment] 2016-08-05 23:54
I agree with @nmhamster. A very common situation I've come across is that (1) a matrix factorization will peak in performance at N threads < M *and then decline*, while assembly and solve (i.e., permutation, MVP, triangular solve) will scale all the way to M. The declining part is important. (2) It's common to use TPL factorization libraries, so how they treat OpenMP threads is a black box that cannot be altered; the only control is omp_set_num_threads. (3) A similar situation arises with MKL and mkl_set_num_threads.

Hence my view is that altering the number of threads is a reality we have to deal with. That said, at least without hwloc I believe it's straightforward in practice to make sure that omp_get_max_threads() returns a single number for Kokkos to see. The only complication is if two Kokkos-based components differ on the optimal number of threads to use. (But I would argue that if a component is implemented in Kokkos, Kokkos patterns will enable an implementation that won't result in performance decreasing with increasing number of threads; rather, performance will simply plateau. A plateau means it's OK to stay at M threads everywhere.)

**Comment by crtrott** [comment] 2016-08-06 18:47
The issue here seems to be that something else resets the number of OpenMP threads. 
Kokkos right now will not allow you to call multiple init/finalize calls. One of the reasons is that we have internal data structures which depend on the number of threads, and there are a couple of things which are tougher to handle when you want this reinitialize to work. In particular on CUDA it would mean we can't call a reset at the end of the code, which might affect the next code running. 
(And after a reset you can't use the GPU in the same process anymore). 

Anyway, we would need to reset the number of threads to whatever you requested in Kokkos::initialize at every kernel call if we would allow this. That means another third party library might be in trouble if itself reset number of threads to some specific value in a init call and doesn't allow it to be changed. For using less than Max threads can't one use the pragma property 

```C++
#pragma parallel for num_threads(N)
....
```

which doesn't reset the total number of threads in the runtime and would be local? I believe this is the correct way to do these things. And at a global level the number of threads the runtime holds available for the process should be constant and the same over all components. 

Christian

**Comment by nmhamster** [comment] 2016-08-06 19:14
The re-initialization/finalize call sequence is a disaster and it feels logically inconsistent with what the user is asking for. I'd strongly advocate against that. So yes, there is an option to the use `num_threads(N)` approach with a policy but for libraries in child calls which do modify the number of threads we could just have Kokkos detect the difference and set it back to the max, or re-initialize itself around the smaller number? This is expensive but if we don't provide a call in Kokkos to allow this it should be limited to a hopefully small set of libraries with this behavior (or auto-tuners etc). BTW - not a given with auto-tuners that `N` will be the same everywhere.

**Comment by nmhamster** [comment] 2016-08-06 19:18
@ambrad not sure that just by using Kokkos you get round the issue of decreased performance at increasing thread counts (the "plateau") and certainly not true for energy consumption where busy-wait loops can consume a nasty amount of energy. In the end Kokkos is only calling OpenMP constructs and so the studies which show its better to back off on thread counts would, in theory, still show similar things right? Would be better to have a way to tell Kokkos to just limit dispatch to subset of the threads and keep the others parked up wouldn't it (by parking up I mean we could use some serious hard thread-wait constructs, not busy wait)?

**Comment by ambrad** [comment] 2016-08-06 19:31
@nmhamster, I largely agree with what you wrote. Let's divide the issue into two pieces.

(1) Energy consumption, and assume OMP_WAIT_POLICY=passive. Then the only way to reduce energy, I think, is by telling OpenMP to use fewer threads. (Not sure what happens if active rather than passive.)

(2) Performance. Here there is more freedom. To be clear, the issue is that if you use too many threads for too little work, the computation is slower than if you use fewer threads. In shylu/HTS, I throttle the number of threads I use based on data size within each parallel operation in a long sequence of operations *all in one parallel region* (with point-to-point synchronization among tasks). All OpenMP threads are still active, but at any given moment, just a subset might be used for actual work. Contrast this with straightforward parallel for-type code, where all threads are used regardless of data size. This throttling tends to lead to a nice plateau (robust) rather than a peak (tricky).

My point about Kokkos is that it encourages more thoughtful decomposition of work. e.g., thread teams and tasks with data parallelism within the task. Task decomposition, in particular, lets the programmer decide what data size is too small to parallelize (and hence is a single task rather than multiple). In principle, the task engine will be running fewer threads of computation than there are threads available, if the programmer has decided that there is not enough work at that point in the program to provide enough tasks to fill all threads. This is a good thing rather than a bad when trying to get a plateau rather than a peak.

**Comment by crtrott** [comment] 2016-08-06 20:26
Si, so do I read you correct that you also agree that calling initialize/finalize multiple times is not the way to go? The "set number of threads back instead of throw" option should be simple enough. Giving the policies an option to reduce the number of threads to be used should also be possible, and actually the chunk size setting should be able to do that for you in a workset centric way (i.e. you tell not how many threads to use, but how much work each thread should get minimally).

**Comment by nmhamster** [comment] 2016-08-06 21:05
@crtrott I think the best way to think of this is that when `Kokkos::initialize` is called the user is telling you the *maximum* number of threads that can be used in this job. It means we could then create a high water mark on the number of resources required in the thread pools and/or memory managers etc. Any subsequent Kokkos call which is made where the current thread count exceeds that initialized value is an error, this is roughly equivalent to the idea of OpenMP's max threads versus num threads but I think it also applies cleanly to pthreads and C++11 threads backends. The user is then free to supply less than the number of threads in any call to a Kokkos parallel construct with the runtime using the minimum of the available threads (from initialize) or the number supplied by the user in the call. It would allow for restriction on parallelism but no mechanism to increase parallelism and ensures that once initialize returns we have set a high water mark for the internal resources. Does that sound better? I do agree that multiple calls to initialize and finalize in a single program is just an awful idea both logically and for an implementation.

**Comment by nmhamster** [comment] 2016-08-06 21:07
@ambrad thanks, agree the distinction between the two is helpful. I think Kokkos as an API should deal with (2) and then hopefully we can apply some of our auto-tuning work to do possibly (1) and (2).

**Comment by ambrad** [comment] 2016-08-06 21:07
@crtrott, chunk size is often used as a load-balancing mechanism. So I think in schedule(static,N) num_threads(M), for example, N and M must be considered independent in general.

**Comment by hcedwar** [comment] 2016-08-08 15:32
When initialized with MAX and then reset with NUM < MAX, which subset of MAX threads is ambiguous.  Contiguous?  Strided? What if MAX % NUM != 0 ?  If contiguous and MAX resulted in multiple NUMA regions or multiple hyperthreads/core then specification of the subset has serious performance consequences.
How are you currently handling this in your application where you change OpenMP thread counts on the fly?

**Comment by dholladay00** [comment] 2016-08-08 15:45
Unfortunately I am *not* the one that is changing the number of thread counts. I work is a coupled multiphysics application with many packages and other packages appear to change this. It is likely that a uniform way for packages to deal with OpenMP is in the works, but is not currently in place. Even if this does get implemented, it is not clear that the app-wide OpenMP rules will prevent changing the number of threads. 

Also, though not fully verified (currently working on it), it appears that this issue shows up when compiled with intel but not with gcc. Again, this might not be the case, but I have compiled this app on another (fairly similar) machine with gcc and did not run into this error.

**Comment by hcedwar** [comment] 2016-08-08 16:57
Proposed solution:  
When Kokkos::OpenMP encounters a changed number of OpenMP threads then Kokkos::OpenMP changes that number back to the initialization value and emits a warning.  The warning is emitted the first time this happens, but not for subsequent resets.
Unfortunately we can only hope that the threads have the same binding that they did during initialization.  It would be way to expensive to repeat the binding process, almost as expensive as finalize/initialize.
Work for you?

**Comment by dholladay00** [comment] 2016-08-08 18:44
That sounds good. The only thing we had discussed in addition was caching the previous value for the number of threads and resetting it to that value at the end of the parallel region.

This suffers from the same issues associated with the binding policy but its the best thing I can think of at the moment that attempts to play nice with other packages/libraries that use openmp. 

The actual long term solution will likely require more thought, but this will work for the time being. Going with a different threaded backend is another alternative as well.

**Comment by dholladay00** [comment] 2016-08-08 22:29
I thought I could quickly hack in something that would get this to work in the interim, but it turns out that things like `omp_set_num_threads(nt);` don't do much outside of a parallel region. 

Is the best way to just set `Kokkos::OpenMP::thread_pool_size(0) = omp_get_max_threads;` ? 

My guess is that I don't have the ability to change that member, any suggestions (besides wait for the fix)?

With a little bit of guidance, I might be able to take a stab at it myself.

**Comment by nmhamster** [comment] 2016-09-27 21:43
@hcedwar I think Kokkos should allow the if `NUM` < `MAX`. In general users aren't going to be spanning multiple NUMA domains etc anyway, if they are then I think we are more likely to get better behavior from a vendor supplied runtime. If we are all in the same NUMA then it should work out relatively cheaply. In most cases the runtime will just restrict dispatch and park threads up.

**Comment by dholladay00** [comment] 2017-05-04 00:40
@dsunder this can probably be marked as in devlelop when your OpenMP fix is finished. I'm sure there's a number of issues related to this, but thought you'd like to know about this one as well.

**Closed** 2017-07-27 15:46 UTC
Labels: enhancement, InDevelop, question
