### ISSUE TITLE
Kokkos::resize should test whether dimensions have changed before resizing

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#904] opened 2017-06-21 19:37 UTC
@alanw0 found that introducing `if` statements to check sizes first before calling `Kokkos::resize`, reduced Aria memory use (reported in its log) from 2500 MB to 440 MB.  We'll be happy to submit a patch if this is a good idea.

**Comment by ibaned** [comment] 2017-06-21 21:28
@mhoemmen if you already have a patch, by all means open a PR. Even if we don't accept it directly, it will illustrate clearly the desired behavior.

**Comment by ibaned** [comment] 2017-06-21 21:33
That memory use reduction seems too dramatic... I could see how you avoid two copies of the same structure in a single `resize` call, but I don't understand how the memory use could be reduced by more than 2X for the overall program. Assuming the reported memory is accurate, this may point to a related bug (for example, if the old memory allocations were not freed for some reason, possibly due to  misuse of reference counting).

The proposed checks are still a good idea, but keep this in mind.

**Comment by alanw0** [comment] 2017-06-22 14:37
I don't think the issue is solely due to the kokkos resize function. The app calls it many many times over thousands of time steps, and we suspect there are also some issues with reference counts (views to the same allocation held by multiple code scopes). But the only thing we know for sure at this point is that reducing the number of resizes reduces the amount of memory growth. Dramatically. We will make use of Mark, he's a great resource!

**Comment by ibaned** [comment] 2017-06-22 15:15
Okay, looking forward to your patch.

**Comment by mhoemmen** [comment] 2017-06-22 20:31
Awww thanks @alanw0 ! :D Let me work on this.  I'll run it through Kokkos tests first.

**Comment by mhoemmen** [comment] 2017-06-27 23:56
I have a fix and a test for that fix done locally.  I'll make a PR for it when I get the chance.

**Comment by mhoemmen** [comment] 2017-06-28 15:34
@alanw0 I just opened a pull request to fix this.  The included test passes with CUDA.

**Comment by alanw0** [comment] 2017-06-28 15:44
@mhoemmen great, thanks! It turned out to not be the problem for the memory growth issue, but it may be a performance boost.
FYI the memory growth issue turned out to be related to a view-of-views that was being resized, and the inner views were being constructed weirdly and not being cleaned up. I didn't end up understanding the details, it was fixed by the app folks.

**Comment by mhoemmen** [comment] 2017-06-29 04:26
@alanw0 wrote:
> FYI the memory growth issue turned out to be related to a view-of-views that was being resized, and the inner views were being constructed weirdly and not being cleaned up. I didn't end up understanding the details, it was fixed by the app folks.

I think the issue was that the inner Views were constructed using placement `new`, so that made it our responsibility to destroy them explicitly.  But yes, it's fixed now :)

**Comment by ibaned** [comment] 2017-06-29 14:21
> the inner Views were constructed using placement `new`

Thanks @mhoemmen for forwarding the explanation! That was bothering me...

**Comment by mhoemmen** [comment] 2017-06-29 17:42
@ibaned Views of Views bother me ;-)

**Comment by stanmoore1** [comment] 2017-06-29 17:44
With great power comes great responsibility

**Comment by mhoemmen** [comment] 2017-06-29 18:16
generally responsibility increases much faster than power over time ;-)

**Comment by mhoemmen** [comment] 2017-06-30 20:07
I fixed this in develop, in #916.  Thanks all! :-D

**Closed** 2017-07-27 15:46 UTC
Labels: enhancement, InDevelop
