### ISSUE TITLE
ambiguous 'atomic_fetch_add' with hipcc

### ISSUE THREAD

**Issue by XzzX** [kokkos/kokkos#5299] opened 2022-08-01 10:19 UTC
**Describe the bug**
If you compile a simple application using at least a `View` with `hipcc` but without enabling the `HIP` backend a compilation error will occur:  
error: call to 'atomic_fetch_add' is ambiguous

**Please also include the following items to support reproducing the bug**
1. compilers (with versions)
hipcc from rocm 5.1.3
3. Kokkos release or commit used (i.e., the sha1 number)
current develop
4. platform and backend
serial backend
5. cmake configure command
`cmake -S batched_gels -B batched-build -DCMAKE_CXX_COMPILER=hipcc`
6. output from cmake command
fine
8. code needed to reproduce the bug
https://gitlab.mpcdf.mpg.de/seibl/batched_gels  
I think it is reproducible with other codes as well.

**Any additional info**
It includes `core/src/../../tpls/desul/include/desul/atomics/HIP.hpp` which I think should not be the case if HIP is not enabled.

**Comment by dalg24** [comment] 2022-08-01 13:00
Please confirm what backends you enabled when you built Kokkos and that you used `hipcc` as the `CMAKE_CXX_COMPILER` both for building Kokkos and your "batched gels" project.

**Comment by XzzX** [comment] 2022-08-01 16:02
```
-- Setting default Kokkos CXX standard to 17
-- The project name is: Kokkos
-- Using -std=c++17 for C++17 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: NoTypeDefined
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
-- 
-- Architectures:
-- Using internal desul_atomics copy
-- Kokkos Devices: SERIAL, Kokkos Backends: SERIAL
```

yes, `hipcc` from rocm 5.1.3. Kokkos is embedded in my project so both use the same configuration.

**Comment by JBludau** [comment] 2022-08-01 17:08
It is not restricted to your code, I can reproduce it with `Kokkos_ENABLE_TESTS=On`
It happes if you use `hipcc` but do not enable the hip backend.

**Comment by JBludau** [comment] 2022-08-01 17:28
So it looks like this is a compiler problem with the `DESUL` lib. We will try to look into this. 
Have you tried adding `Kokkos_ENABLE_HIP=On` to `cmake -S batched_gels -B batched-build -DCMAKE_CXX_COMPILER=hipcc` ?

**Comment by XzzX** [comment] 2022-08-02 07:19
> So it looks like this is a compiler problem with the `DESUL` lib. We will try to look into this. Have you tried adding `Kokkos_ENABLE_HIP=On` to `cmake -S batched_gels -B batched-build -DCMAKE_CXX_COMPILER=hipcc` ?

Yes, with HIP enabled it also works for me.

**Comment by JBludau** [comment] 2022-08-04 15:09
So this seems to be a desul issue. @XzzX do you need Kokkos and `hipcc` with disabled HIP backend for any specific problem/calculation/etc.? Or does enabling the backend work for you? 
As we treat desul as a third party library and it is undergoing some redesign, it might take some time until this is in kokkos develop.

**Comment by XzzX** [comment] 2022-08-04 18:06
Yes, I can work around it. No problem. Just a general remark.

**Comment by JBludau** [comment] 2022-08-04 18:17
Then I will go ahead and close this issue, as it is a desul thing, see [here](https://github.com/desul/desul/issues/67)

**Closed by JBludau** 2022-08-04 18:17 UTC
