### ISSUE TITLE
Figure out the maximal number of elements in a shared memory view

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1811] opened 2018-09-19 22:56 UTC
I get the "Kokkos::Impl::ParallelFor< Cuda > insufficient shared memory" runtime error when trying to use TeamPolicy::scratch_size_max(0) / sizeof(int) to calculate the maximal number of element in a shared view. This is an example:
```
#include <Kokkos_Core.hpp>
#include <Kokkos_DualView.hpp>
using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using namespace std;

template < class DualView >
void syncToHost(DualView&& data) {
  using MemorySpace = typename std::decay_t<DualView>::memory_space;
  using HostMirrorSpace = typename std::decay_t<DualView>::host_mirror_space;
  std::forward<DualView>(data).template modify<MemorySpace>();
  std::forward<DualView>(data).template sync<HostMirrorSpace>();
}

template < class DualView >
void syncToDevice(DualView&& data) {
  using MemorySpace = typename std::decay_t<DualView>::memory_space;
  using HostMirrorSpace = typename std::decay_t<DualView>::host_mirror_space;
  std::forward<DualView>(data).template modify<HostMirrorSpace>();
  std::forward<DualView>(data).template sync<MemorySpace>();
}

template < class T, class E >
struct F {
  using TeamPolicy = Kokkos::TeamPolicy<E>;
  using Team = typename TeamPolicy::member_type;
  using SharedSpace = typename E::scratch_memory_space;
  using UnmanagedTraits = Kokkos::MemoryTraits<Kokkos::Unmanaged>;
  using SharedView = Kokkos::View<T*,SharedSpace,UnmanagedTraits>;

  Kokkos::DualView<std::size_t,E> N_;

  F() : N_("N") 
  {
    N_.h_view() = TeamPolicy::scratch_size_max(0) / sizeof(T);
    syncToDevice(N_);
    printf("N = %10lu\n",N_.h_view());
  };

  KOKKOS_INLINE_FUNCTION 
  void operator()(const Team& team) const {
    SharedView a(team.team_scratch(0),N_.d_view());
    Kokkos::parallel_for(Kokkos::TeamThreadRange(team,a.extent(0)),
      [&](const int& i){
        a(i) = i;
      });
  }

  std::size_t shmemSize() const {
    return SharedView::shmem_size(N_.h_view());
  }

};


int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  const std::size_t nTeams = 10;
  using Functor = F<int,ExecutionSpace>;
  using Policy = Functor::TeamPolicy;
  using Team = Functor::Team;
  Functor f{};
  printf("shmemSize = %10lu\n",f.shmemSize());
  const std::size_t teamSize = Policy(nTeams,Kokkos::AUTO).
    team_size_max(f,Kokkos::ParallelForTag{});
  auto policy = Policy(nTeams,teamSize).
    set_scratch_size(0,Kokkos::PerTeam(f.shmemSize())); 
  Kokkos::parallel_for(policy,f); 

  } Kokkos::finalize();
}
```

**Comment by Char-Aznable** [comment] 2018-09-19 23:06
I was compiling the example with clang 6.0.1 + cuda 9.0 and running it on a GeForce GTX 1080 that has 48 kB of shared memory

**Comment by crtrott** [comment] 2018-09-19 23:14
Ok Views in scratch space have some alignment requirements. This is taken into account in the `Kokkos::View<...>::shmem_size(int...)` interface. So you would need to have that function called in your `shmemSize` function. There is no really good interface way for us to provide a way of telling you how many elements you could have a in scratch view. For a 1D view we probably could, but for a multi dimensional one it becomes tricky.

**Comment by crtrott** [comment] 2018-09-19 23:27
Yeah but you don't check anymore that that number is smaller than `scratch_size_max(0)`.

**Comment by Char-Aznable** [comment] 2018-09-19 23:34
@crtrott  Can you be more specific? In my example, `scratch_size_max(0)` is the same as `shmemSize`

**Comment by crtrott** [comment] 2018-09-19 23:35
Oh it is? S*** ...

**Comment by crtrott** [comment] 2018-09-19 23:35
Sounds like a bug to me :-( I will try fix that as part of the alignment issue #1750

**Comment by Char-Aznable** [comment] 2018-09-19 23:42
OK. Thanks. For reference, I print out the sizes for my example:
```
    printf("Max scratch size = %10d\n", TeamPolicy::scratch_size_max(0));
    printf("sizeof(T) = %10lu\n", sizeof(T));
    printf("N = %10lu\n",N_.h_view());
   printf("shmemSize = %10lu",f.shmemSize());
```
which resutls in
```
Max scratch size =      40960
sizeof(T) =          4
N =      10240
shmemSize =      40960
```

**Comment by Char-Aznable** [comment] 2018-09-19 23:49
Also, if I type `T` is `double`, which is 8 byte and the example still gives me the same error, which is weird considering that 8 byte alignment is used.

**Comment by crtrott** [comment] 2018-09-19 23:54
Yeah I will track this down. There are somewhere some holes in our logic I do not fully understand right now. I thought I had them finally sorted out - but apparently not.

**Comment by ndellingwood** [comment] 2018-10-05 04:51
@crtrott is this fixed with your shmem alignment PR #1817?

**Comment by Char-Aznable** [comment] 2019-02-01 18:48
@crtrott Is there any update on this thread? I'm getting the same error now with CUDA 10

**Comment by PhilMiller** [comment] 2022-11-10 17:55
Reproduces on 3.7.0, Cuda 11.2, GCCC 8.3.0

```
N =      10240
shmemSize =      4096449152 49172
unknown file: Failure
C++ exception with description "Kokkos::Impl::ParallelFor< Cuda > insufficient shared memory" thrown in the test body.
```

**Comment by PhilMiller** [comment] 2022-11-10 18:03
Clearing the really old assignment to @ndellingwood for now

**Comment by PhilMiller** [comment] 2022-12-21 19:25
This may actually be fixed by #5687 - I'll test.

**Comment by PhilMiller** [comment] 2022-12-21 19:49
With that PR, it still fails:
```
$ ./KokkosCore_UnitTest_Develop 
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from defaultdevicetype
[ RUN      ] defaultdevicetype.development_test
N =      10240
shmemSize =      40968
49152 49176
unknown file: Failure
C++ exception with description "Kokkos::Impl::ParallelFor< Cuda > insufficient shared memory" thrown in the test body.
[  FAILED  ] defaultdevicetype.development_test (0 ms)
```

The numbers are bumped a bit, but that's all.

**Comment by PhilMiller** [comment] 2022-12-21 19:55
Edited a bit to add a print:

```
[ RUN      ] defaultdevicetype.development_test
TeamPolicy::scratch_size_max(0) =      40960
N =      10240
shmemSize =      40968
49152 49176
unknown file: Failure
C++ exception with description "Kokkos::Impl::ParallelFor< Cuda > insufficient shared memory" thrown in the test body.
```

**Comment by PhilMiller** [comment] 2022-12-21 20:02
@crtrott I think the issue in part may be that the alignment code needs to not round up to an offset of the alignment value when 0 would suffice

**Comment by brian-kelley** [comment] 2022-12-21 22:54
I just cross-referenced a KokkosKernels issue I was running into, in which a TeamPolicy parallel_for kernel would fail with messages like
```
ScratchMemorySpace<...>::get_shmem: Failed to allocate 36 byte(s); remaining capacity is 36 byte(s)
```
So it's just a note to check if this might be the root cause.

**Comment by PhilMiller** [comment] 2022-12-22 17:59
I just confirmed that #5718 fixes this issue - the test given above now passes.

**Closed** 2023-03-08 19:17 UTC
Labels: Bug, InDevelop, CHANGELOG, Backend - CUDA, Backend - HIP
