### ISSUE TITLE
Support PGI

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#2] opened 2015-04-15 18:15 UTC
We need to make sure PGI 15.x compilers are supported both for host only and host+cuda compilation. This will probably be an important compiler on machines with NVIDIA GPUs.

**Comment by crtrott** [comment] 2015-05-17 18:25
I get through the compilation with PGI 15.4 but fail at link time with:
/usr/bin/ld: cannot find -lgcc_s

**Comment by nmhamster** [comment] 2015-05-18 16:01
What system are you using for this compile?



--
Si Hammond
Scalable Computer Architectures
Sandia National Laboratories, NM
[Sent remotely, please excuse typing errors]
________________________________

**Comment by hcedwar** [comment] 2017-01-03 22:58
Duplicate of issue #289

**Closed by hcedwar** 2017-01-03 22:58 UTC
Labels: duplicate, enhancement
