### ISSUE TITLE
Compiler warnings when compiling core unit tests for Cuda

### ISSUE THREAD

**Issue by gmackey** [kokkos/kokkos#214] opened 2016-03-16 19:32 UTC
When I compile for Cuda (7.5.18) in core/unit_test, I see a bunch of compiler warnings.

Here are the warnings:

/home/gemacke/kokkos/clean_kokkos/core/src/Kokkos_Atomic.hpp(130): warning: extern inline function "Kokkos::Impl::lock_address_cuda_space" was referenced but not defined

/home/gemacke/kokkos/clean_kokkos/core/src/Kokkos_Atomic.hpp(139): warning: extern inline function "Kokkos::Impl::unlock_address_cuda_space" was referenced but not defined

/home/gemacke/kokkos/clean_kokkos/core/src/Kokkos_Atomic.hpp(130): warning: extern inline function "Kokkos::Impl::lock_address_cuda_space" was referenced but not defined

/home/gemacke/kokkos/clean_kokkos/core/src/Kokkos_Atomic.hpp(139): warning: extern inline function "Kokkos::Impl::unlock_address_cuda_space" was referenced but not defined

/home/gemacke/kokkos/clean_kokkos/core/src/Kokkos_Atomic.hpp(130): warning: extern inline function "Kokkos::Impl::lock_address_cuda_space" was referenced but not defined

/home/gemacke/kokkos/clean_kokkos/core/src/Kokkos_Atomic.hpp(139): warning: extern inline function "Kokkos::Impl::unlock_address_cuda_space" was referenced but not defined

/home/gemacke/kokkos/clean_kokkos/core/src/Kokkos_Atomic.hpp(130): warning: extern inline function "Kokkos::Impl::lock_address_cuda_space" was referenced but not defined

/home/gemacke/kokkos/clean_kokkos/core/src/Kokkos_Atomic.hpp(139): warning: extern inline function "Kokkos::Impl::unlock_address_cuda_space" was referenced but not defined

/home/gemacke/kokkos/clean_kokkos/core/src/Kokkos_Atomic.hpp(130): warning: extern inline function "Kokkos::Impl::lock_address_cuda_space" was referenced but not defined

/home/gemacke/kokkos/clean_kokkos/core/src/Kokkos_Atomic.hpp(139): warning: extern inline function "Kokkos::Impl::unlock_address_cuda_space" was referenced but not defined

/home/gemacke/kokkos/clean_kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp(106): warning: function "Kokkos::Impl::<unnamed>::cuda_launch_blocking" was declared but never referenced

/home/gemacke/kokkos/clean_kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp(106): warning: function "Kokkos::Impl::<unnamed>::cuda_launch_blocking" was declared but never referenced

**Comment by crtrott** [comment] 2016-04-28 06:24
The root cause is a forward declaration of an inline function. That inline function is forward declared, in Kokkos_Atomic, but only defined in Kokkos_CudaExec.hpp. Not sure yet how to resolve that, since both the forward declaration is necessary and I can't pull the functions forward (since they use a const symbol only declared in Kokkos_CudaExec.hpp, which I can't forward declare).

**Comment by crtrott** [comment] 2016-04-28 19:11
So I looked a bit more into this, and fixing it would involve a lot of cleanup and restructuring of internal code, in particular the organization of atomics. Considering other commitments for end of spring (in particular supporting execution space instances) this is not feasible, and I move this issue to backlog again.

**Comment by dsunder** [comment] 2017-06-13 21:26
Fixed by #881

**Closed** 2017-07-27 15:46 UTC
Labels: enhancement, InDevelop
