### ISSUE TITLE
View of UnorderedMap resize() error

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#4072] opened 2021-06-04 18:51 UTC
This code gives the `Constructing View and initializing data with uninitialized execution space` error. Note that all relevant views are on the host and the code is built for the host OpenMP backend:
```c++
#include <Kokkos_Core.hpp>
#include <Kokkos_UnorderedMap.hpp>

using HostExecutionSpace = Kokkos::DefaultHostExecutionSpace;
using HostMemorySpace = HostExecutionSpace::memory_space;
using HostDevice = Kokkos::Device<HostExecutionSpace, HostMemorySpace>;

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  using Map = Kokkos::UnorderedMap<int, int, HostDevice>;

  Kokkos::View<Map*, HostDevice> v("v", 1);

  Kokkos::resize(v, 5); //This triggers the error

  } Kokkos::finalize();
}

```

**Comment by Char-Aznable** [comment] 2021-06-04 19:00
To give this some context, the intended usage was actually `Kokkos::vector<Kokkos::UnorderedMap>`  and the same error was found when calling the vector's `push_back()` method.

**Comment by crtrott** [comment] 2021-06-04 20:02
There might be something more fundamentally wrong, if the allocation doesn't trigger the bug but the resize does. There shouldn't be a difference in constraints regarding what works for allocation and what works for resize.

**Comment by Char-Aznable** [comment] 2021-06-05 00:34
Not sure if this is related but if we do
```c++
  Kokkos::View<Map*, HostDevice> vCopy("vCopy", v.extent(0));
  Kokkos::deep_copy(vCopy, v);

```
instead of the resize() call then it gives a different error: 
```c++
Kokkos::Impl::SharedAllocationRecord '' failed decrement count = 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos::Impl::SharedAllocationRecord failed decrement count
```

**Comment by Char-Aznable** [comment] 2021-06-18 17:12
Not sure if this is related but something like this will also throw `Constructing View and initializing data with uninitialized execution space`:
```c++
int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  using MapHost = Kokkos::UnorderedMap<int,void,Kokkos::DefaultHostExecutionSpace>;
  Kokkos::parallel_for("generateMap",
    Kokkos::RangePolicy<Kokkos::DefaultHostExecutionSpace>{Kokkos::DefaultHostExecutionSpace{}, 0, 10},
    [&] (const int i) {
    MapHost mHost(10000);
  });
  } Kokkos::finalize();
}

```

**Comment by ajpowelsnl** [comment] 2022-04-20 18:24
@nliber -- please have a look!

**Comment by ajpowelsnl** [comment] 2024-04-22 18:12
@nliber -- do yo have an ETA for this fix?  Could we get it into the next release?

**Comment by nliber** [comment] 2024-07-15 19:38
The problem in https://github.com/kokkos/kokkos/issues/4072#issue-911757643 I cannot reproduce.

The problem in https://github.com/kokkos/kokkos/issues/4072#issuecomment-855154851 is Issue #6986.

**Comment by nliber** [comment] 2024-07-15 21:57
https://github.com/kokkos/kokkos/issues/4072#issuecomment-864173374 also not reproducible.

**Comment by nliber** [comment] 2024-07-15 21:58
Closing...

**Comment by nliber** [comment] 2024-07-15 21:58
Closing as only one of the examples is reproducible, and that is indicative of enough issue (mentioned above).

**Closed by nliber** 2024-07-15 21:58 UTC
Labels: Bug
