### ISSUE TITLE
Missing error check for some View constructors

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos#5205] opened 2022-07-12 16:55 UTC
@kliegeois 
**Describe the bug**
Kokkos computes wrong extent of subview below is the source code followed by the output:
```c++
const int n = A.extent(0);
ScratchPadMatrixViewType tmp(member.team_scratch(0), n, n + 4);
std::cout << "tmp extents: (" << tmp.extent(0) << ", " << tmp.extent(1) << "), n=" << n << std::endl;
```

```
tmp extents: (3, 1), n=3
unknown file: Failure
C++ exception with description "Kokkos::subview bounds error ( Kokkos::ALL , 1 <= 3 - 0 )" thrown in the test body.
```

**Please also include the following items to support reproducing the bug**
1. compilers (with versions): GNU 10.1.0
2. Kokkos release or commit used (i.e., the sha1 number): a51981a9
3. platform and backend: serial
4. cmake configure command: `cmake -DKokkos_ENABLE_SERIAL=ON -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_CXX_STANDARD=14 -DKokkos_ENABLE_COMPILER_WARNINGS=ON  -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK:BOOL=ON -DKokkos_ENABLE_DEPRECATED_CODE_3=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/../install ..`
5. output from cmake command 
```
-- Setting default Kokkos CXX standard to 14
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The project name is: Kokkos
-- Using -std=gnu++14 for C++14 extensions as feature
-- Built-in Execution Spaces:
--     Device Parallel: NoTypeDefined
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
-- 
-- Architectures:
-- Found TPLLIBDL: /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include  
-- Using internal desul_atomics copy
-- Kokkos Devices: SERIAL, Kokkos Backends: SERIAL
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/runner/work/kokkos-kernels/kokkos-kernels/kokkos/build
```
6. code needed to reproduce the bug: kokkos kernels batched dense linear algebra unit-tests 
7. command line needed to reproduce the bug: `./unit_test/KokkosKernels_batched_dla_serial --gtest_filter=serial.batched_scalar_team_gesv_static_pivoting*`
8. please also attach the `KokkosCore_config.h` header file (generated during the build);

**Any additional info**
Please provide any additional context about the issue here.

**Comment by lucbv** [comment] 2022-07-12 17:18
@dalg24 good point, I reproduced on both my laptop, my workstation and the original failure is in our CI so this is not compiler sensitive.
The previous commit in kokkos/develop works just fine, I have not tried to compile with other backends.

**Comment by kliegeois** [comment] 2022-07-12 18:36
Based on https://github.com/kokkos/kokkos-kernels/pull/1461/commits/8e6986d13651ea84b965a41fca356df431a71cc1 it seems that @mzuzek found the issue.

The issue is associated to this:

```
template <typename DeviceType, typename MatrixType, typename VectorType,
          typename AlgoTagType>
struct Functor_TestBatchedTeamVectorGesv {
  const MatrixType _A;
  const VectorType _X;
  const VectorType _B;

  KOKKOS_INLINE_FUNCTION
  Functor_TestBatchedTeamVectorGesv(const MatrixType &A, const VectorType &X,
                                    const VectorType &B)
      : _A(A), _X(X), _B(B) {}

  template <typename MemberType>
  KOKKOS_INLINE_FUNCTION void operator()(const MemberType &member) const {
    const int matrix_id = static_cast<int>(member.league_rank());
    auto A = Kokkos::subview(_A, matrix_id, Kokkos::ALL, Kokkos::ALL);
    auto x = Kokkos::subview(_X, matrix_id, Kokkos::ALL);
    auto b = Kokkos::subview(_B, matrix_id, Kokkos::ALL);

    member.team_barrier();
    KokkosBatched::TeamVectorGesv<MemberType, AlgoTagType>::invoke(member, A, x,
                                                                   b);
    member.team_barrier();
  }

  inline void run() {
    //...

    using MatrixViewType =
        Kokkos::View<typename MatrixType::non_const_value_type **,
                     typename MatrixType::array_layout,
                     typename MatrixType::execution_space>;

    const int n    = _A.extent(1);
    size_t bytes_0 = MatrixViewType::shmem_size(n, n + 4);
    policy.set_scratch_size(0, Kokkos::PerTeam(bytes_0));

    Kokkos::parallel_for(name.c_str(), policy, *this)
  }
};
```
where:


```
template <typename MemberType>
struct TeamGesv<MemberType, Gesv::StaticPivoting> {
  template <typename MatrixType, typename VectorType>
  KOKKOS_INLINE_FUNCTION static int invoke(const MemberType &member,
                                           const MatrixType A,
                                           const VectorType X,
                                           const VectorType Y) {

    using ScratchPadMatrixViewType = Kokkos::View<
        typename MatrixType::non_const_value_type **,
        typename MatrixType::array_layout,
        typename MatrixType::execution_space::scratch_memory_space>;

    const int n = A.extent(0);

    ScratchPadMatrixViewType tmp(member.team_scratch(0), n, n + 4);
    
    //...
    }
 };
```

The issue is that in the first code, `MatrixType` is a 3D view type and in the second one, it is the type associated to `Kokkos::subview(_A, matrix_id, Kokkos::ALL, Kokkos::ALL);`, i.e. a 2D one where the layout might not be the same as the layout of the 3D one. If I recall correctly, a left layout for the 3D view will lead to a stride layout for the 2D one in this case.

Therefore, I guess it is a bug only on the Kokkos Kernels side and it turned out that it worked before by chance.

**Comment by kliegeois** [comment] 2022-07-12 19:09
I guess, we can close the issue.

**Comment by ajpowelsnl** [comment] 2022-07-12 20:10
Hi @kliegeois and @lucbv -- may I close this issue now?

**Comment by mzuzek** [comment] 2022-07-12 20:21
@crtrott @dalg24 

With our [sneaky KK bug](https://github.com/kokkos/kokkos-kernels/pull/1461#issuecomment-1182232042) we felt into a tiny trap hidden inside `Kokkos::View` constructor: if we define `m`x`n` rank-2 view with `KokkosView<Scalar**, Layout, Device> A(data_ptr, m, n);` and someone provides `Layout=Kokkos::LayoutStride`, he will effectively subvert the statement to yield `m`x1 rank-1 view instead, because `n` will be passed to [`LayoutStride` constructor](https://kokkos.github.io/kokkos-core-wiki/API/core/view/layoutStride.html#constructors) and interpreted as stride there (instead of second extent like in left and right layouts).

Could this `LayoutStride` case be somehow better detected in `Debug` builds (maybe even with `Kokkos_ENABLE_DEBUG_BOUNDS_CHECK=OFF`) - for instance as _incorrect construction_, which has rank-2 data pointer (`Scalar**`) but only one extent (`m`) in constructor argumnets ?

**Comment by crtrott** [comment] 2022-07-12 20:59
Oh interesting. Note that 
```c++
View<int**,LayoutRight> a("A",n,m);
```

Does not actually compile:
```
/ascldap/users/crtrott/Kokkos/kokkos/core/src/Kokkos_View.hpp:1584:5: error: static assertion failed: Layout is not extent constructible. A layout object should be passed too.

     static_assert(traits::array_layout::is_extent_constructible,
```

So there is a check missing in the from pointer constructor.

**Comment by lucbv** [comment] 2022-07-12 21:26
Yeah, I was a bit surprised that our code was able to call the constructor wrongly like that, it has been doing so for a while.
I can leave this issue open if you are planning on adding an assertion for that, otherwise we can close this and track that somewhere else.

**Comment by crtrott** [comment] 2022-07-12 21:51
Have a fix in-flight. Systematically looked for places in Kokkos_View.hpp where we create a layout object just from extents and added the static_assert.

**Closed** 2022-10-04 22:28 UTC
Labels: Bug, InDevelop
