### ISSUE TITLE
What is KOKKOS_SEPARATE_LIBS needed for?

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#2295] opened 2019-09-07 02:43 UTC
What was the rational for having either three separate libraries `kokkoscore`, `kokkosalgorithms`, and `kokkoscontainers`, versus just the one `kokkos`?

Was it a Trilinos thing?  If so, does the current HEAD of the develop actually work?  I don't see any cmake logic to set the variable `KOKKOS_SEPARATE_LIBS` to `TRUE` if Trilinos/TriBITS is detected.

Related to #2119, #2167, and more loosely to https://github.com/kokkos/kokkos/pull/2294#issuecomment-529063887

**Comment by jjwilke** [comment] 2019-09-08 23:53
This is a Trilinos thing. I'm sure there is historical reason for it in Trilinos - but I don't know it.

Kokkos always builds "separate" libraries. Trilinos just toggles whether they are actual libraries or object libraries which later get concatenated into a libkokkos.

I believe this use of temporary object libraries is the cause of the `fPIC` weirdness in #2283

**Comment by mhoemmen** [comment] 2019-09-09 18:21
@dalg24 wrote:
> What was the rational for having either three separate libraries `kokkoscore`, `kokkosalgorithms`, and `kokkoscontainers`, versus just the one `kokkos`?

Those corresponded to different Trilinos subpackages.  The idea was that downstream packages could declare a dependency on just a subpackage.  That would reduce the testing burden (e.g., if something doesn't depend on KokkosAlgorithms then it doesn't have to be tested if KokkosAlgorithms changes).

**Comment by masterleinad** [comment] 2019-10-14 22:09
Addressed in #2447.

**Closed** 2019-12-20 23:46 UTC
Labels: InDevelop, enhancement
