### ISSUE TITLE
Documentation: Improve documentation on fencing behavior in create_mirror_view_and_copy

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos#5465] opened 2022-09-16 21:09 UTC
The documentation does not discuss whether or not the call to create_mirror_view_and_copy fences.

https://kokkos.github.io/kokkos-core-wiki/API/core/view/create_mirror.html?highlight=create_mirror_view_and_copy

**Comment by PhilMiller** [comment] 2022-09-16 21:12
Duplicate of #4837

**Closed by PhilMiller** 2022-09-16 21:12 UTC
