### ISSUE TITLE
Warning : calling a __host__ function from __host__ __device__ function in Kokkos.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#2694] opened 2020-01-29 21:17 UTC
Why do I see this warning ? 
```
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/kokkos/core/src/impl/Kokkos_FunctorAnalysis.hpp(341): warning: calling a __host__ function("Kokkos::Impl::HostThreadTeamMember< ::Kokkos::OpenMP> ::HostThreadTeamMember") from a __host__ __device__ function("Kokkos::Impl::HostThreadTeamMember< ::Kokkos::OpenMP> ::HostThreadTeamMember [subobject]") is not allowed
```

**Comment by stanmoore1** [comment] 2020-01-29 21:19
I find it is typically because I forgot to add `KOKKOS_FUNCTION` or `KOKKOS_INLINE_FUNCTION` somewhere.

**Comment by dhollman** [comment] 2020-01-29 23:00
This is a bug in NVCC as far as I can tell. One place this bug shows up is when we're using a base class constructor with a `using` clause. This should be mostly fixed on `develop`, though. What branch are you seeing this on? Do you have a minimal reproducer?

**Comment by ndellingwood** [comment] 2020-08-19 21:06
@kyungjoo-kim closing the issue, if addition of `KOKKOS_FUNCTION` or `KOKKOS_INLINE_FUNCTION` was insufficient to resolve the warning please reopen, thanks.

**Closed by ndellingwood** 2020-08-19 21:06 UTC
