### ISSUE TITLE
UnorderedMap::size() does not match the number of "valid" entries

### ISSUE THREAD

**Issue by PhilipFackler** [kokkos/kokkos#2636] opened 2020-01-09 21:27 UTC
The value I get from map.size() is not the same as I get as the `total` from the following:
```c++
Kokkos::parallel_reduce(map.capacity(), KOKKOS_LAMBDA (std::size_t i, std::size_t& running) {
    if (map.valid_at(i)) {
        ++running;
    }
}, total);
```

I expected these two to give the same result. The `size()` is the correct value. That is, using the same logic in serial with a std::vector, that's the number of things added to the vector.

Am I wrong in my assumption here? Thanks.

**Comment by masterleinad** [comment] 2020-01-10 21:39
Hmm...
```C++
TEST(TEST_CATEGORY, UnorderedMap_size) {
  Kokkos::UnorderedMap<int, int, TEST_EXECSPACE> map(100);
  Kokkos::parallel_for(
      "insert", Kokkos::RangePolicy<TEST_EXECSPACE>(0, 10),
      KOKKOS_LAMBDA(int i) {
        map.insert(2 * i, i);
        printf("Inserting %d=%d\n", 2 * i, i);
      });
  int total = 0;
  Kokkos::parallel_reduce(
      "count", Kokkos::RangePolicy<TEST_EXECSPACE>(0, map.capacity()),
      KOKKOS_LAMBDA(int i, int &running) {
        if (map.valid_at(i)) {
          ++running;
        }
      },
      total);

  EXPECT_GT(map.capacity(), 20);
  EXPECT_EQ(map.size(), 10);
  EXPECT_EQ(total, 10);
}
```
works for me with `Kokkos::Serial` or `Kokkos::OpenMP`. What does your MWE look like?

**Comment by crtrott** [comment] 2020-01-23 03:09
@PhilipFackler can we get a complete reproducer to figure out whether there is an issue here?

**Comment by PhilipFackler** [comment] 2020-01-23 13:34
I didn't want to include the code where it was happening, since it was pretty complicated. I'll try to reproduce it with something simple today.

**Comment by PhilipFackler** [comment] 2020-01-24 15:50
I am unable to reproduce this with a simple example. Probably there was (or still is) a bug in the code where I was trying to use this.

**Comment by masterleinad** [comment] 2020-01-24 17:11
Closing for now. Lease reopen if you find a reproducer.

**Closed by masterleinad** 2020-01-24 17:11 UTC
