### ISSUE TITLE
Kokkos Base Makefile adds AVX to KNC Build

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#16] opened 2015-05-14 19:22 UTC
If I run: ../generate_makefile.bash --with-openmp --arch=KNC --compiler=`which iclc`

But use Kokkos files later, I get: 

mpiicpc -O3 -I../src -DWITH_MPI=1 -mmic -DCELL_FLUX -I./ -I/home/sdhammo/kokkos/kokkos-git/core/src -I/home/sdhammo/kokkos/kokkos-git/containers/src -I/home/sdhammo/kokkos/kokkos-git/algorithms/src  --std=c++11 -mavx -fopenmp -c ../src/Cell.C
icpc: command line error: option '-mavx' not supported

CXXFLAGS looks incorrect here, should be -mmic not -mavx.

**Comment by crtrott** [comment] 2015-05-14 21:22
I can't reproduce that at the moment. Can you give more details.

**Comment by nmhamster** [comment] 2015-05-14 22:00
Here is what I have been doing.

(1) git glone ..
(2) cd into directory
(3) mkdir build
(4) cd build
(5) ../generate_makefile.bash --with-openmp --arch=KNC --compiler=`which icpc`
(6) make

**Comment by crtrott** [comment] 2015-05-14 22:06
but where is the -DWITH_MPI coming from? thats not Kokkos.

**Comment by nmhamster** [comment] 2015-05-14 22:14
MiniAero.

**Comment by crtrott** [comment] 2015-05-14 22:23
I am going through that right now and will fix any issues ;-)

**Comment by crtrott** [comment] 2015-05-14 23:22
OK I just pushed a fix which makes it work at least with GCC. KNC build fails because it says the library is not valid. Is ar the wrong thing to put the things together in that case?
Also the miniAero makefile needs some small changes so that it doesn't override setting from the installed Makefile.kokkos (i.e. comment out some lines):

#Set the path to Kokkos
KOKKOS_PATH = /home/crtrott/KokkosInstall/SNB-OpenMP
#Set the Devices to compile for
#KOKKOS_DEVICES=OpenMP
#Set the Architecture to compiler for
#KOKKOS_ARCH=SNB

 (1) ~/kokkos/generate_makefile.bash --with-openmp --prefix=/home/crtrott/KokkosInstall/SNB-OpenMP --arch=SNB --compiler=g++ --kokkos-path=/home/crtrott/kokkos
(2) make install
(3) cd ~/mantevo/trunk/packages/miniAero/miniAero_Kokkos/build/
(4) make -j 

that worked for non KNC, for KNC we need to fix the linking step of the library itself I guess.

**Comment by nmhamster** [comment] 2015-05-14 23:53
ar should be fine for Kokkos (assuming you want .a file), if not xiar
might be needed from Intel.
-- 
Si Hammond

Scalable Computer Architectures
Sandia National Laboratories, NM, USA

**Comment by crtrott** [comment] 2015-06-15 21:09
I think this was fixed. If you encounter this issue again feel free to reopen/make a new issue.

**Closed by crtrott** 2015-06-15 21:09 UTC
