### ISSUE TITLE
openmp.team_broadcast_long unit test segfaults with gcc/10.2.0

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4017] opened 2021-05-10 22:15 UTC
The `openmp.team_broadcast_long` test segfaults in gcc/10.2.0 release builds with the OpenMP backend on SKX architectures. This does not occur if debugging and boundschecking are enabled. Also, this does not occur with gcc/7.2.0 on the same system.

This occurs with the develop branch and the release-candidate-3.4.1 branch

## Reproducer instructions (blake testbed):

```
module load cmake/3.19.3 gcc/10.2.0

cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized"  -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_SKX=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH
```

**Comment by rgayatri23** [comment] 2021-07-12 18:40
I tried this on Cori-GPU which also has a Skylake CPU but was unable to reproduce the issue following the above steps.
Can you give me any other pointers ? 
I tried it with both release-candidate-3.4.1 and with the develop branch.

```
rgayatri@cgpu05:~/Kokkos/upstream/kokkos/build_issue_4017> g++ --version
g++ (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rgayatri@cgpu05:~/Kokkos/upstream/kokkos/build_issue_4017> ./core/unit_test/KokkosCore_UnitTest_OpenMP --gtest_filter=*team_broadcast_long*
Note: Google Test filter = *team_broadcast_long*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from openmp
[ RUN      ] openmp.team_broadcast_long
[       OK ] openmp.team_broadcast_long (16 ms)
[----------] 1 test from openmp (16 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (16 ms total)
[  PASSED  ] 1 test.
```

**Comment by ndellingwood** [comment] 2021-07-14 17:23
@rgayatri23 let me retest this build on our SKX testbed, it may be that other updates in Kokkos happened to resolve this

**Comment by ndellingwood** [comment] 2021-07-14 17:43
I'm still seeing the seg fault on our testbed with SHA 9d53f39440c1614d8cac05e9c53a1e075f267481:

```
bash-4.2$ ./KokkosCore_UnitTest_OpenMP --gtest_filter=*broadcast*
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
Note: Google Test filter = *broadcast*
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from openmp
[ RUN      ] openmp.team_broadcast_long
Segmentation fault (core dumped)
```

This is running on `Intel(R) Xeon(R) Platinum 8160 CPU` hardware

**Comment by rgayatri23** [comment] 2021-07-16 00:03
Do you still observe that with the current develop branch? I tried running the same SHA and still dint see the error : 

```
rgayatri@cgpu18:~/Kokkos/upstream/kokkos/build_issue_4017> echo $(git log --pretty=format:'%h' -n 1)
9d53f394

rgayatri@cgpu18:~/Kokkos/upstream/kokkos/build_issue_4017> ./core/unit_test/KokkosCore_UnitTest_OpenMP --gtest_filter=*broadcast*
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
Note: Google Test filter = *broadcast*
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from openmp
[ RUN      ] openmp.team_broadcast_long
[       OK ] openmp.team_broadcast_long (17 ms)
[ RUN      ] openmp.team_broadcast_char
[       OK ] openmp.team_broadcast_char (16 ms)
[ RUN      ] openmp.team_broadcast_float
[       OK ] openmp.team_broadcast_float (17 ms)
[ RUN      ] openmp.team_broadcast_double
[       OK ] openmp.team_broadcast_double (16 ms)
[----------] 4 tests from openmp (66 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (66 ms total)
[  PASSED  ] 4 tests.
```

FYI - I am running on  Intel Xeon Gold 6148 ('Skylake')

**Comment by ndellingwood** [comment] 2021-07-16 21:04
This still fails for me with develop (SHA 35ae5dc71bdb1ce85c3102279b13bb4d5e8771e3 at time of build and test)

**Comment by dalg24** [comment] 2021-12-01 19:58
Check if that is still an issue

**Comment by ndellingwood** [comment] 2022-01-19 19:42
I still see a seg fault on our Blake machine, tested with SHA b033b5d00d82552726221b7b551142937541b38e. This does not occur with debugging enabled.

**Comment by ajpowelsnl** [comment] 2022-04-20 18:23
Hi @ndellingwood and @rgayatri23 -- is this issue still active?

**Comment by ajpowelsnl** [comment] 2022-08-22 19:25
Hi @ndellingwood -- has this issue been resolved?

**Comment by ndellingwood** [comment] 2022-08-22 20:30
Hi @ajpowelsnl I still see the seg fault in the config above updated for c++17, with sha 0b9dee7977da2cc2dfef47b73f9f8f5489410e4c

**Comment by ndellingwood** [comment] 2022-08-22 22:54
Running through gdb:
```
[ RUN      ] openmp.team_broadcast_long

Thread 1 "KokkosCore_Unit" received signal SIGSEGV, Segmentation fault.
0x0000000000ae2dd3 in Kokkos::Impl::ParallelReduce<Test::(anonymous namespace)::TestTeamBroadcast<Kokkos::OpenMP, Kokkos::Schedule<Kokkos::Static>, long, void>, Kokkos::TeamPolicy<Kokkos::Schedule<Kokkos::Static>, Kokkos::OpenMP>, Kokkos::InvalidType, Kokkos::OpenMP>::execute() const [clone ._omp_fn.0] ()
```

**Comment by ndellingwood** [comment] 2022-08-22 23:26
If I change the arch from `-DKokkos_ARCH_SKX=ON` to `-DKokkos_ARCH_SKL=ON` the test passes, @ajpowelsnl I'll update the build and we can close this issue, thanks for checking in!

**Comment by ndellingwood** [comment] 2022-08-22 23:28
Strange to me that the failure does not show with the debug build, I would guess it should fail in both cases with the arch (and underlying flags) mismatch?

**Comment by crtrott** [comment] 2022-08-22 23:32
This is not correct technically. Blake is SKX not SKL (which is a subset of SKX).

**Comment by ajpowelsnl** [comment] 2022-10-07 19:32
@crtrott , @dalg24, @ndellingwood , @rgayatri23 -- I am able to reproduce the seg fault when I run **_all_** of the OpenMP tests:

```core/unit_test/KokkosCore_UnitTest_OpenMP
...

[ RUN      ] openmp.team_broadcast_long
Segmentation fault
```
But I **_cannot_** reproduce the seg fault failure when I run the single test (even running > 10 times):

```
-bash-4.2$ core/unit_test/KokkosCore_UnitTest_OpenMP --gtest_filter=team_broadcast_long
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
Note: Google Test filter = team_broadcast_long
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.
```

**Comment by ajpowelsnl** [comment] 2022-11-22 21:57
To build with address / thread sanitizer:

```
cmake \
-DCMAKE_CXX_COMPILER=g++ \
-DCMAKE_CXX_FLAGS="-g \
-fsanitize=thread \
-Wall \
-Wunused-parameter \
-Wshadow \
-Wpedantic \
-Wsign-compare \
-Wtype-limits \
-Wignored-qualifiers \
-Wempty-body \
-Wclobbered \
-Wuninitialized"  \
-DKokkos_ENABLE_OPENMP=ON \
-DKokkos_ARCH_SKX=ON \
-DKokkos_ENABLE_TESTS=ON \
-DKokkos_ENABLE_EXAMPLES=OFF \
-DKokkos_ENABLE_LARGE_MEM_TESTS=ON \
-DCMAKE_VERBOSE_MAKEFILE=ON \
-DCMAKE_CXX_EXTENSIONS=OFF \
-DCMAKE_CXX_STANDARD=17 \
-DCMAKE_BUILD_TYPE=Release ..
```
# Flag to use if address sanitizer:
# -fsanitize=address \

**Comment by PhilMiller** [comment] 2022-11-27 16:06
Transcribing my debugging process suggestions from a Slack conversation while I was away with only my phone:

> What I'd suggest is to look for variables in the tsan logs that either are part of the crash, or have assignments to/from them, or are used in calculating them. Once you have a candidate or a few, convert them to using atomic_load/store, and see if things calm down

> In the long run, we basically want to do that conversion to everything, so it won't be wasted work if any given one doesn't solve it

> Process wise, I'd suggest making a separate commit for each variable converted, so that it's easier to review later

> #5530 would be a good refresher [...]

Looking at this again, the TSan logs may be a good adjunct to the details already described here - just focusing on the variables used to compute the addresses of the `src` and `dest` arguments to the failing `join` call from the stack trace should point the right direction

**Comment by ajpowelsnl** [comment] 2024-04-22 18:14
@ndellingwood , @crtrott -- any updates on this issue?

**Comment by ndellingwood** [comment] 2024-05-14 18:16
The HW in the original post is no longer available; I'll cycle back to testing on what is available on blake (SPR) and update the issue after DST is complete this week

**Comment by ndellingwood** [comment] 2024-05-21 21:44
Retested with sha 1d9d0df2eecfce635fe5c77559eb17adfa128d04 on Blake after HW and SW updates (original posted configuration no longer usable), with gcc/11.3.0 for SKX arch, the `openmp.team_broadcast_long` test passed in each case

**Configuration line**:
```
# Configured for SKX
cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-O3 -Wall -Wno-deprecated-declarations -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized"  -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_SKX=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ARCH_SKX=ON $KOKKOS_PATH
```

**Run as**:
```
 ./core/unit_test/Kokkos_CoreUnitTest_OpenMP --gtest_filter=openmp.team_broadcast_long
```

Note: the `-Wno-deprecated-declarations` flag added to avoid `-Werror` of form: 
```
/home/ndellin/kokkos/containers/src/Kokkos_Vector.hpp:33:67: error: 'int {anonymous}::emit_warning_kokkos_vector_deprecated()' is deprecated: Deprecated <Kokkos_Vector.hpp> header is included [-Werror=deprecated-declarations]
   33 | static auto do_not_include = emit_warning_kokkos_vector_deprecated();
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/ndellin/kokkos/containers/src/Kokkos_Vector.hpp:30:1: note: declared here
   30 | emit_warning_kokkos_vector_deprecated() {
```

I think this is just an artifact of my configuration since my build had the defaults `Kokkos_ENABLE_DEPRECATION_WARNINGS:BOOL=ON` and `Kokkos_ENABLE_DEPRECATED_CODE_4:BOOL=ON` set

**Comment by dalg24** [comment] 2024-05-21 22:14
You should not need the `-Wno-deprecated-declarations` flag since #6999 and #7016

**Comment by ndellingwood** [comment] 2024-05-21 22:36
@dalg24 thanks for clarifying, the sha I tested was before merge of those commits

**Comment by ajpowelsnl** [comment] 2024-06-03 23:12
closing because cannot reproduce

**Closed by ajpowelsnl** 2024-06-03 23:12 UTC
Labels: Bug

**Comment by dalg24** [comment] 2024-06-03 23:18
Did Nathan say it was ok to close?

**Comment by ajpowelsnl** [comment] 2024-06-03 23:23
> Did Nathan say it was ok to close?

Yes, we all conferred, and decided to close.
