### ISSUE TITLE
parallel_reduce with const return value reference doesn't fail like it should

### ISSUE THREAD

**Issue by dhollman** [kokkos/kokkos#2090] opened 2019-04-09 17:12 UTC
The following snippet compiles, runs, and prints `0`:

```c++
    const int value = 0;

    Kokkos::parallel_reduce(42,
      KOKKOS_LAMBDA (int i, int& result) {
        result += 1;
      },
      value
    );

    Kokkos::fence();
    std::cout << value << std::endl;
```

This feels like a bug...

**Comment by dhollman** [comment] 2019-04-09 17:14
I'll clean this up along with #2034 and #2088, but for now I thought it should be documented as a known bug.

**Comment by crtrott** [comment] 2019-04-09 17:39
Its not a bug. Its user error, but we can help the user.

**Comment by crtrott** [comment] 2019-04-09 17:39
I.e. bugs are generally things which are expected to work, but don't.

**Comment by crtrott** [comment] 2019-04-09 17:45
Oh I see where this is coming from ...

**Comment by ajpowelsnl** [comment] 2022-06-08 20:23
@dalg24 and @masterleinad -- can we close this issue?

**Comment by masterleinad** [comment] 2022-06-08 20:38
@ajpowelsnl It has the `InDevelop` tag.

**Closed** 2022-06-08 21:58 UTC
Labels: Enhancement, InDevelop
