### ISSUE TITLE
Assert error while compiling Kokkos OpenMPTarget Backend with Clang

### ISSUE THREAD

**Issue by chichunchen** [kokkos/kokkos#3370] opened 2020-09-09 17:37 UTC
Assert "Trying to aggregate-copy a type without a trivial copy/move constructor or assignment operator" compiling Kokkos OpenMP Backend with Clang 10/11/12.

```
llvm-project/clang/lib/CodeGen/CGExprAgg.cpp:1980: void clang::CodeGen::CodeGenFunction::EmitAggregateCopy(clang::CodeGen::LValue, clang::CodeGen::LValue, clang::QualType, clang::CodeGen::AggValueSlot::Overlap_t, bool): Assertion `(Record->hasTrivialCopyConstructor() || Record->hasTrivialCopyAssignment() || Record->hasTrivialMoveConstructor() || Record->hasTrivialMoveAssignment() || Record->isUnion()) && "Trying to aggregate-copy a type without a trivial copy/move " "constructor or assignment operator"' failed.
```

This assertion error only occurs when compiling OpenMPTarget backend and if I commented out the OpenMP pragma in `OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp` line 666 and line 691, the asserts go away:

```
diff --git a/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp b/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp
index d92712d2..32600d13 100644
--- a/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp
+++ b/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp
@@ -663,7 +663,7 @@ struct ParallelReduceSpecialize<FunctorType, PolicyType, ReducerType,
     OpenMPTargetReducerWrapper<ReducerType>::init(result);

 // clang-format off
-#pragma omp target teams distribute parallel for num_teams(512) map(to: f) \
+//#pragma omp target teams distribute parallel for num_teams(512) map(to: f) \
     map(tofrom: result) reduction(custom: result)
     for (auto i = begin; i < end; i++) f(i, result);
     // clang-format on
@@ -688,7 +688,7 @@ struct ParallelReduceSpecialize<FunctorType, PolicyType, ReducerType,
     OpenMPTargetReducerWrapper<ReducerType>::init(result);

 // clang-format off
-#pragma omp target teams distribute parallel for num_teams(512) map(to: f) \
+//#pragma omp target teams distribute parallel for num_teams(512) map(to: f) \
     map(tofrom: result) reduction(custom: result)
     for (auto i = begin; i < end; i++) f(TagType(), i, result);
     // clang-format on
```

The other quick workaround to fix the assertion error is simply commented out the copy constructor in `array_reduce` class in `core/unit_test/TestNonTrivialScalarTypes.hpp`. But it only solves the build issue and might fails the runtime test.

Replacing the `target teams distribute parallel for` construct in `Kokkos_OpenMPTarget_Parallel.hpp` with `parallel for` can avoid the asserts, therefore, I'm guessing that Clang has some bug or haven't fully supported it.

**Comment by crtrott** [comment] 2020-09-11 14:58
This is a contentious issue right now. Whether to only allow trivially copyable classes to be captured. Technically that is what the OpenMP standard says in practice the implementation ignored this so far. Note Kokkos::View is NOT trivially copyable and can not be. We are working with compiler folks on figuring out what to do. Earlier versions of Clang should work (since we test them) - in fact we do test clang 10.0 so I am not sure why that would fail for you (see kokkos/scripts/docker/Dockerfile.openmptarget and kokkos/.jenkins).

**Comment by chichunchen** [comment] 2020-09-14 20:55
I think the reason why clang doesn't report assertion failure due to the fact that the docker file is using the release version of Clang. However, ignoring the assertion failure might lead to runtime failure. (I also didn't see make test in dockerfile)

**Comment by PhilMiller** [comment] 2023-04-14 16:32
@rgayatri23 Is this still a relevant concern? If not, please close it.

**Comment by PhilMiller** [comment] 2023-04-14 16:32
If it is, maybe update the issue title to be more specific?

**Comment by rgayatri23** [comment] 2023-04-14 18:51
The issue is not valid with the latest clang versions of 15 and 16.

**Closed by rgayatri23** 2023-04-14 18:51 UTC
Labels: Backend - OpenMPTarget
