### ISSUE TITLE
MDRangePolicy kernel not launched for certain inputs

### ISSUE THREAD

**Issue by msimberg** [kokkos/kokkos#4192] opened 2021-07-28 15:12 UTC
A kernel with an `MDRangePolicy` on CUDA is sometimes quietly not launched at all. Reproducer:

```
#include <Kokkos_Core.hpp>
#include <cassert>
#include <cstdio>

int main(int argc, char* argv[]) {
  int N = 1 << 1;
  int M = 1 << 17;

  Kokkos::initialize(argc, argv);

  {
    Kokkos::View<double**> A("A", N, M);
    auto h_A = Kokkos::create_mirror_view(A);

    Kokkos::parallel_for(
        Kokkos::MDRangePolicy<Kokkos::Rank<2>>({0, 0}, {N, M}),
        KOKKOS_LAMBDA(int i, int j) {
          printf("initializing (i, j) = (%d, %d)\n", i, j);
          A(i, j) = i + j;
        });

    Kokkos::deep_copy(h_A, A);

    for (int i = 0; i < N; ++i) {
      for (int j = 0; j < M; ++j) {
        assert(h_A(i, j) == i + j);
      }
    }
  }

  Kokkos::finalize();
}
```

This was tested on a P100 with CUDA 11.0.2, GCC 9.3.0, and Kokkos develop/3.4.01. Is this behaviour expected? I'd at the very least expect a runtime error if certain inputs can't be handled, but certainly not the kernel launch being silently ignored.

**Comment by Rombur** [comment] 2021-08-04 15:10
I can confirm that the code above does not launch the kernel. This is because the block size than we compute is greater than 65535 which is the maximum size for the y- and the z-dimension. The maximum size of the x-dimension is `2^31-1` unfortunately we are using the y-dimension.

Concerning the error message, you need to use `-DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON` to get an error. This is what I get:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetLastError() error( cudaErrorInvalidConfiguration): invalid configuration argument /opt/kokkos/include/Cuda/Kokkos_Cuda_KernelLaunch.hpp:644
Traceback functionality not available
```
This option is not set by default in debug mode because it increases the runtime for each kernel launch. The option is documented in https://github.com/kokkos/kokkos/blob/master/BUILD.md.

**Comment by msimberg** [comment] 2021-08-05 13:11
Thanks for the reply! It's definitely good to know that enabling bounds checking at least catches that; I was not aware of that option.

That said, is this something you think is fixable? I'd just like to add that this is not critical for me. I mainly wanted to report this since the behaviour is odd to me. I'd imagine others might have been affected by this though.

**Comment by ajpowelsnl** [comment] 2022-04-20 18:26
@Rombur -- please have a look!

**Comment by ajpowelsnl** [comment] 2022-06-06 19:10
Hi @Rombur -- Is this issue still on your RADAR?

**Comment by Rombur** [comment] 2022-06-29 20:18
This has been fixed by https://github.com/kokkos/kokkos/pull/4559 The fix is already in 3..6 so closing this

**Closed by Rombur** 2022-06-29 20:18 UTC
Labels: Bug
