### ISSUE TITLE
deep_copy scalar into scratch View fails to compile

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#2723] opened 2020-02-05 14:54 UTC
in trilinos/trilinos#6747, @tasmith4 writes:

For the following statement:

      Kokkos::deep_copy(multiDimViews[i]->get_scratch_view_1D(0), i+1);

we get this build error after updating to the latest Trilinos (develop branch):

```
/tmp/tasmit/exawind/install/intel/trilinos/include/Kokkos_CopyViews.hpp(1430): error #373: "Kokkos::ScratchMemorySpace<ExecSpace>::ScratchMemorySp
ace() [with ExecSpace=Kokkos::OpenMP]" (declared at line 79 of "/tmp/tasmit/exawind/install/intel/trilinos/include/Kokkos_ScratchSpace.hpp") is in
accessible
              typename ViewType::memory_space().name()),
              ^
          detected during instantiation of "void Kokkos::deep_copy(const Kokkos::View<DT, DP...> &, Kokkos::ViewTraits<DT, DP...>::const_value_typ
e &, std::enable_if<std::is_same<Kokkos::ViewTraits<DT, DP...>::specialize, void>::value, void>::type *) [with DT=double *, DP=<Kokkos::LayoutRigh
t, sierra::nalu::DeviceShmem, Kokkos::MemoryUnmanaged>]" at line 137 of "/tmp/tasmit/exawind/source/nalu-wind/unit_tests/UnitTestCopyAndInterleave
.C"
```

Our code has not changed recently -- is there something we need to change in how we call `Kokkos::deep_copy`?

**Comment by alanw0** [comment] 2020-02-05 22:56
FYI, the ExaWind nalu-wind nightly build is broken due to this issue, dashboard is here: https://my.cdash.org/index.php?project=Nalu-Wind
If there is something we need to change in nalu-wind's usage of deep_copy, please let us know.

**Comment by masterleinad** [comment] 2020-02-06 00:24
Would you have a standalone reproducer in `Kokkos`?

**Comment by alanw0** [comment] 2020-02-06 02:50
Here's a pure-kokkos reproducer which has the above compile error:

```
using TestDeviceTeamPolicy = Kokkos::TeamPolicy<Kokkos::DefaultExecutionSpace>;

template<typename T, typename SHMEMTYPE>
using ShMemView = Kokkos::View<T,Kokkos::LayoutRight,SHMEMTYPE,Kokkos::MemoryUnmanaged>;

void do_the_deep_copy_test()
{
  const int bytes_per_team = 256, bytes_per_thread = 256;
  const int threads_per_team = 1;

  TestDeviceTeamPolicy policy(1, threads_per_team);
  auto team_exec = policy.set_scratch_size(1, Kokkos::PerTeam(bytes_per_team),
                                              Kokkos::PerThread(bytes_per_thread));

  const int N = 8;

  Kokkos::parallel_for(team_exec, KOKKOS_LAMBDA(const sierra::nalu::DeviceTeamHandleType& team)  {

    ShMemView<double**,ShmemType> shview = Kokkos::subview(ShMemView<double***,ShmemType>(team.team_scratch(1),team.team_size(), N, N), team.team_rank(), Kokkos::ALL(), Kokkos::ALL());

    Kokkos::parallel_for(Kokkos::TeamThreadRange(team, 1), [&](const size_t&  /* index */)
    {   
      Kokkos::deep_copy(shview, 5.0);
    }); 
  });     
}

TEST(PureKokkos, ScratchDeepCopy)
{
  do_the_deep_copy_test();
}
```

**Comment by wilsonrvornlgov** [comment] 2020-02-10 17:52
Are there any workarounds for this issue? Is there a timeframe for a resolution? Thanks.

**Comment by alanw0** [comment] 2020-02-10 18:08
I'm working on a workaround in nalu-wind now, should have it checked in today, so the nalu-wind dashboard will hopefully be back up tomorrow.

**Comment by masterleinad** [comment] 2020-02-10 18:16
I am looking into this. Was it working with a previous release?

**Comment by alanw0** [comment] 2020-02-10 18:23
Yes it's been working for a long time, it appears to have broken approximately a week ago. (nalu-wind attempts to pull and build the trilinos develop branch each night.)

**Comment by masterleinad** [comment] 2020-02-10 18:42
So the problem is at 
https://github.com/kokkos/kokkos/blob/ecce45d55952db8a36f97c2d1d7ac8847144e9f1/core/src/Kokkos_CopyViews.hpp#L1427-L1436
due to `Kokkos::ScratchMemorySpace` not being default constructible. `name()` should be a static member function here (and called as such), but `Kokkos::ScratchMemorySpace` doesn't implement that either. This is related to #2233.
This was not a problem in previous releases since that profiling feature was not implemented. Since all the occurrences are guarded by `KOKKOS_ENABLE_PROFILING`, disabling that feature should work as a workaround.
The following patch also works for me:
```C++
diff --git a/core/src/Kokkos_CopyViews.hpp b/core/src/Kokkos_CopyViews.hpp
index 96c3cd7a..e312fbf5 100644
--- a/core/src/Kokkos_CopyViews.hpp
+++ b/core/src/Kokkos_CopyViews.hpp
@@ -1427,8 +1427,7 @@ inline void deep_copy(
 #if defined(KOKKOS_ENABLE_PROFILING)
   if (Kokkos::Profiling::profileLibraryLoaded()) {
     Kokkos::Profiling::beginDeepCopy(
-        Kokkos::Profiling::SpaceHandle(
-            typename ViewType::memory_space().name()),
+        Kokkos::Profiling::SpaceHandle(ViewType::memory_space::name()),
         dst.label(), dst.data(),
         Kokkos::Profiling::SpaceHandle(Kokkos::HostSpace().name()), "Scalar",
         &value, dst.span() * sizeof(typename ViewType::value_type));
@@ -1554,7 +1553,7 @@ inline void deep_copy(
   if (Kokkos::Profiling::profileLibraryLoaded()) {
     Kokkos::Profiling::beginDeepCopy(
         Kokkos::Profiling::SpaceHandle(Kokkos::HostSpace().name()), "Scalar",
-        &dst, Kokkos::Profiling::SpaceHandle(src_memory_space().name()),
+        &dst, Kokkos::Profiling::SpaceHandle(src_memory_space::name()),
         src.label(), src.data(),
         src.span() * sizeof(typename src_traits::value_type));
   }
@@ -1604,8 +1603,8 @@ inline void deep_copy(
 #if defined(KOKKOS_ENABLE_PROFILING)
   if (Kokkos::Profiling::profileLibraryLoaded()) {
     Kokkos::Profiling::beginDeepCopy(
-        Kokkos::Profiling::SpaceHandle(dst_memory_space().name()), dst.label(),
-        dst.data(), Kokkos::Profiling::SpaceHandle(src_memory_space().name()),
+        Kokkos::Profiling::SpaceHandle(dst_memory_space::name()), dst.label(),
+        dst.data(), Kokkos::Profiling::SpaceHandle(src_memory_space::name()),
         src.label(), src.data(),
         src.span() * sizeof(typename dst_type::value_type));
   }
@@ -1665,8 +1664,8 @@ inline void deep_copy(
 #if defined(KOKKOS_ENABLE_PROFILING)
   if (Kokkos::Profiling::profileLibraryLoaded()) {
     Kokkos::Profiling::beginDeepCopy(
-        Kokkos::Profiling::SpaceHandle(dst_memory_space().name()), dst.label(),
-        dst.data(), Kokkos::Profiling::SpaceHandle(src_memory_space().name()),
+        Kokkos::Profiling::SpaceHandle(dst_memory_space::name()), dst.label(),
+        dst.data(), Kokkos::Profiling::SpaceHandle(src_memory_space::name()),
         src.label(), src.data(),
         src.span() * sizeof(typename dst_type::value_type));
   }
@@ -2640,7 +2639,7 @@ inline void deep_copy(
 #if defined(KOKKOS_ENABLE_PROFILING)
   if (Kokkos::Profiling::profileLibraryLoaded()) {
     Kokkos::Profiling::beginDeepCopy(
-        Kokkos::Profiling::SpaceHandle(dst_memory_space().name()), dst.label(),
+        Kokkos::Profiling::SpaceHandle(dst_memory_space::name()), dst.label(),
         dst.data(), Kokkos::Profiling::SpaceHandle(Kokkos::HostSpace().name()),
         "(none)", &value, dst.span() * sizeof(typename dst_traits::value_type));
   }
@@ -2675,7 +2674,7 @@ inline void deep_copy(
   if (Kokkos::Profiling::profileLibraryLoaded()) {
     Kokkos::Profiling::beginDeepCopy(
         Kokkos::Profiling::SpaceHandle(Kokkos::HostSpace().name()), "(none)",
-        &dst, Kokkos::Profiling::SpaceHandle(src_memory_space().name()),
+        &dst, Kokkos::Profiling::SpaceHandle(src_memory_space::name()),
         src.label(), src.data(), sizeof(ST));
   }
 #endif
@@ -2723,8 +2722,8 @@ inline void deep_copy(
 #if defined(KOKKOS_ENABLE_PROFILING)
   if (Kokkos::Profiling::profileLibraryLoaded()) {
     Kokkos::Profiling::beginDeepCopy(
-        Kokkos::Profiling::SpaceHandle(dst_memory_space().name()), dst.label(),
-        dst.data(), Kokkos::Profiling::SpaceHandle(src_memory_space().name()),
+        Kokkos::Profiling::SpaceHandle(dst_memory_space::name()), dst.label(),
+        dst.data(), Kokkos::Profiling::SpaceHandle(src_memory_space::name()),
         src.label(), src.data(), sizeof(DT));
   }
 #endif
@@ -2787,8 +2786,8 @@ inline void deep_copy(
 #if defined(KOKKOS_ENABLE_PROFILING)
   if (Kokkos::Profiling::profileLibraryLoaded()) {
     Kokkos::Profiling::beginDeepCopy(
-        Kokkos::Profiling::SpaceHandle(dst_memory_space().name()), dst.label(),
-        dst.data(), Kokkos::Profiling::SpaceHandle(src_memory_space().name()),
+        Kokkos::Profiling::SpaceHandle(dst_memory_space::name()), dst.label(),
+        dst.data(), Kokkos::Profiling::SpaceHandle(src_memory_space::name()),
         src.label(), src.data(), dst.span() * sizeof(dst_value_type));
   }
 #endif
diff --git a/core/src/Kokkos_ScratchSpace.hpp b/core/src/Kokkos_ScratchSpace.hpp
index 64c4667c..212c9c4d 100644
--- a/core/src/Kokkos_ScratchSpace.hpp
+++ b/core/src/Kokkos_ScratchSpace.hpp
@@ -91,6 +91,8 @@ class ScratchMemorySpace {
   typedef typename ExecSpace::array_layout array_layout;
   typedef typename ExecSpace::size_type size_type;
 
+  static constexpr const char* name() { return "ScratchMemorySpace"; }
+
   template <typename IntType>
   KOKKOS_INLINE_FUNCTION static IntType align(const IntType& size) {
     return (size + MASK) & ~MASK;
```

**Comment by tasmith4** [comment] 2020-02-10 18:52
@masterleinad, thanks for the explanation -- that makes sense.  Can we expect your patch in Kokkos soon or are there other issues involved?

**Comment by masterleinad** [comment] 2020-02-10 19:03
There will be a pull request today (against `develop`).

**Comment by tasmith4** [comment] 2020-02-10 20:35
Great, thanks!

**Comment by masterleinad** [comment] 2020-02-11 01:36
@alanwo The example in https://github.com/kokkos/kokkos/issues/2723#issuecomment-582711516 looks a bit interesting since you can't use `Kokkos::deep_copy` in a `CUDA` kernel. Do you have an example that also uses `CUDA`?

**Comment by alanw0** [comment] 2020-02-11 01:54
@masterleinad That example was taken from a unit-test that doesn't run on cuda but runs for openmp. The compile-error was seen on a gcc 7.2.0 build, no cuda.
Today I refactored the unit-test to no-longer use deep_copy so that our code could resume building.

Is it general guidance that deep_copy can't be used for scratch-space views? That might be reasonable since scratch-space doesn't exist outside of kernels (right?).

**Comment by masterleinad** [comment] 2020-02-11 02:27
You could call the `ScratchMemorySpace` constructor yourself with valid pointers to the memory to be used. In that case, you could still create a `View` and use `deep_copy`.
Usually, you obtain access to the shared memory in a kernel, though, (as your example code also shows) and `deep_copy` can at least not be used for a device execution space (since it is a `host` function).

**Comment by dhollman** [comment] 2020-02-11 09:53
This should work. We'll look into it. For self-similarity arguments, among others, `deep_copy` to `View`s of scratch memory should semantically work the same way as `deep_copy` on other views. This should work with whatever we ended up naming the local deep copy (did we give it a different name or just make it an overload?)

**Comment by crtrott** [comment] 2020-02-12 13:40
Ok this is problematic for various reasons. Right now we have something called `local_deep_copy` for being called inside of Kernels. `deep_copy` is not currently legal to be called inside of kernels. The primary reason for calling this different is that we can not reliably detect whether we are within kernel code with all backends, and at the same time we can not detect from the arguments which version we should call (obviously for scratch memory it should be fine, but for everything else it is not).

**Comment by crtrott** [comment] 2020-02-12 13:48
Just to clarify: this is user error. `Kokkos::deep_copy` is not allowed to be used inside of Kernels. `Kokkos::Experimental::local_deep_copy` provides this capability. And it has an overload to take the team handle if called inside a hierarchical kernel.

**Comment by crtrott** [comment] 2020-02-12 13:49
In the above test case you should call it without the `team_handle` btw since it is done with individual threads.

**Closed** 2020-04-14 21:38 UTC
Labels: InDevelop
