### ISSUE TITLE
Add static_assert to ensure reduction value_type is word-aligned POD

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#226] opened 2016-03-26 02:20 UTC
In the words of @hcedwar from #225:

"Reduction value_type needs to be a word-aligned plain-old-data type. Unfortunately `bool` can be compiled to a fraction of a word, which is probably the source of the error. We should introduce a `static_assert` to catch / enforce this requirement."

**Comment by nmhamster** [comment] 2016-03-26 04:21
Can you explain what you are seeing there? On most CPU platforms it will be sufficient to just be within a single cache line.

**Comment by ibaned** [comment] 2016-03-26 13:20
@nmhamster: Please note my example code in #225. When I set value_type to be `bool`, I get a false return value even when the arrays have the same content. Via asserts I tracked it down to the `join` function receiving a false `update` value despite me never setting `update` to false in any function. Also, this is on a GPU platform: NVidia K40 on Shannon. I'm fine with this simply being disallowed usage, but if its unclear why this fails, this is what I know.

**Comment by hcedwar** [comment] 2016-03-29 14:29
Duplicate of issue #225

**Comment by crtrott** [comment] 2016-04-01 02:46
Merged

**Closed by crtrott** 2016-04-01 02:46 UTC
Labels: bug, bug - fix pushed to develop branch, duplicate
