### ISSUE TITLE
Kokkos build failure with intel/19 and shared library support: unresolvable R_X86_64_TPOFF32 relocation against symbol

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4722] opened 2022-01-26 19:35 UTC
Kokkos builds with intel/19 and shared library support fail with the following type of output:

```
ld: CMakeFiles/KokkosCore_PerformanceTest_Mempool.dir/test_mempool.cpp.o(.text._ZN6Kokkos4Impl21ParallelReduceAdaptorINS_11RangePolicyIJNS_6SerialEN11TestFunctor15TagAllocDeallocEEEES4_lE7executeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS6_RKS4_Rl[_ZN6Kokkos4Impl21ParallelReduceAdaptorINS_11RangePolicyIJNS_6SerialEN11TestFunctor15TagAllocDeallocEEEES4_lE7executeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS6_RKS4_Rl]+0x3e8): unresolvable R_X86_64_TPOFF32 relocation against symbol `_ZN6Kokkos4Impl22SharedAllocationRecordIvvE18t_tracking_enabledE'
ld: final link failed: Nonrepresentable section on output
make[2]: *** [core/perf_test/KokkosCore_PerformanceTest_Mempool] Error 1
make[2]: Leaving directory `/home/ndellin/kokkos/testing/Intel19'
make[1]: *** [core/perf_test/CMakeFiles/KokkosCore_PerformanceTest_Mempool.dir/all] Error 2
```

**Reproducer** (kokkos-dev* modules referenced):
```
module load sems-archive-cmake/3.17.1 sems-archive-gcc/8.3.0 sems-archive-intel/19.0.5

cmake -DKokkos_ENABLE_SERIAL=ON -DCMAKE_CXX_COMPILER=icpc -DBUILD_SHARED_LIBS=ON -DKokkos_ENABLE_TESTS=ON $KOKKOS_PATH
```

**Comment by PhilMiller** [comment] 2022-01-26 19:37
This also showed up in Trilinos, https://github.com/trilinos/Trilinos/pull/10047#issuecomment-1018921116

My digging online suggests a missing `-fPIC` on some compilation unit.

**Comment by PhilMiller** [comment] 2022-01-26 20:03
Or, conversely, there could be `-fPIE` on a file that's ending up in a shared library rather than directly in a binary

**Comment by PhilMiller** [comment] 2022-01-27 00:58
Following the reproducer recipe, the tests link and run successfully with this bit of workaround code from 2019 removed:

```
$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 543047b..8df5a09 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -203,9 +203,9 @@ KOKKOS_SETUP_BUILD_ENVIRONMENT()
 
 OPTION(BUILD_SHARED_LIBS "Build shared libraries" OFF)
 # Workaround for building position independent code.
-IF(BUILD_SHARED_LIBS)
-  SET(CMAKE_POSITION_INDEPENDENT_CODE ON)
-ENDIF()
+#IF(BUILD_SHARED_LIBS)
+#  SET(CMAKE_POSITION_INDEPENDENT_CODE ON)
+#ENDIF()
 
 SET(KOKKOS_EXT_LIBRARIES Kokkos::kokkos Kokkos::kokkoscore Kokkos::kokkoscontainers Kokkos::kokkosalgorithms)
 SET(KOKKOS_INT_LIBRARIES kokkos kokkoscore kokkoscontainers kokkosalgorithms)
```

@masterleinad added that in #2288 in response to #2283

I confirmed with `make VERBOSE=1` that `-fPIC` does appear on compilation lines of the object files going into the shared libraries. The change drops `-fPIE` from the compilation lines of object files getting linked directly into the unit tests.

**Comment by PhilMiller** [comment] 2022-01-27 01:05
https://cmake.org/cmake/help/latest/policy/CMP0083.html#policy:CMP0083 may be the culprit - we may be depending on the `OLD` behavior, of not setting `-fPIE`

**Comment by PhilMiller** [comment] 2022-01-27 01:06
The tests also built and passed with gcc 8.3.0 with the workaround removed.

I'll try the policy setting next

**Comment by PhilMiller** [comment] 2022-01-27 01:17
Setting the policy to OLD worked to build and run the tests with gcc. On Intel, cmake is still passing `-fPIE` to the compilation of the unit test object files, and so still failing to link the subsequent binaries.

Unless we can identify the present environment in which the older workaround is still necessary, I recommend removing it.

**Comment by PhilMiller** [comment] 2022-01-27 01:20
I opened #4725 accordingly

**Comment by PhilMiller** [comment] 2022-01-27 02:41
Reading up on [the details of relocation types](https://docs.oracle.com/cd/E19120-01/open.solaris/819-0690/chapter8-1/index.html) (search for `R_AMD64_TPOFF32`), it looks like the Intel compiler is maybe generating wrong or overly optimistic code for accessing the variable in question, `t_tracking_enabled`. It's perhaps because it's confused about the declaration being inside a class template, perhaps specifically a template specialization, and treating it as a non-class `static thread_local` variable, which would be privately accessible within the same object file, and not across linking boundaries.

Code accessing this variable seems to be on the kernel launch path, but may not actually be performance critical. The implementations are inlined in `Kokkos_SharedAlloc.hpp` right now, with only the variable declaration itself in the .cpp file. If the variable and code accessing it were moved out of line to the .cpp file, and thus out of the class, I don't think this issue would come up.

**Comment by PhilMiller** [comment] 2022-01-27 03:20
Under Intel 19, depending on whether I compile with `-fPIE` or not, the generated relocation for that variable changes as follows:

```
$ grep TPOFF reloc.plain 
0000000000005835 R_X86_64_GOTTPOFF  _ZN6Kokkos4Impl22SharedAllocationRecordIvvE18t_tracking_enabledE-0x0000000000000004
[... more of the same on that one variable]

$ grep TPOFF reloc.fPIE
0000000000005d90 R_X86_64_TPOFF32  _ZN6Kokkos4Impl22SharedAllocationRecordIvvE18t_tracking_enabledE
[... more of the same on that one variable]
```
These correspond to the 'Initial Executable' (IE) and 'Local Executable' (LE) TLS models, respectively.

In contrast, GCC 8.3.0  with or without `-fPIE` generates the `GOTTPOFF` relocation.

I think this may be a bug in Intel's compiler, and possibly one that will bite us again down the line.

**Comment by PhilMiller** [comment] 2022-05-20 23:14
Release in 3.6.00, closing.

**Closed by PhilMiller** 2022-05-20 23:14 UTC
Labels: Bug, InDevelop
