### ISSUE TITLE
dual view with custom device type

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#2703] opened 2020-01-30 21:47 UTC
Trilinos enables UVM space and when I use dual view with CudaSpace, it causes alloc error as follows:
```
C++ exception with description "cudaMalloc( &ptr, arg_alloc_size ) error( cudaErrorIllegalAddress):
an illegal memory access was encountered /ascldap/users/kyukim/Work/lib/trilinos/kyukim
/packages/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:175
```
The problem is caused when I use DualView with `Kokkos::Device<Kokkos::Cuda,Kokkos::CudaSpace>`.
```
/// this causes dual view alloc problem
typedef Kokkos::Device<Kokkos::Cuda,Kokkos::CudaSpace> device_type;
Kokkos::DualView<value_type*,device_type> A("A", 100); /// not okay
Kokkos::DualView<value_type*,Kokkos::Cuda> B("B", 100); /// okay as its default paired memory space is uvm.
```
Any idea ?

**Comment by crtrott** [comment] 2020-02-02 01:50
This is weird.

**Comment by crtrott** [comment] 2020-02-02 01:55
I can not reproduce right now (neither master nor develop):
```c++
#include<Kokkos_Core.hpp>
#include<Kokkos_DualView.hpp>
int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
     int N = (argc>1) ? atoi(argv[1]) : 10000;
     int M = (argc>2) ? atoi(argv[2]) : 10000;
     int R = (argc>3) ? atoi(argv[3]) : 10;
     Kokkos::DualView<double*,Kokkos::Device<Kokkos::Cuda,Kokkos::CudaSpace>> a("A",N);
     Kokkos::fence();
  }
  Kokkos::finalize();
}
```

**Comment by PhilMiller** [comment] 2022-12-12 22:35
Wasn't reproducible in 2020, and no follow-up since then. Closing.

**Closed by PhilMiller** 2022-12-12 22:35 UTC
