### ISSUE TITLE
Nightly test failures following gtest update

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4400] opened 2021-10-13 02:59 UTC
Following merge of PR #4230 with the gtest update some nightly builds have begun failing. I'll add separate comments for different failing builds, @cz4rs would you have time to take a look?

**Comment by cz4rs** [comment] 2021-10-13 21:05
@ndellingwood @crtrott 
### Clang
- I could not reproduce this using provided configuration with `clang-9` or `clang-12` on Ubuntu (compiles and runs just fine). I don't think I can setup an environment with sems modules.
- TLDR: no idea why it wouldn't see `std::u8string` and no idea how to work around the issue (apart from reverting).

### Intel
- Newer compilers don't complain, so maybe disabling this warning for intel/17.0.1, intel/18.0.5, intel/19.0.5 could be a solution.
- Simply removing `operator()` seems to work fine (but this means patching external library, which doesn't seem like a good long-term solution):
```diff
diff --git a/tpls/gtest/gtest/gtest-all.cc b/tpls/gtest/gtest/gtest-all.cc
index eb8fa17c8..ca610336a 100644
--- a/tpls/gtest/gtest/gtest-all.cc
+++ b/tpls/gtest/gtest/gtest-all.cc
@@ -4293,11 +4293,6 @@ class TestNameIs {
   explicit TestNameIs(const char* name)
       : name_(name) {}
 
-  // Returns true if and only if the test name of test_info matches name_.
-  bool operator()(const TestInfo * test_info) const {
-    return test_info && test_info->name() == name_;
-  }
-
  private:
   std::string name_;
 };
```

Caveats:
- I have tested it with Clang, I don't have access to Intel classic compilers (they don't offer evaluation licenses anymore, pushing people towards oneAPI instead)

### Solutions
- #4404 simply reverts googletest library to the previous version we used
  - this should fix the nightly tests right now
  - I don't like switching back to old version but...
  - when #4384 is done, it should be easy to select whether the build should use old version from the repo or external (latest) one
  - if nightly builds have to be fixed really quickly, this is the way to go, because other solutions require more time (PR is marked as a draft, but it is actually ready for review & merge)
- While Intel warnings can be silenced / worked around, Clang error will not go away that easily - I will get back to it tomorrow.

**Comment by dalg24** [comment] 2021-10-13 21:24
About
```
<kokkos>/tpls/gtest/gtest/gtest.h:5446:55: error: no member named 'u8string' in namespace 'std'
GTEST_IMPL_FORMAT_C_STRING_AS_STRING_(char8_t, ::std::u8string);
```
I think the issue is the toolchain does not actually have a C++20 library

**Comment by ndellingwood** [comment] 2021-10-13 21:45
Thanks for the updates @cz4rs and @dalg24, let me confirm if the following steps should be taken on the testing side to help resolve the issue (as opposed to a revert or modification of gtest headers):

* Clang w/ c++20

> I think the issue is the toolchain does not actually have a C++20 library

For the clang builds gcc/8.3.0 is passed as the gcc-toolchain argument (i.e. `--gcc-toolchain=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/8.3.0/base`), I can try updating to gcc/9.3 and see if this resolves the error.

* Intel builds

I can add the `-Wno-unused-function` flag (unused-function warnings apparently set by -Wall) to the intel builds to disable those warnings, let me know if you'd prefer a different approach

**Comment by cz4rs** [comment] 2021-10-15 15:24
@ndellingwood Can you please confirm that the problem is fixed and close this issue if so?

**Closed** 2021-10-15 16:56 UTC
Labels: Bug
