### ISSUE TITLE
Nightly failures with openmp.partitioning_by_args , partitioning_by_vector subtests

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6670] opened 2023-12-14 03:23 UTC
**Describe the bug**
The openmp `partitioning_by_args` and `partitioning_by_vector` subtests fail in Cuda_OpenMP builds with cuda/11.2.2 and gcc/8.3.0 following recent update; presumably this will apply to other OpenMP jobs after nightly testing completes

**Test failures**:
```
[ RUN      ] openmp.partitioning_by_args
/home/jenkins/weaver/workspace/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/kokkos/core/unit_test/TestExecSpacePartitioning.hpp:105: Failure
Expected equality of these values:
  sum1
    Which is: -294063648
  sum2
    Which is: 2016
[  FAILED  ] openmp.partitioning_by_args (20 ms)
[ RUN      ] openmp.partitioning_by_vector
/home/jenkins/weaver/workspace/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/kokkos/core/unit_test/TestExecSpacePartitioning.hpp:105: Failure
Expected equality of these values:
  sum1
    Which is: -1367109152
  sum2
    Which is: 3297
[  FAILED  ] openmp.partitioning_by_vector (11 ms)
```

This follows merge of the following commits:

Fix builtin_unreachable use for MSVC/CUDA ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/334/changes#fb0380b91b79b5744ea2b12e28a5663c59aeacc4) / [githubweb](https://github.com/kokkos/kokkos/commit/fb0380b91b79b5744ea2b12e28a5663c59aeacc4))
    Fix missing include on msvc/cuda ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/334/changes#458910fbf37ba7fae78e54a2e5b78522cb1b2ccb) / [githubweb](https://github.com/kokkos/kokkos/commit/458910fbf37ba7fae78e54a2e5b78522cb1b2ccb))
    Avoid lambdas in constexpr branch for msvc/cuda ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/334/changes#7dcf1deba623ce533f905beb9f37bc26e2009144) / [githubweb](https://github.com/kokkos/kokkos/commit/7dcf1deba623ce533f905beb9f37bc26e2009144))
    Sidestep lacking CTAD support msvc/cuda ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/334/changes#249f8b4fb42679d37ee4cca9d0c3012739050ac2) / [githubweb](https://github.com/kokkos/kokkos/commit/249f8b4fb42679d37ee4cca9d0c3012739050ac2))
    Fix formatting ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/334/changes#c6d01e9435c0f16c84e8d191d723ebe5ef863cf7) / [githubweb](https://github.com/kokkos/kokkos/commit/c6d01e9435c0f16c84e8d191d723ebe5ef863cf7))
    Move header for Damien because he is right ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/334/changes#e524ec7777bb2f6f06391bbea0bc007f624ee599) / [githubweb](https://github.com/kokkos/kokkos/commit/e524ec7777bb2f6f06391bbea0bc007f624ee599))
    Add CMakeLists.txt for stream benchmark ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/334/changes#379d5db1a67a1bad6d7d9c8e25a6933655fc8c5e) / [githubweb](https://github.com/kokkos/kokkos/commit/379d5db1a67a1bad6d7d9c8e25a6933655fc8c5e))
    Drop guards to accommodate external code defining KOKKOS_ASSERT ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/334/changes#ae71e400213ae256c352e3e8c46cdc9db6d089bf) / [githubweb](https://github.com/kokkos/kokkos/commit/ae71e400213ae256c352e3e8c46cdc9db6d089bf))
    Use omp_get_max_active_levels() when supported ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta-debug/334/changes#a996c12a0315957458df283b5ea797b3e10573ee) / [githubweb](https://github.com/kokkos/kokkos/commit/a996c12a0315957458df283b5ea797b3e10573ee))

**Reproducer configuration** (weaver rhel8 queue):
```bash
module load cuda/11.2.2/gcc/8.3.1 cmake/3.23.1

${KOKKOS_PATH}/generate_makefile.bash --with-cuda --with-openmp --compiler=${KOKKOS_PATH}/bin/nvcc_wrapper --arch=Volta70,Power9 --with-cuda-options=enable_lambda --kokkos-path=${KOKKOS_PATH} --debug --cxxstandard=17
```

**Comment by dalg24** [comment] 2023-12-14 14:01
Likely related to #6666 
Is that the only build that had the issue?

**Comment by masterleinad** [comment] 2023-12-14 14:27
> Likely related to #6666

Looks like the `jenkins` CI didn't run on that one since `lascaux04` was selected to run `clang-format`. I think we should really do #6651.

**Comment by ndellingwood** [comment] 2023-12-14 15:46
> Is that the only build that had the issue?

@dalg24 it failed in the build above, as well as the non-debug version of the build above

**Comment by ajpowelsnl** [comment] 2023-12-20 19:42
Please have a look OpenMP specialist ; P

**Comment by dalg24** [comment] 2023-12-21 15:43
> > Likely related to #6666
> 
> Looks like the `jenkins` CI didn't run on that one since `lascaux04` was selected to run `clang-format`. I think we should really do #6651.

How is it related.  Are you saying that the OpenMP builds are broken on Jenkins and we did not notice?

**Comment by masterleinad** [comment] 2023-12-21 15:49
> How is it related. Are you saying that the OpenMP builds are broken on Jenkins and we did not notice?

No, I only meant to say that we didn't test the pull request using some configurations that have been problematic in the past. I haven't yet seen any jenkins build that would reproduce the issue.

**Comment by rgayatri23** [comment] 2023-12-21 20:04
I tested the issue described with as low as cuda/11.5 and on Ampere80,Zen3 (these are the only configs available to me that come close to match the versions and architecture described) with the current `develop` branch. I was unable to reproduce the issue. 
I tried a few combinations for example, changing the build types and backends (with and without cuda) and in each case `partitioning_by_args` passes. 
Is there any particular build option that is necessary to reproduce the issue?

**Comment by ndellingwood** [comment] 2023-12-21 20:28
@rgayatri23 I think the guess is that this may be specific to older versions of gcc that we still support, e.g. gcc/8.3.0, as opposed to newer versions of gcc. The only failure occurrence I have seen is with gcc/8.3.0

**Comment by rgayatri23** [comment] 2023-12-21 21:14
Thanks @ndellingwood - That was right. I could reproduce the issue with gcc/10.3.0 too.
And as mentioned above it seems that the issue appeared when we merged #6666 . Maybe a missing implementation for `omp_get_max_active_levels` in older gcc versions.
I will make a PR to fix this issue.

**Comment by ndellingwood** [comment] 2023-12-21 21:58
Thanks for the update @rgayatri23 !

**Comment by rgayatri23** [comment] 2024-01-02 06:11
I think we can close this issue since the fix for the issue is already merged.

**Closed** 2024-01-02 16:32 UTC
Labels: Failure - Nightly
