### ISSUE TITLE
Kokkos macros and old macros

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#787] opened 2017-05-10 20:55 UTC
There are lots of warnings when you compile kokkos under nvcc about stuff like

/home/mbetten/installs/install-for-panzer/cuda-RELEASE/include/Kokkos_Macros.hpp:143:0: warning: "KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA" redefined

So, my question is why does kokkos_macros.hpp include the oldmacros file before it defines a lot of these things??

Example
Kokkos macros defines
    #define KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA 1

however oldmacros has this code
```
#ifdef KOKKOS_HAVE_CXX11_DISPATCH_LAMBDA
#ifndef KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA
#define KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA KOKKOS_HAVE_CXX11_DISPATCH_LAMBDA
#endif
#endif

```

Can we somehow remove this?  or move the oldmacros include to the end?

It generates 30 lines per file, which hides real errors

**Comment by crtrott** [comment] 2017-05-11 16:35
I don't see those warnings on master, does something in Trilinos include some Kokkos Macro file explicitly (instead of including Kokkos_Core_fwd for example)?

**Comment by crtrott** [comment] 2017-05-11 16:36
And I don't see the issue with the code above. It will define KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA only if it is not previously defined. So even including that line of code multiple times shouldn't be an issue.

**Comment by dsunder** [comment] 2017-05-11 17:16
I just pushed a fix to Trilinos, moertel was directly including KokkosCore_config.h instead of Kokkos_Macros.hpp

Projects should include Kokkos_Macros.hpp instead of KokkosCore_config.h since it handles deprecated features and has appropriate compiler workarounds that KokkosCore_config.h is lacking.

**Closed by dsunder** 2017-05-11 17:16 UTC

**Comment by ibaned** [comment] 2017-05-11 17:22
We could add preprocessor code that causes a compile error when people do that. I certainly wasn't aware of that requirement. Here is the first example Google found:

https://github.com/felis/USB_Host_Shield_2.0/blob/master/avrpins.h#L21

**Comment by dsunder** [comment] 2017-05-11 17:32
The problem is that KokkosCore_config.h can be generated in many different ways.  Some users might directly create it, others will let the current build system create it, and others completely skip creating it.  This complexity comes from allowing Kokkos to be used by many different build systems
(Makefiles, Tribits, cmake, bjam, ...). 

Kokkos_Macros.hpp handles all the various ways that Kokkos could have been configured and creates a consistent system.  We did this to support backwards compatibility so that existing users are not broken when macros/features are deprecated, and so that we can apply complier/architecture specific fixes that have not made it into the various build systems.

**Comment by ibaned** [comment] 2017-05-11 18:34
I've made this change as PR #788
