### ISSUE TITLE
Provide runtime options

### ISSUE THREAD

**Issue by kmorel** [kokkos/kokkos#5843] opened 2023-02-02 01:17 UTC
It would be helpful to have an API that allows you to query the runtime options that Kokkos was initialized in. This would be helpful for debugging purposes and also to record these options in benchmarking code in a formatting that matches the rest of the logs.

**Comment by dalg24** [comment] 2023-02-02 03:05
Summarizing what initialization settings we currently support and describing the status quo

| Setting | Note |
| --- | --- |
| num_threads | see below |
| device_id | see below |
| map_device_id_by | useful? |
| disable_warnings | already provided `Kokkos::show_warnings() -> bool` |
| print_configuration | not convinced it would be useful |
| tune_internals | already provided `Kokkos::tune_internals() -> bool` |
| tools_libs | useful? |
| tools_help | not convinced it would be useful |
| tools_args | not convinced it would be useful |

* num_threads
  Currently, one would have to do `Kokkos::DefaultHostExecutionSpace().concurrency()`
* device_id
  No portable solution
  * CUDA: `Kokkos::DefaultExecutionSpace().cuda_device()`
  * HIP: `Kokkos::DefaultExecutionSpace().hip_device()`
  * SYCL: can't get the actual ID but there is `Kokkos::DefaultExecutionSpace().sycl_queue().get_device()`
  * OpenMPTarget: functionality missing at the moment (we should add it)
     In the meantime I suppose could do `omp_get_default_device()`
  * OpenACC: `Kokkos::DefaultExecutionSpace().acc_device_number()`
  * Serial, Threads, OpenMP, HPX: N/A

**Comment by dalg24** [comment] 2023-02-02 23:29
How does #5853 sound?

**Comment by dalg24** [comment] 2023-02-03 14:33
> How does #5853 sound? Doc [here](https://github.com/kokkos/kokkos-core-wiki/pull/291/files#diff-5c6293825b06d5bca21aa4e3e0369a0af52c949d1283ddf5bf7c5bb927d90324)

Does not address the issue.  See https://github.com/kokkos/kokkos/pull/5853#discussion_r1095851548

**Comment by crtrott** [comment] 2023-02-03 16:35
So what you want is a "what initialization settings would I need to provide to reproduce this run with explicit settings?"

**Comment by kmorel** [comment] 2023-02-03 17:48
That's a fair way of looking at it.

**Comment by dalg24** [comment] 2023-02-03 18:06
I just remembered we actually have some test where we check our initialization does the right thing
https://github.com/kokkos/kokkos/blob/e7aeb9bb3f0e7db1b2a3128bc7d701d4b5b61fae/core/unit_test/UnitTest_DeviceAndThreads.cpp#L40-L66
https://github.com/kokkos/kokkos/blob/e7aeb9bb3f0e7db1b2a3128bc7d701d4b5b61fae/core/unit_test/TestDeviceAndThreads.py#L40-L62
Just adding for reference.

**Comment by dalg24** [comment] 2023-04-05 19:17
@kmorel does #5855 meet your needs?

**Comment by kmorel** [comment] 2023-04-05 20:28
This looks good.

Maybe this is a dumb question, but what happens with, for example, `device_id` if Kokkos is compiled for multiple devices. For example, what if I compile Kokkos with support for both CUDA and HIP (I think this is possible), and I am running on a computer with an AMD device? Will I get the wrong answer because `device_id` checks CUDA instead of HIP? What if I am on a computer that actually has both devices?

**Comment by masterleinad** [comment] 2023-04-05 20:39
Kokkos can only be configured with one GPU backend and only use one GPU per process.

**Comment by kmorel** [comment] 2023-04-05 20:53
In that case, it looks good to me.

**Comment by kmorel** [comment] 2023-04-11 13:04
Correct (or at least it does not address the problem we were having).

**Comment by dalg24** [comment] 2023-04-11 13:19
Can we close this issue as resolved since #5855 was merged (will be in release 4.1) or is something still missing?

**Comment by kmorel** [comment] 2023-04-11 17:48
It's fine with me to close this issue.

**Closed** 2023-04-11 18:19 UTC
Labels: Feature Request
