### ISSUE TITLE
New View Implementation

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#135] opened 2015-11-23 17:51 UTC
The new view implementation has to be finished. Need Performance Test, Compile Time Test, and Compile Size Test and Correctness test with Trilinos, LAMMPS, Nalu.

**Comment by hcedwar** [comment] 2016-03-17 13:50
Implementation done and in master.  The remainder of this issue is now a duplicate of issue #138

**Closed by hcedwar** 2016-03-17 13:50 UTC
Labels: Feature Request, InDevelop
