### ISSUE TITLE
Scratch space for range policy ..

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#231] opened 2016-03-29 20:04 UTC
Currently team policy has scratch spaces for per team and per thread. Can we extend this to other parallel policies such as range policy (without team scratch in this case )?

**Comment by crtrott** [comment] 2016-03-29 20:18
You mean something like a generic per_iteration scratch or so?

**Comment by kyungjoo-kim** [comment] 2016-03-29 20:54
Yes, that might be the better name.

**Comment by dsunder** [comment] 2017-06-13 21:46
This is a duplicate of #428

**Closed by dsunder** 2017-06-13 21:46 UTC
Labels: Feature Request
