### ISSUE TITLE
Kokkos on Summit

### ISSUE THREAD

**Issue by ascheinb** [kokkos/kokkos#1985] opened 2019-02-11 22:03 UTC
I just tried running the Kokkos Hello World after building Kokkos on Summit. I tried out building kokkos and compiling the example with two different compilers: g++ and pgc++ (separately). In both cases, I get this output:
```
Hello World on Kokkos execution space N6Kokkos4CudaE
Hello from i = 0
...
Hello from i = 14
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, ./hello_world: undefined symbol: __PAMI_Invalidate_region
Kokkos::Cuda ERROR: Failed to call Kokkos::Cuda::finalize()

```
So it fails somewhere between the end of the parallel_for and the beginning of the finalize. I compile with:
```
~/kokkos/bin/nvcc_wrapper -fopenmp -O3 -std=c++11 --expt-extended-lambda -I~/kokkos/install/include --relocatable-device-code=true -arch=sm_70  -L~/kokkos/install/lib -lkokkos hello_world.o
```
Has Kokkos been used successfully on Summit yet? Anyone else run into this problem?

I also get these warnings repeatedly during compilation with g++:
```
~/kokkos/install/include/Kokkos_Crs.hpp(106): warning: __device__ annotation is ignored on a function("Crs") that is explicitly defaulted on its first declaration
~/kokkos/install/include/Kokkos_Crs.hpp(106): warning: __host__ annotation is ignored on a function("Crs") that is explicitly defaulted on its first declaration
```
With my pgc++ build, these warnings do not appear; so it is probably unrelated to the runtime error described above.

Thanks!

**Comment by nmhamster** [comment] 2019-02-11 22:10
@ascheinb - what are you using to link your tests? The PAMI error usually relates to low level transport for the network. Could it be you have wrappers in place here for MPI-based compilation?

**Comment by ascheinb** [comment] 2019-02-11 22:13
Thanks for the reply! I'm not sure - where can I check this? What link are you referring to?

**Comment by nmhamster** [comment] 2019-02-11 22:14
@ascheinb - can you copy your configure link (compilers etc) into a comment here so we can look at it?

**Comment by ascheinb** [comment] 2019-02-11 22:18
I've configured Kokkos with this:
```
export KOKKOS_SRC_DIR=~/kokkos
export KOKKOS_INSTALL_DIR=$KOKKOS_SRC_DIR/install
export NVCC_WRAPPER_DEFAULT_COMPILER=/usr/bin/g++
# Above is for g++ version; below is the pgc++ version.
#export NVCC_WRAPPER_DEFAULT_COMPILER=/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/pgi-18.10-w2qkfaill2olnyrfykr5a3kmwaz6pjur/linuxpower/18.10/bin/pgc++


../generate_makefile.bash \
  --prefix=$KOKKOS_INSTALL_DIR \
  --with-cuda --with-openmp --with-serial \
  --compiler=$KOKKOS_SRC_DIR/bin/nvcc_wrapper \
  --cxxflags="-arch=sm_70" \
  --with-cuda-options=enable_lambda
```

Is that what you're asking for?

**Comment by ascheinb** [comment] 2019-02-11 22:28
Here's my jobscript as well, in case it's part of the problem. For simplicity I just use one node, one resource set, one core, one gpu:
```
#!/bin/bash
# Begin LSF Directives
#BSUB -P PHY122
#BSUB -W 1:00
#BSUB -nnodes 1
#BSUB -J test
#BSUB -o test.%J
#BSUB -e test.%J

cd $MEMBERWORK/csc190
date
jsrun -n 1 -r 1 -a 1 -g 1 ./hello_world
```

**Comment by crtrott** [comment] 2019-02-12 00:00
This is weird. I mean the code obviously ran kernels (the hello stuff). The final error is because it then aborted before getting through all of the Kokkos finalize, and thus the singleton for the Cuda execution space upon its destruction complains. The find symbol error after the program already ran, also means that it must be trying to dynamically load something. Kokkos itself doesn't do it at that point. All its potential dynamic library open calls happen during initialize.

**Comment by nmhamster** [comment] 2019-02-12 00:05
I think its trying to deregister memory for the MPI library (PAMI is IBM's transport layer).

**Comment by crtrott** [comment] 2019-02-12 00:18
How did you compile the Kokkos library itself?

**Comment by ascheinb** [comment] 2019-02-12 00:27
I generated the makefile as described above, then did make install. It compiled without any problem. For the g++ version I only loaded one additional module - cuda/9.2.148. For the pgc++ install, I also used pgi/18.10.

**Comment by crtrott** [comment] 2019-02-12 00:30
Ah right. This looks all ok. You are the first to report this issue. I asked on the slack channel to see if someone else with Summit access can reproduce it. We have similar machines with IBM Power9 and NVIDIA Voltas but are running slightly different software stacks.

**Comment by ascheinb** [comment] 2019-02-12 00:37
Great, thanks!

**Comment by mhoemmen** [comment] 2019-02-12 01:04
@crtrott If you can't find anyone else to work on this, let me know.

**Comment by pgrete** [comment] 2019-02-12 01:25
I can confirm that behaviour, i.e., I also see 
```
...
Hello from i = 13
Hello from i = 14
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, ./01_hello_world.cuda: undefined symbol: __PAMI_Invalidate_region
Kokkos::Cuda ERROR: Failed to call Kokkos::Cuda::finalize()
```
after compiling the example hello world.

However, I can also confirm that Kokkos works on Summit (we have an MPI application that works for both Cuda and OpenMP Kokkos devices).

I also suspect that it's somewhat interconnect related (which technically should not be used but there may be some unknown defaults that just assume that you'd not run non-MPI single GPU processes).

Otherwise, I noticed that you set `export NVCC_WRAPPER_DEFAULT_COMPILER=/usr/bin/g++`.
I suggest to just set it to `g++` so that it actually uses the g++ that is loaded via the module environment (which could be different from the OS default version).

**Comment by crtrott** [comment] 2019-02-12 03:11
Hm ok. You could try adding MPI_Init and MPI_Finalize to the little example and compile with OpenMPI (export OMPI_CXX=$(HOME)/kokkos/bin/nvcc_wrapper) and use mpicxx as your compiler.

**Comment by nmhamster** [comment] 2019-02-12 03:20
Can you just try adding `-lpami` to your link line? The function you are missing can be found in:

```
$ nm ./spectrum_mpi/lib/pami_433/libpami.so | grep __PAMI_Invalidate_region
00000000000bed40 T __PAMI_Invalidate_region
```

**Comment by nmhamster** [comment] 2019-02-12 03:45
@ascheinb / @pgrete - we can recreate this issue only when running using `jsrun` on our local CORAL system clone. I think it comes down to jsrun using some kind of library preloading to insert a hook in the running application to clean up memory. 

So, my quick fix is the following. Add this to your `jsrun` command:

`jsrun -E LD_PRELOAD=/opt/ibm/spectrum_mpi/lib/pami_433/libpami.so .. put rest of normal stuff here`

This seems to run successfully on our machine and not induce the error.

**Comment by ascheinb** [comment] 2019-02-12 14:22
Thanks all. Adding the preload to jsrun solved the problem, but is hopefully not the long term solution. Adding -lpami to the link line was not recognized. I will try now to compile Kokkos with mpicc and let you know how that goes.

**Comment by nmhamster** [comment] 2019-02-12 15:06
@ascheinb - issue reported to IBM last night. Hopefully this is easily fixed.

**Comment by ascheinb** [comment] 2019-02-12 15:08
Thanks!

I just tried adding an mpi_init/mpi_finalize (after rebuilding Kokkos with the PGI mpiCC wrapper), but the PAMI error appeared as before. I've also tried with multiple resource sets (jsrun -n 2 -r 2 -a 1 -g 1 ./hello_world) and still get the error. As before, the preload flag resolves it.

 @pgrete  Could I get an example of a functioning code on summit?

**Comment by sslattery** [comment] 2019-02-12 15:10
Thanks for taking a look at this guys

**Comment by pgrete** [comment] 2019-02-12 15:27
@ascheinb are you looking for a hello world type of example or a fully featured code?

For me the hello world example didn't show the errors any more when including MPI init/finalize and compiling with mpicxx.

**Comment by ascheinb** [comment] 2019-02-12 15:47
@pgrete That's strange. I just tried the same thing and still get the error. Are you using the default environment or a different one?

**Comment by ascheinb** [comment] 2019-02-12 15:52
The default when I log in appears to be XL, oddly enough: `which mpicxx`
`/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-1/spectrum-mpi-10.2.0.10-20181214-y75ruim4h6cvqcdymmcnb6mllodtyfuz/bin/mpicxx`

Is that what you used?

**Comment by pgrete** [comment] 2019-02-12 15:56
I'm using gcc/6.4.0, i.e., I change the environment by `module swap xl gcc/6.4.0`
Also you can check which compiler is actually called by the mpi wrapper with
```
[pgrete@login5.summit 01_hello_world]$ mpicxx --showme
/ccs/home/pgrete/src/summit/kokkos/example/tutorial/01_hello_world/../../../bin/nvcc_wrapper -I/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.2.0.10-20181214-o4r7cptz5i4og4c5x6ngsacosjqeo6l7/include -L/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.2.0.10-20181214-o4r7cptz5i4og4c5x6ngsacosjqeo6l7/lib -lmpiprofilesupport -lmpi_ibm
```

**Comment by ascheinb** [comment] 2019-02-12 16:14
Strangely do that module swap created a new problem altogether when compiling the example.
```
/ccs/home/scheinberg/mpicc_summit/kokkos/bin/nvcc_wrapper -fopenmp -pedantic -O3 -std=c++11 --expt-extended-lambda -I/ccs/home/scheinberg/mpicc_summit/kokkos/install/include --relocatable-device-code=true -arch=sm_70  -L/ccs/home/scheinberg/mpicc_summit/kokkos/install/lib -lkokkos Kokkos_world.o
Kokkos_world.o: In function `void Kokkos::parallel_for<hello_world>(unsigned long, hello_world const&, std::string const&)':
tmpxft_0001fe05_00000000-5_Kokkos_world.cudafe1.cpp:(.text._ZN6Kokkos12parallel_forI11hello_worldEEvmRKT_RKSs[_ZN6Kokkos12parallel_forI11hello_worldEEvmRKT_RKSs]+0x8c): undefined reference to `Kokkos::Profiling::beginParallelFor(std::string const&, unsigned int, unsigned long*)'
/usr/bin/ld: link errors found, deleting executable `a.out'
```
I guess the best thing to do for me is to use the quick fix and wait to hear if it's resolved.

**Comment by crtrott** [comment] 2019-02-12 16:32
Did you delete every object file etc. before rebuilding with the different modules? That could be the cause of your link issue.

**Comment by ascheinb** [comment] 2019-02-12 16:50
@crtrott I was about to say "Of course I did!" but it turns out no... I did not. :( Adding in mpi_init and mpi_finalize resolves the error - using PGI as well. Thanks all!

**Comment by crtrott** [comment] 2019-02-12 16:59
@ascheinb No problem, it happens to all of us ;-)

**Comment by crtrott** [comment] 2019-02-12 17:10
Gonna close this issue now, since it is basically resolved as far as Kokkos goes (i.e. its not really a Kokkos issue but some weird special stuff IBM does on their Power9/Volta systems).

**Closed** 2019-02-12 17:10 UTC
Labels: help wanted, question

**Comment by dalg24** [comment] 2019-02-14 05:05
> @crtrott I was about to say "Of course I did!" but it turns out no... I did not. :( Adding in mpi_init and mpi_finalize resolves the error - using PGI as well. Thanks all!

Ran into the exact same issue in the past.  Initializing MPI is one way of resolving the issue.
For the record, here is a less painful alternative: pass `--smpiargs="-disable_gpu_hooks"` or `--smpiargs=“off”` to `jsrun`.  Either will do the trick.

**Comment by hjjvandam** [comment] 2019-10-29 14:27
I am seeing the same issue in a completely different context (LibXC) when I use cudaMallocHost. Replacing this with cudaMalloc resolved the issue for me.
