### ISSUE TITLE
deep_copy slower since May merge of Kokkos into Trilinos

### ISSUE THREAD

**Issue by kddevin** [kokkos/kokkos#1710] opened 2018-07-25 18:58 UTC
Do you expect that the performance of deep_copy would have degraded between March and May?  I am seeing slower performance from deep_copy since the May merging of Kokkos into Trilinos.

In the attached test, I copy LayoutLeft 2D arrays into compatible LayoutRight 2D arrays, and then back again.  Here are the times using Trilinos from March 2018:  

TimeMonitor results over 16 processors
Timer Name            MinOverProcs    MeanOverProcs    MaxOverProcs  
COPY LEFT TO RIGHT    6.026        6.141        6.261      
COPY RIGHT TO LEFT    6.219       6.362         6.496     

And here are times using Trilinos from May 2018; the current version of Trilinos produces the same performance:  

TimeMonitor results over 16 processors
Timer Name            MinOverProcs    MeanOverProcs    MaxOverProcs    
COPY LEFT TO RIGHT    4.907       5.317         5.543  
COPY RIGHT TO LEFT    19.22       19.53         19.88     

The left-to-right times are consistently a bit shorter in the May version, but the right-to-left times are consistently much much longer in the May version.

Why do I care?  In my application, I use Tpetra::MultiVector, which currently requires LayoutLeft.  But my computation is faster with LayoutRight.  In fact, it had been faster to copy the LayoutLeft view of the MultiVector data to LayoutRight, do the computation and copy the results back to the MultiVector than to do the computation using the MultiVector's LayoutLeft view.  With the slower copies, though, that advantage shrinks.

If I am misusing Kokkos or there is an easier way to achieve the LayoutRight performance, please let me know.  Thanks!

Attached are my test program, the test output, and my Trilinos configuration script.  Tests were run on skybridge using the Intel 16.0.2 compiler.
[copy.cpp.txt](https://github.com/kokkos/kokkos/files/2229171/copy.cpp.txt)
[output.txt](https://github.com/kokkos/kokkos/files/2229174/output.txt)
[build.txt](https://github.com/kokkos/kokkos/files/2229175/build.txt)

**Comment by mhoemmen** [comment] 2018-07-25 19:51
@kddevin What happens if you set `KOKKOS_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON`?  I'm curious if Kokkos' optimizations for Kokkos::deep_copy are giving the compiler more code, and thus reducing its ability to optimize.  Kokkos' ETI for ViewCopy and ViewFill may help with that, but it also may increase build time a lot.  I've been looking at this issue for SPARC.

**Comment by ibaned** [comment] 2018-07-26 12:58
Hi @kddevin, I just built and ran this program with Kokkos by itself from March and May, and didn't see a big difference in runtimes. I tried ETI on and off, and still got the same runtimes. I guess I could try on Skybridge with your compiler...

Here is my modified code:
```cpp
// Test timing of copy from LayoutLeft to LayoutRight and back again.
// Copies 2D arrays ("multivectors") of varying lengths.
// Runtime increased from March to May.

#include "Kokkos_Core.hpp"
#include <vector>
#include <chrono>

struct Now {
  typedef std::chrono::time_point<std::chrono::high_resolution_clock> Impl;
  Impl impl;
};

Now now() {
  Now t;
  t.impl = std::chrono::high_resolution_clock::now();
  return t;
}

double operator-(Now b, Now a) {
  return std::chrono::duration_cast<std::chrono::nanoseconds>(b.impl - a.impl)
             .count() *
         1e-9;
}

int main(int narg, char **arg)
{
//Kokkos::ScopeGuard kokkos(narg, arg);
  Kokkos::initialize(narg, arg); {

  const int nIters = 100;
  const int nViews = 3;
  const int nJ = 10;
  
  typedef Kokkos::View<double **, Kokkos::LayoutLeft> layoutLeft_t;
  typedef Kokkos::View<double **, Kokkos::LayoutRight> layoutRight_t;

  // Initialize LayoutLeft vectors
  std::cout << "Initializing LayoutLeft multivectors" << std::endl;

  std::vector<layoutLeft_t> left;
  left.reserve(nViews);

  for (int m = 0; m < nViews; m++) {
    char name[10];
    int nids = pow(100, (m+1));
    sprintf(name, "left%d", m);
    left.push_back(layoutLeft_t(name, nids, nJ));
    std::cout << name << " is " << nids << "x" << nJ << std::endl;
  }

  // Initialize LayoutRight vectors
  std::cout << "Allocating LayoutRight multivectors" << std::endl;

  std::vector<layoutRight_t> right;
  right.reserve(nViews);

  for (int m = 0; m < nViews; m++) {
    right.push_back(layoutRight_t("copym", left[m].extent(0),
                                           left[m].extent(1)));
  }

  std::cout << "Copying multivectors" << std::endl;

  double ltrt = 0;
  double rtlt = 0;
  for (int i = 0; i < nIters; i++) {

    // Copy from LayoutLeft to LayoutRight
    auto t0 = now();

    for (int m = 0; m < nViews; m++) {
      Kokkos::deep_copy(right[m], left[m]);
    }

    auto t1 = now();
    ltrt += (t1 - t0);

    // Copy from LayoutRight to LayoutLeft
    t0 = now();
    
    for (int m = 0; m < nViews; m++)
      Kokkos::deep_copy(left[m], right[m]);
   
    t1 = now();
    rtlt += (t1 - t0);
  }
  std::cout << "left to right time: " << ltrt << '\n';
  std::cout << "right to left time: " << rtlt << '\n';

  } Kokkos::finalize();
}
```
And the Makefile:
```make
KOKKOS_DEVICES=Serial
KOKKOS_OPTIONS=disable_deprecated_code,enable_eti
KOKKOS_CUDA_OPTIONS=enable_lambda
KOKKOS_ARCH = "HSW"


MAKEFILE_PATH := $(subst Makefile,,$(abspath $(lastword $(MAKEFILE_LIST))))

ifndef KOKKOS_PATH
  KOKKOS_PATH = $(MAKEFILE_PATH)../..
endif

SRC = $(wildcard $(MAKEFILE_PATH)*.cpp)
HEADERS = $(wildcard $(MAKEFILE_PATH)*.hpp)

vpath %.cpp $(sort $(dir $(SRC)))

default: build
	echo "Start Build"

LINKFLAGS =
ifneq (,$(findstring Cuda,$(KOKKOS_DEVICES)))
CXX = ${KOKKOS_PATH}/bin/nvcc_wrapper
EXE = copy.cuda
override LINKFLAGS += --remove-duplicate-link-files
else
CXX = g++
EXE = copy.host
endif

CXXFLAGS ?= -O3 -g
override CXXFLAGS += -I$(MAKEFILE_PATH)

DEPFLAGS = -M
LINK = ${CXX}

OBJ = $(notdir $(SRC:.cpp=.o))
LIB =

include $(KOKKOS_PATH)/Makefile.kokkos

build: $(EXE)

$(EXE): $(OBJ) $(KOKKOS_LINK_DEPENDS)
	$(LINK) $(KOKKOS_LDFLAGS) $(LINKFLAGS) $(EXTRA_PATH) $(OBJ) $(KOKKOS_LIBS) $(LIB) -o $(EXE)

clean: kokkos-clean
	rm -f *.o *.cuda *.host

# Compilation rules

%.o:%.cpp $(KOKKOS_CPP_DEPENDS) $(HEADERS)
	$(CXX) $(KOKKOS_CPPFLAGS) $(KOKKOS_CXXFLAGS) $(CXXFLAGS) $(EXTRA_INC) -c $< -o $(notdir $@)
```
In all cases on my machine it takes about 2.5 seconds for right to left and 6.6 seconds for left to right.

**Comment by ibaned** [comment] 2018-07-26 13:08
Just ran on the Skybridge login node, similar times:
```
left to right time: 3.17503
right to left time: 7.00712
```

**Comment by ibaned** [comment] 2018-07-26 13:14
Tried with what I think should be the same compiler flags (`-O2 -g -fopenmp`):
```
left to right time: 2.66129
right to left time: 6.80192
```

**Comment by ibaned** [comment] 2018-07-26 13:17
While I keep trying this, stepping back, @mhoemmen it seems strange to me that `Tpetra::MultiVector` is `LayoutLeft`... does that mean that entries from each sub-vector are interleaved?

**Comment by ibaned** [comment] 2018-07-26 13:18
Turning deprecated code on and ETI on:
```
left to right time: 2.76219
right to left time: 6.87533
```
I guess I'll have to try the full Trilinos configuration....

**Comment by mhoemmen** [comment] 2018-07-26 15:43
@ibaned wrote:
> @mhoemmen it seems strange to me that `Tpetra::MultiVector` is `LayoutLeft`... does that mean that entries from each sub-vector are interleaved?

No -- each column of a MultiVector is a separate Vector.  Vectors always have stride 1.

`LayoutRight` would make more sense for block (in the sense of "multiple right-hand sides at a time") Krylov methods, but it would also break `{Anasazi, Belos}::MultiVecTraits`.  (Look carefully at the "view a subset of columns" methods to see why.  One fix would be for Anasazi and Belos to have a "basis of blocks" concept, separate from its block / multivector concept.)

**Comment by ibaned** [comment] 2018-07-26 17:03
Ah, okay, I was just hoping that Vectors were contiguous, and thats the case so thats good.

**Comment by kddevin** [comment] 2018-07-26 18:00
Following Mark's suggestion, I tried builds with KOKKOS_ENABLE_EXPLICIT_INSTANTIATION=ON in the May version of Trilinos.  The times did not change; the May version times are the same with and without KOKKOS_ENABLE_EXPLICIT_INSTANTIATION.  
The May version is slower than the March version.

**Comment by kddevin** [comment] 2018-07-26 18:04
Next I can try running Dan's code using my installations of Kokkos via Trilinos.  skybridge is down now, though.  Stay tuned.

**Comment by kddevin** [comment] 2018-07-27 03:52
I must be doing something different from Dan in my builds.  Running his code with my current, May and March repos, I see times similar to the Teuchos times reported by my test program:

Current Trilinos repo
left to right time: 5.16379
right to left time: 19.1331

May repo 
left to right time: 5.01375
right to left time: 19.2906

March repo
left to right time: 6.00036
right to left time: 5.98682

**Comment by mhoemmen** [comment] 2018-07-27 23:20
@kddevin Thanks for the results! :-D  We SPARC folks were thinking of working around by rolling our own `deep_copy`.  I'm not happy about that but hopefully we can feed that back into Kokkos.

**Comment by bathmatt** [comment] 2018-08-23 20:30
yes, develop;

example, it takes 100ms to deep copy a few hundred ints.  

simple parallel_for 0.04ms

so I did the math wrong, it was only 3000x slower.  

I reported this to kokkos-developers but then heard about this issue and thought I'd bring it up here..

@kyungjoo-kim I believe is trying to duplicate this

**Comment by kyungjoo-kim** [comment] 2018-08-23 20:58
@ibaned Not related to this issue but responding to @bathmatt comment, I am just trying to find which actually cause this problem. 

- As @kddevin find this performance issue a month ago without CUDA 9.2, I think that deep copy (following the call stack and her use case is changing layout which invokes view remapping) itself has a problem. The main change in Kokkos promotion is ETI of deep_copy (more precisely ViewCopy and ViewFill). The differnce between left->right and right->left might be due to implementation difference, which should not be different thought.

- @bathmatt also reported that Kokkos::deep_copy(some_1d_view, 0) gets slow down too. This performance issue is not a layout specific issue. Maybe we can blame it more ETI. Do we have a knob to select Kokkos ETI separately from Trilinos ETI ? 

- As @bathmatt shows serious performance drop on GPUs, I am trying to reproduce the problem under CUDA 9.2 (compiling on white is very slow). Then, I will report more detailed profiling (probably in a separate issue)

**Comment by ibaned** [comment] 2018-08-23 21:04
@kyungjoo-kim I think this issue is the right place to post detailed profiling results if you get them, thanks!

**Comment by ibaned** [comment] 2018-08-23 21:05
Also yes, the knob is `-DKOKKOS_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF`

**Comment by bathmatt** [comment] 2018-08-23 21:27
I also believe this is only on the pascal cards.  EMPIRE is dog slow on pascal, but faster on the k80s 
Probably the sm_60 stuff

**Comment by ndellingwood** [comment] 2018-08-23 23:46
Talked to @kyungjoo-kim and as a sanity check tested a build on ride on the Pascal GPU queue with cuda/9.2 + gcc/7.2 with cuda and openmp backends enabled and uvm, build completed and all tests passed.

**Comment by bathmatt** [comment] 2018-08-24 13:44
So, here is a quick difference, same configure of trilinos, only difference is KokkosArch set to pascal (60) vs K86 (37), I see

Pascal
50/74 Test #50: CircularlyPolarized3D .......................   Passed  19104.30 sec
K80
50/74 Test #50: CircularlyPolarized3D .......................   Passed  336.90 sec

From nvvp it looks like memory is thrashing on the pascal card...  Just FWIW, this is 30s on openmp.  

@rppawlo thought you'd like to see this...

**Comment by rppawlo** [comment] 2018-08-24 14:01
yes - that is exactly what I am seeing for pascal. Thanks for verifying @bathmatt !

**Comment by bathmatt** [comment] 2018-08-24 14:38
submitted a ride issue, not sure where the problem is, @crtrott is there any pascal60 specific optimizations in kokkos?  Maybe that kill UVM performance or the such?

**Comment by rppawlo** [comment] 2018-08-24 15:16
I can verify that I built for Pascal60 and used the pascal que. Got the same results as Matt - 19K seconds. Used the Trilinos atdm build but modified the environment.sh to force Pascal60. Verified in configure output.

**Comment by bathmatt** [comment] 2018-08-24 17:13
Yes, the run with the sm_37 code on the P100 card hung, and obviously the sm_60 wouldn't run on the k80 card..

**Comment by kyungjoo-kim** [comment] 2018-08-28 00:06
I wrote a simple code to compare deep copy on gpus with uvm on and I only use kokkos (no mpi). This is tested on white P100 cuda 9.2 
```
 N = 10000 Chunksize = 262144 MaxSize = 33554432 Niter = 1 
Time cudamemcpy between views = 4.2686e-05 sec 
Time Kokkos copy assign between views = 4.2103e-05 sec 
Time Kokkos deepcopy between views = 5.0586e-05 sec 
Time Thrust deepcopy between views = 3.5857e-05 sec 
Time Kokkos copy assign between dynamic views = 4.4457e-05 sec 
Time Kokkos deepcopy from view to dynamic view = 0.1568 sec 
Time Kokkos chunkwise deepcopy from view to dynamic view = 7.3193e-05 sec 
```
Sometimes I see this big timing difference when a view is copied to deep copy as observed by @bathmatt and @rppawlo . In this small test, this happens occasionally but this may happen consistently in big code. 

Testing with nvprof, it shows...
```
CPU, Tesla P100         -         -           64.000000KB   0x3effc0200000  [Unified Memory page thrash]        
-         PC 0x10033a84   0x3effc0200000  [Unified Memory CPU page faults]    
-         PC 0x10033a84   0x3effc0200000  [Unified Memory CPU page faults]    
-         PC 0x10033a84   0x3effc0200000  [Unified Memory CPU page faults]    
-         PC 0x10033a84   0x3effc0200000  [Unified Memory CPU page faults]    
-         PC 0x10033a84   0x3effc0200000  [Unified Memory CPU page faults]    
.... a lot more page faults.
```
In my test code, I never access gpu memory from host. I guess that this might be cuda 9.2 issue on pascal. @crtrott will cross-examine this (probably tmrw).

**Comment by ibaned** [comment] 2018-08-30 17:49
So I think this issue has accumulated what are really three separate issues:
1. @kddevin 's left-to-right case
2. @bathmatt 's "100 integers" case
3. @kyungjoo-kim 's "view to dynamic view" case

I'm going to focus on the first one since it was the original post. Some experiments seem to confirm @kyungjoo-kim 's analysis that for this use case the `MDRangePolicy` iteration layout isn't the best choice:
```
running Karen Devine's layout-change issue:
running on HOST
Initializing LayoutLeft multivectors
left0 is 100x10
left1 is 10000x10
left2 is 1000000x10
Allocating LayoutRight multivectors
Copying multivectors
left to right time: 0.229788
right to left time: 0.486619
left to right time via lambda left/left: 0.538845
right to left time via lambda left/left: 0.584492
left to right time via lambda right/right: 0.520127
right to left time via lambda right/right: 0.521139
left to right time via functor left/left: 0.412934
right to left time via functor left/left: 0.460558
left to right time via functor right/right: 0.195319
right to left time via functor right/right: 0.212509
running on DEVICE
Initializing LayoutLeft multivectors
left0 is 100x10
left1 is 10000x10
left2 is 1000000x10
Allocating LayoutRight multivectors
Copying multivectors
left to right time: 0.0407646
right to left time: 0.0325944
left to right time via lambda left/left: 0.0361792
right to left time via lambda left/left: 0.0319637
left to right time via lambda right/right: 0.0396291
right to left time via lambda right/right: 0.039045
left to right time via functor left/left: 0.0349714
right to left time via functor left/left: 0.0310257
left to right time via functor right/right: 0.0358355
right to left time via functor right/right: 0.0355044
running Karen Devine's layout-change issue with dimensions flipped:
running on HOST
Initializing LayoutLeft multivectors
left0 is 100x10
left1 is 10000x10
left2 is 1000000x10
Allocating LayoutRight multivectors
Copying multivectors
left to right time: 0.478515
right to left time: 0.24695
left to right time via lambda left/left: 0.53024
right to left time via lambda left/left: 0.518828
left to right time via lambda right/right: 0.580448
right to left time via lambda right/right: 0.546656
left to right time via functor left/left: 0.213385
right to left time via functor left/left: 0.22454
left to right time via functor right/right: 0.446052
right to left time via functor right/right: 0.412903
running on DEVICE
Initializing LayoutLeft multivectors
left0 is 100x10
left1 is 10000x10
left2 is 1000000x10
Allocating LayoutRight multivectors
Copying multivectors
left to right time: 0.0320034
right to left time: 0.0406709
left to right time via lambda left/left: 0.0398909
right to left time via lambda left/left: 0.040464
left to right time via lambda right/right: 0.0317773
right to left time via lambda right/right: 0.0313039
left to right time via functor left/left: 0.035985
right to left time via functor left/left: 0.0363703
left to right time via functor right/right: 0.0295375
right to left time via functor right/right: 0.0291624
```
I have a simple change that gets optimal performance for this use case, but @crtrott is concerned about differently-shaped views in the general case so I'll re-run these tests using different shapes.

**Comment by kyungjoo-kim** [comment] 2018-08-30 17:57
@ibaned I think that item 2 and 3 are same and @bathmatt  almost always use 1D dynamic views in his particle data structure. Anyway, if the slowness happens in the conventional views, we cannot fix the problem as it invokes cuda memcpy.

**Comment by ibaned** [comment] 2019-09-04 18:16
I undertook a large effort to choose the iteration style that is optimal in either case of the 2D layout conversion use case, and the resulting code was sufficiently complex that we decided not to add it. Now that `deep_copy` is based on `MDRangePolicy`, the fundamental difficulty is raised because one has to develop an optimal algorithm for all possible ranks. At the moment, I think @crtrott prefers the conceptual convenience of using `MDRangePolicy`, so it is unclear how this can be resolved in the foreseeable future.

**Comment by ibaned** [comment] 2019-09-04 18:17
If this is strongly impacting the performance of your application, please open a separate issue with your specific use case and we'll try to optimize for that.

**Closed by ibaned** 2019-09-04 18:17 UTC
Labels: wontfix
