### ISSUE TITLE
Trilinos nightly failure, OpenMP backend: simpleBuildAgainstTrilinos app builds against install fails with "Target "MyApp" links to target "OpenMP::OpenMP_CXX" but the target was not   found."

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5514] opened 2022-10-03 22:17 UTC
**Describe the bug**
Attempting to build the demo "app" `simpleBuildAgainstTrilinos` from Trilinos with an OpenMP build, gcc/8.3.0 as compiler fail to configuration with output:
```
CMake Error at CMakeLists.txt:53 (add_executable):
  Target "MyApp" links to target "OpenMP::OpenMP_CXX" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

This does not occur with kokkos@3.7.00 snapshot into Trilinos, so I'm filing as a kokkos issue as this follows an apparent change in kokkos. 

**Please also include the following items to support reproducing the bug**
**Reproducer**:
trilinos/Trilinos@820615d4fa40f9fb72d27bd689b54797ea5ee7cb
kokkos/kokkos@2ce06b9754972818d8b023b5530732367ef28288
kokkos/kokkos-kernels@a438bcc72fb85fff36f32519c255960eee2bc804

```bash
# Repos
git clone -b develop kokkos
git clone -b develop kokkos-kernels
# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override
cd Trilinos
ln -s <path-to-your-repo>/kokkos kokkos
ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels

# Trilinos configure
cd $HOME
mkdir -p build
cd build

module purge
module load openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 openblas/0.3.18/gcc/8.3.1 cmake/3.21.2
export OMPI_CXX=`which g++`
export OMPI_CC=`which gcc`
export OMPI_FC=`which gfortran`

cmake \
 -D CMAKE_INSTALL_PREFIX="$PWD/install" \
 -D CMAKE_CXX_COMPILER=`which mpicxx` \
 -D CMAKE_CXX_FLAGS="-g" \
 -D CMAKE_C_COMPILER=`which mpicc` \
 -D CMAKE_C_FLAGS="-g" \
 -D CMAKE_Fortran_COMPILER=`which mpifort` \
 -D CMAKE_Fortran_FLAGS="-g" \
 -D CMAKE_BUILD_TYPE:STRING=RELEASE \
 -D CMAKE_CXX_STANDARD=17 \
 -D BUILD_SHARED_LIBS=OFF \
\
 -D TPL_ENABLE_CUDA:STRING=OFF \
 -D TPL_ENABLE_MPI:STRING=ON \
 -D MPI_BASE_DIR:PATH="$OPENMPI_ROOT" \
 -D MPI_BIN_DIR:PATH="$OPENMPI_BIN" \
 -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-map-by;socket:PE=4" \
\
-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
\
-D TPL_ENABLE_Boost=OFF \
   -D Boost_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D Boost_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_BoostLib=OFF \
   -D BoostLib_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D BoostLib_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_Netcdf=OFF \
\
 -D Trilinos_ENABLE_OpenMP=ON \
 -D Trilinos_ENABLE_COMPLEX=ON \
 -D Trilinos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_EXAMPLES=OFF \
\
 -D Trilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=ON \
  -D Kokkos_ENABLE_OPENMP=ON \
  -D Kokkos_ENABLE_CUDA=OFF \
  -D Kokkos_ENABLE_CUDA_LAMBDA=ON \
  -D Kokkos_ARCH_VOLTA70=ON \
  -D Kokkos_ARCH_POWER9=ON \
  -D Kokkos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_KokkosKernels=ON \
  -D KokkosKernels_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Tpetra=ON \
  -D Tpetra_ENABLE_CUDA=OFF \
  -D Tpetra_INST_SERIAL:BOOL=ON \
  -D Tpetra_INST_OPENMP:BOOL=ON \
  -D Tpetra_INST_PTHREAD:BOOL=OFF \
  -D Tpetra_INST_CUDA:BOOL=OFF \
  -D Tpetra_ENABLE_TESTS=OFF \
\
  -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
  -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
  -DKokkosKernels_ENABLE_SPARSE=ON \
  -DKokkosKernels_ENABLE_GRAPH=ON \
  -DKokkosKernels_ENABLE_BLAS=ON \
  -DKokkosKernels_ENABLE_BATCHED=ON \
$TRILINOS_DIR

# Install Trilinos
make -j20 install

# Create app directory and attempt to configure
mkdir AppInstallTest
cd AppInstallTest

cmake -DCMAKE_PREFIX_PATH=$PWD/../install $TRILINOS_DIR/demos/simpleBuildAgainstTrilinos
# Failure happens at the cmake configure step
```

**Comment by crtrott** [comment] 2022-10-05 04:56
https://github.com/kokkos/kokkos/pull/4105 is likely the issue ...

**Comment by ndellingwood** [comment] 2022-10-05 18:09
Link to Trilinos wiki page of the demo "app": https://github.com/trilinos/Trilinos/tree/develop/demos/simpleBuildAgainstTrilinos

**Comment by masterleinad** [comment] 2022-10-05 20:40
@ndellingwood What is the interaction between `Trilinos_ENABLE_OpenMP=ON` and `Kokkos_ENABLE_OPENMP`?
If the latter forces the former, we could just not do anything for `OpenMP` when configuring inside `Trilinos`. 
Otherwise, we need to hack https://github.com/kokkos/kokkos/blob/61d7db55fceac3318c987a291f77b844fd94c165/cmake/kokkos_install.cmake#L32-L44 to append something like
```
INCLUDE(CMakeFindDependencyMacro)
${KOKKOS_TPL_EXPORTS}")
```
where I'm not quite sure if we should have all of `KOKKOS_TPL_EXPORTS` or only append
```
INCLUDE(CMakeFindDependencyMacro)
FIND_DEPENDENCY(OpenMP REQUIRED)
```
in case `Kokkos` is configured with `OpenMP` support.

**Comment by ndellingwood** [comment] 2022-10-06 02:56
> What is the interaction between `Trilinos_ENABLE_OpenMP=ON` and `Kokkos_ENABLE_OPENMP`?

@masterleinad I think that  `Trilinos_ENABLE_OpenMP=ON` is supposed to trigger `Kokkos_ENABLE_OPENMP`, I will test configurations with Trilinos' develop branch to confirm

**Comment by masterleinad** [comment] 2022-10-06 20:32
Ah, we also need
```
6da@lap115343:~/Trilinos-dev/demos/simpleBuildAgainstTrilinos/build$ git diff
diff --git a/demos/simpleBuildAgainstTrilinos/CMakeLists.txt b/demos/simpleBuildAgainstTrilinos/CMakeLists.txt
index 990287789e6..7893b678082 100644
--- a/demos/simpleBuildAgainstTrilinos/CMakeLists.txt
+++ b/demos/simpleBuildAgainstTrilinos/CMakeLists.txt
@@ -7,13 +7,14 @@ cmake_minimum_required(VERSION 3.0)
 # You must do this before calling find_package(Trilinos) when
 # BUILD_SHARED_LIBS=ON or you get a lot of nasty warnings.
 #
-project(MyApp NONE)
+project(MyApp CXX)
 
 # Disable Kokkos warning about not supporting C++ extensions
 set(CMAKE_CXX_EXTENSIONS OFF)
 
 # Get Trilinos as one entity but require the packages being used
-find_package(Trilinos REQUIRED COMPONENTS Teuchos Tpetra)
+#find_package(Trilinos REQUIRED COMPONENTS Teuchos Tpetra Kokkos)
+find_package(Trilinos REQUIRED)
 
 # Echo trilinos build info just for fun
 MESSAGE("\nFound Trilinos!  Here are the details: ")
```
(either of the `find_package` calls work). Otherwise `KokkosCore.config` is not considered because of https://github.com/trilinos/Trilinos/blob/fef3ccfae5e6cc865aad5025d7d8f99740aa5aa8/cmake/tribits/core/installation/TribitsProjectConfigTemplate.cmake.in#L99-L136. At this point, I'm not quite sure how to proceed.
One option is to always include `Kokkos` if `Trilinos` was configure with it, another option would be to force `Trilinos_ENABLE_OPENMP` if `Kokkos_ENABLE_OPENMP`.

**Comment by masterleinad** [comment] 2022-10-06 20:33
Either way, this requires some changes in Trilinos itself.

**Comment by PhilMiller** [comment] 2022-10-06 21:06
It would probably be a good idea to get attention from @bartlettroscoe before we commit to a fix

**Comment by ndellingwood** [comment] 2022-10-06 21:36
Thanks @masterleinad for the investigation, will wait on response from @bartlettroscoe like @PhilMiller suggests for Trilinos-related changes. As far as the kokkos update in PR #5526 , should we move forward getting that reviewed and merged (independent of the Trilinos update)?

**Comment by bartlettroscoe** [comment] 2022-10-06 22:08
@ndellingwood, @PhilMiller, @masterleinad, @crtrott

My guess is that we may need to upgrade TriBITS and Trilinos to treat OpenMP as an external package/TPL and have it use `find_package(OpenMP)` (see [FindOpenMP.cmake](https://cmake.org/cmake/help/v3.22/module/FindOpenMP.html)) as described [here](https://tribitspub.github.io/TriBITS/users_guide/index.html#creating-findtpl-tplname-cmake-using-find-package) and then have Kokkos also use `find_package(OpenMP)`.  That will ensure that `find_package(OpenMP)` will get called both when building Trilinos and when downstream customer CMake projects pull in Trilinos with `find_package(Trilinos)` (or `find_package(<TrilinosPackage>)`). But it might be good to wait until we get the minimum CMake version upgraded to 3.22 in the next couple of weeks (see trilinos/Trilinos#10355) so we don't fight with a bad implementation of `FindOpenMP.cmake`.

This is all part of the natural pains of moving to consistent usage native CMake support for things that we used to have to do on our own (see https://github.com/TriBITSPub/TriBITS/issues/411).

**Comment by masterleinad** [comment] 2022-10-06 22:34
@bartlettroscoe The issue is coming from `Kokkos` using `find_package(OpenMP)` with `target_link_libraries(kokkoscore PUBLIC OpenMP::OpenMP_CXX)` already. I don't think we have time to wait for Trilinos to require CMake 3.22 to fix this issue. Also, TriBITS is using `find_package(OpenMP)` but not linking it AFAICT (https://github.com/trilinos/Trilinos/blob/7bacda8c8f8a3285c4ddbb0c7a85338e2ec09d4c/cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake#L1686-L1700) but it also doesn't really matter for a setup with `Trilinos_ENABLE_OpenMP=OFF` and `Kokkos_ENABLE_OPENMP=ON`. In that case, we still need to make sure to call `find_dependency(OpenMP)` when linking with `Trilinos` in downstream code.

I am mostly looking for an agreeable workaround. It would be sufficient if any `Trilinos` package that has `Kokkkos` as a direct dependency makes sure that `KokkosConfig.cmake` is included but I am not familiar enough with Trilinos to judge if that would be sensible or too much work.

Would forcing `Kokkos_ENABLE_OPENMP=ON` to imply `Trilinos_ENABLE_OpenMP=On` (and letting `Trilinos`/`TriBITS` handle the `OpenMP` flags) be a better  (short-term) solution?

**Comment by masterleinad** [comment] 2022-10-06 22:39
Alternatively, we could also just extract the `OpenMP` flag in case `Kokkos` is configured inside of `Trilinos` and don't link with it in that case.

**Comment by bartlettroscoe** [comment] 2022-10-06 23:47
> Would forcing Kokkos_ENABLE_OPENMP=ON to imply Trilinos_ENABLE_OpenMP=On (and letting Trilinos/TriBITS handle the OpenMP flags) be a better (short-term) solution?

@masterleinad, yea, I think that would work.  I think you could put the logic in the file:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/CallbackSetupExtraOptions.cmake

See [here](https://tribitspub.github.io/TriBITS/users_guide/index.html#repodir-cmake-callbacksetupextraoptions-cmake).

> I am mostly looking for an agreeable workaround. It would be sufficient if any Trilinos package that has Kokkkos as a direct dependency makes sure that KokkosConfig.cmake is included but I am not familiar enough with Trilinos to judge if that would be sensible or too much work.

When building Kokkos along with Trilinos, downstream packages in Trilinos would **not** read `KokkosConfig.cmake`.  That would only be read by downstream CMake projects.  Kokkos needs to behave consistently where it is pulled in with `add_subdirectory(kokkos)` or `find_package(Kokkos)`.

**Comment by masterleinad** [comment] 2022-10-07 13:24
@ndellingwood Would you mind trying if https://github.com/kokkos/kokkos/pull/5532 fixes this for you?

**Comment by masterleinad** [comment] 2022-10-07 13:46
Adding the `OpenMP` flags and not linking with `OpenMP` in case `Kokkos` was configured within `Trilinos` appears to be the minimally invasive short-term solution.

**Comment by bartlettroscoe** [comment] 2022-10-07 13:51
> Adding the `OpenMP` flags and not linking with `OpenMP` in case `Kokkos` was configured within `Trilinos` appears to be the minimally invasive short-term solution.

Okay, I added this to the list of issues to address in the incremental refactoring and modernization in the usage of CMake in https://github.com/TriBITSPub/TriBITS/issues/411.  Otherwise, we are continuing to pile on technical dept.  We need a steady stream of minimum required CMake version upgrades to keep up with this (e.g. https://github.com/trilinos/Trilinos/issues/10355).

**Comment by ndellingwood** [comment] 2022-10-07 20:37
> @ndellingwood Would you mind trying if #5532 fixes this for you?

@masterleinad just finished testing with your PR, that allowed the demo app to configure, compile and pass tests with the OpenMP build :)

**Closed** 2023-03-08 19:17 UTC
Labels: Blocks Promotion, InDevelop, Failure - Nightly, Failure - Trilinos
