### ISSUE TITLE
Possible issue with TeamVectorRange and Kokkos::MaxLoc<value_type, int>

### ISSUE THREAD

**Issue by kliegeois** [kokkos/kokkos#4976] opened 2022-04-22 22:50 UTC
This is related to https://github.com/kokkos/kokkos-kernels/issues/1388 

In the develop branch of Kokkos Kernels, we face this error:

```
05:19:28 2: [ RUN      ] cuda.batched_scalar_teamvector_gesv_static_pivoting_double
05:19:28 2: cudaDeviceSynchronize() error( cudaErrorIllegalInstruction): an illegal instruction was encountered /home/jenkins/jenkins-new/workspace/KokkosKernels_KokkosDev2_CLANG8_CUDA10_cpp14/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:151
05:19:28 2: Backtrace:
05:19:28 2:                         [0x9ddf70]
05:19:28 2:                         [0x9d4fe8]
05:19:28 2:                         [0x9d5068]
05:19:28 2:                         [0x440d36]
05:19:28 2:                         [0x9e45a9]
05:19:28 2:                         [0x440961]
05:19:28 2:                         [0x9e3f8b]
05:19:28 2:                         [0x9bd390]
05:19:28 2:                         [0x97905f]
05:19:28 2:                         [0x40d9f0]
05:19:28 2:                         [0x9af604]
05:19:28 2:                         [0x9935d0]
05:19:28 2:                         [0x9944c0]
05:19:28 2:                         [0x994c17]
05:19:28 2:                         [0x99d747]
05:19:28 2:                         [0x9b01c4]
05:19:28 2:                         [0x99d2db]
05:19:28 2:                         [0x40b350]
05:19:28 2: __libc_start_main [0x7f15cd62c555]
05:19:28 2:                         [0x40b264]
05:19:28  2/23 Test  #2: batched_dla_cuda .................Child aborted***Exception: 589.38 sec
...
```
when using:
```
  using reducer_value_type =
      typename Kokkos::MaxLoc<value_type, int>::value_type;
//...
    Kokkos::parallel_reduce(
        Kokkos::TeamVectorRange(member, n),
        [&](const int &j, reducer_value_type &update) {
          //...
        },
        reducer_value);
```
on kokkos-dev-2 test machine with:
```
source /projects/sems/modulefiles/utils/sems-archive-modules-init.sh ; module use /home/projects/x86-64/modulefiles/local
module purge
module load sems-archive-env sems-archive-cmake/3.17.1 sems-archive-gcc/7.2.0 clang/8.0 cuda/10.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Cuda,Serial --arch=SNB,Volta70 --compiler=clang++ --cxxflags="-O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-cuda-options=enable_lambda  --no-examples
```

However, it works fine when we replace `TeamVectorRange` by `ThreadVectorRange`.
It worked great (without the modification) on the other tested builds (including the PR tester).

**Comment by crtrott** [comment] 2022-04-25 19:26
Does it fail with newer clang/CUDA?

**Comment by kliegeois** [comment] 2022-04-25 21:45
It is the only known combination for which it failed.
It passed the KK CI tester and I think that all the other nightly builds passed too, can you confirm that @ndellingwood ?
In KK CI, we test cuda 9/gcc 7.2 and cuda 10 (but I don't know with which compiler).

**Comment by ajpowelsnl** [comment] 2022-05-10 16:55
Morning @ndellingwood -- can you give us an update on CI testing with cuda 9 & 10 + gcc/7.2?  Are we still seeing the failure caused by `TeamVectorRange` and `Kokkos::MaxLoc<value_type, int>`?

**Comment by ndellingwood** [comment] 2022-05-10 17:37
@ajpowelsnl this is continuing to fail in a kokkos-kernels nightly test with clang/8+cuda/10.0, I think @kliegeois posted the relevant snip of kokkos code related to `Kokkos::MaxLoc<value_type, int>`. I'm not sure of any isolated reproducer outside of the kokkos-kernels test

**Comment by ndellingwood** [comment] 2022-05-16 17:55
@ajpowelsnl I tested with clang/10.0 + cuda/10.0, kokkos/kokkos@810aa2a15e3b7de963ea352a6da81dd56d55babc , kokkos/kokkos-kernels@3c46a886cb3f77322d718c1a574a2244f61fb081 and the failing test passes in that case

**Comment by ajpowelsnl** [comment] 2022-07-05 15:43
Please use clang-10 or more recent.  This problem is resolved in recent versions of clang.

**Closed by ajpowelsnl** 2022-07-05 15:43 UTC
Labels: Bug
