### ISSUE TITLE
Nightly test failure, SYCL backend on PVC: kokkosp.parallel_scan_no_fence failure

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6794] opened 2024-02-08 18:23 UTC
**Describe the bug**
Nightly Sycl builds on PVC arch with intel/oneapi/2023.1.0 are failing in the `kokkosp.parallel_scan_no_fence` sub-test:
```
[ RUN      ] kokkosp.parallel_scan_no_fence
Test failure: encountered unwanted events
BeginFence { "Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence", 0,10}
EndFence { 10}
BeginFence { "Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence", 117440512,11}
EndFence { 11}
BeginParallelScan { "dogs", 117440513,12}
BeginFence { "Kokkos::Impl::sycl_deallocate: fence before deallocate", 117440512,13}
EndFence { 13}
BeginFence { "Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence", 0,14}
EndFence { 14}
BeginFence { "Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence", 117440512,15}
EndFence { 15}
EndParallelScan { 12}
/home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/tools/TestEventCorrectness.hpp:429: Failure
Value of: success
  Actual: false
Expected: true
[  FAILED  ] kokkosp.parallel_scan_no_fence (0 ms)
```

**Merged commits since previous pass**

Fix SharedAllocationRecord to allocate using the correct execution space instance (#6789) — [github](https://jenkins-son.sandia.gov/user/github/) / [githubweb](https://github.com/kokkos/kokkos/commit/391f2d12f2d3e5f896d497a11d0752aa47be7277)

Temporarily disable simd_reduction test for omptarget build — [Dong Hun Lee](https://jenkins-son.sandia.gov/user/donlee/) / [githubweb](https://github.com/kokkos/kokkos/commit/97997807de7f592a0845f96ee0adb4644a57efb2)
    SYCL: Error out on initialization if the backend is different from ext_oneapi_* (#6784) — [github](https://jenkins-son.sandia.gov/user/github/) / [githubweb](https://github.com/kokkos/kokkos/commit/01d5f8149da38abda68698421bb4aacd788c3d16)
    simd: support vector_aligned_tag (#6243) — [github](https://jenkins-son.sandia.gov/user/github/) / [githubweb](https://github.com/kokkos/kokkos/commit/31fb4761de109335999bf97cc9da89a8c6450a09)
    Add checks for unsafe implicit conversions in RangePolicy (#6754) — [github](https://jenkins-son.sandia.gov/user/github/) / [githubweb](https://github.com/kokkos/kokkos/commit/442e4d42ad53720d3e724052c995667bc7b77787)

**Please include the following for a minimal reproducer**

Reproducer (Blake PV queue):
```bash
salloc -N 1 -p PV

module load cmake intel-oneapi-compilers/2023.1.0 intel-oneapi-dpl/2022.1.0 git

$KOKKOS_PATH/generate_makefile.bash --with-sycl --arch=INTEL_PVC --compiler=icpx --cxxflags="-fp-model=precise" --cmake-flags=-DKokkos_ENABLE_ONEDPL=OFF

make -j

export ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu
ctest -R Kokkos_CoreUnitTest_KokkosP
```

**Comment by ndellingwood** [comment] 2024-02-08 18:26
Some of the other `Kokkos_CoreUnitTest_KokkosP` subtests generate output even when successful, in case it is unintentional I'll list that here for reference:

```
[ RUN      ] kokkosp.test_named_instance_fence
Ref: 117440513
Ref: named_instance
117440513
named_instance
[       OK ] kokkosp.test_named_instance_fence (0 ms)
[ RUN      ] kokkosp.test_unnamed_instance_fence
Ref: 117440513
Ref: Unnamed Instance Fence
117440513
Kokkos::Experimental::SYCL::fence: Unnamed Instance Fence
[       OK ] kokkosp.test_unnamed_instance_fence (0 ms)
[ RUN      ] kokkosp.test_named_global_fence
Ref: 117440512
Ref: test global fence
0
test global fence
Miss on id
117440512
test global fence
[       OK ] kokkosp.test_named_global_fence (0 ms)
[ RUN      ] kokkosp.test_unnamed_global_fence
Ref: 117440512
Ref: Unnamed Global Fence
0
Kokkos::fence: Unnamed Global Fence
Miss on id
117440512
Kokkos::fence: Unnamed Global Fence
[       OK ] kokkosp.test_unnamed_global_fence (0 ms)
[ RUN      ] kokkosp.test_multiple_default_instances
[       OK ] kokkosp.test_multiple_default_instances (0 ms)
[ RUN      ] kokkosp.test_id_gen
[       OK ] kokkosp.test_id_gen (0 ms)
[ RUN      ] kokkosp.test_kernel_sequence
Ref: 117440513
Ref: named_instance
117440513
named_instance
Ref: 117440513
Ref: test_kernel
117440513
named_instance
Miss on name
0
Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence
Miss on name
Miss on id
117440512
Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence
Miss on name
Miss on id
117440513
test_kernel
[       OK ] kokkosp.test_kernel_sequence (0 ms)
...
[ RUN      ] kokkosp.test_kernel_sequence
Ref: 117440513
Ref: named_instance
117440513
named_instance
Ref: 117440513
Ref: test_kernel
117440513
named_instance
Miss on name
0
Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence
Miss on name
Miss on id
117440512
Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence
Miss on name
Miss on id
117440513
test_kernel
[       OK ] kokkosp.test_kernel_sequence (0 ms)
```

**Comment by masterleinad** [comment] 2024-02-08 20:38
```
BeginFence { "Kokkos::Impl::sycl_deallocate: fence before deallocate", 117440512,13}
```
is the culprit but I struggle to reproduce.

**Comment by masterleinad** [comment] 2024-02-14 20:36
@ndellingwood I just tried again and used your build instructions. Can you confirm that you are still seeing the issue?

**Comment by ndellingwood** [comment] 2024-02-14 21:17
@masterleinad yes, the `kokkosp.parallel_scan_no_fence` has been failing consistently in our nightly job

**Comment by masterleinad** [comment] 2024-02-14 21:45
@ndellingwood Any chance you can debug that? Maybe add
```diff
diff --git a/core/src/SYCL/Kokkos_SYCL_Space.cpp b/core/src/SYCL/Kokkos_SYCL_Space.cpp
index 9cc8008cd..fe13bd2af 100644
--- a/core/src/SYCL/Kokkos_SYCL_Space.cpp
+++ b/core/src/SYCL/Kokkos_SYCL_Space.cpp
@@ -197,7 +197,7 @@ void sycl_deallocate(const char* arg_label, void* const arg_alloc_ptr,
   }
 
   SYCL::impl_static_fence(
-      "Kokkos::Impl::sycl_deallocate: fence before deallocate");
+      std::string("Kokkos::Impl::sycl_deallocate: fence before deallocate ")+arg_label);
   sycl::free(arg_alloc_ptr, queue);
 }
```
to see which View is deallocated or set a breakpoint in `sycl_deallocate`.

**Comment by ndellingwood** [comment] 2024-02-20 20:37
@masterleinad if I run the test in isolation (e.g. `./Kokkos_CoreUnitTest_KokkosP --gtest_filter=kokkosp.parallel_scan_no_fence`) the test does not fail, only when I run the full executable `Kokkos_CoreUnitTest_KokkosP`

I added the change you suggested, this is the output (when running the full executable which triggers the failure):
```
[ RUN      ] kokkosp.parallel_scan_no_fence
Test failure: encountered unwanted events
BeginFence { "Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence", 0,10}
EndFence { 10}
BeginFence { "Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence", 117440512,11}
EndFence { 11}
BeginParallelScan { "dogs", 117440513,12}
BeginFence { "Kokkos::Impl::sycl_deallocate: fence before deallocate [unlabeled]", 117440512,13}
EndFence { 13}
BeginFence { "Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence", 0,14}
EndFence { 14}
BeginFence { "Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence", 117440512,15}
EndFence { 15}
EndParallelScan { 12}
/home/ndellin/kokkos/core/unit_test/tools/TestEventCorrectness.hpp:429: Failure
Value of: success
  Actual: false
Expected: true
[  FAILED  ] kokkosp.parallel_scan_no_fence (0 ms)
```

**Comment by masterleinad** [comment] 2024-02-20 20:45
Hmm... so the problematic allocation doesn't even have a label.

**Comment by ndellingwood** [comment] 2024-02-20 20:47
@masterleinad it's weird because the failure does not occur when running the `kokkosp.parallel_scan_no_fence` in isolation. Is there any type of state associated with the `TestEventCorrectness` stuff that may be dirty from a previous subtest and just happens to trigger the fail within `kokkosp.parallel_scan_no_fence` ?

**Comment by masterleinad** [comment] 2024-02-20 20:53
We could try to fence before calling `validate_absence`.

**Comment by ndellingwood** [comment] 2024-02-20 22:57
@masterleinad I tried adding fences before each `validate_absence` call in `core/unit_test/tools/TestEventCorrectness.hpp` but the test still failed

**Comment by masterleinad** [comment] 2024-02-21 18:38
The following patch makes sure that we always have a label when deallocating. Can you try that? My best bet is that we are seeing some `Kokkos::Experimental::SYCL::USMObjectMem` deallocation (but I still can't reproduce).
 
```diff
diff --git a/core/src/SYCL/Kokkos_SYCL_Instance.cpp b/core/src/SYCL/Kokkos_SYCL_Instance.cpp
index 0e67adb57..355067dca 100644
--- a/core/src/SYCL/Kokkos_SYCL_Instance.cpp
+++ b/core/src/SYCL/Kokkos_SYCL_Instance.cpp
@@ -216,13 +216,13 @@ void SYCLInternal::finalize() {
   auto device_mem_space = SYCLDeviceUSMSpace(*m_queue);
   auto host_mem_space   = SYCLHostUSMSpace(*m_queue);
   if (nullptr != m_scratchSpace)
-    device_mem_space.deallocate(m_scratchSpace,
+    device_mem_space.deallocate("Kokkos::Experimental::SYCL::InternalScratchSpace", m_scratchSpace,
                                 m_scratchSpaceCount * sizeScratchGrain);
   if (nullptr != m_scratchHost)
-    host_mem_space.deallocate(m_scratchHost,
+    host_mem_space.deallocate("Kokkos::Experimental::SYCL::InternalScratchHost", m_scratchHost,
                               m_scratchHostCount * sizeScratchGrain);
   if (nullptr != m_scratchFlags)
-    device_mem_space.deallocate(m_scratchFlags,
+    device_mem_space.deallocate("Kokkos::Experimental::SYCL::InternalScratchFlags", m_scratchFlags,
                                 m_scratchFlagsCount * sizeScratchGrain);
   m_syclDev           = -1;
   m_scratchSpaceCount = 0;
@@ -256,7 +256,7 @@ sycl::device_ptr<void> SYCLInternal::scratch_space(const std::size_t size) {
     auto mem_space = Kokkos::Experimental::SYCLDeviceUSMSpace(*m_queue);
 
     if (nullptr != m_scratchSpace)
-      mem_space.deallocate(m_scratchSpace,
+      mem_space.deallocate("Kokkos::Experimental::SYCL::InternalScratchSpace", m_scratchSpace,
                            m_scratchSpaceCount * sizeScratchGrain);
 
     m_scratchSpaceCount = scratch_count(size);
@@ -276,7 +276,7 @@ sycl::host_ptr<void> SYCLInternal::scratch_host(const std::size_t size) {
     auto mem_space = Kokkos::Experimental::SYCLHostUSMSpace(*m_queue);
 
     if (nullptr != m_scratchHost)
-      mem_space.deallocate(m_scratchHost,
+      mem_space.deallocate("Kokkos::Experimental::SYCL::InternalScratchHost", m_scratchHost,
                            m_scratchHostCount * sizeScratchGrain);
 
     m_scratchHostCount = scratch_count(size);
@@ -296,7 +296,7 @@ sycl::device_ptr<void> SYCLInternal::scratch_flags(const std::size_t size) {
     auto mem_space = Kokkos::Experimental::SYCLDeviceUSMSpace(*m_queue);
 
     if (nullptr != m_scratchFlags)
-      mem_space.deallocate(m_scratchFlags,
+      mem_space.deallocate("Kokkos::Experimental::SYCL::InternalScratchFlags", m_scratchFlags,
                            m_scratchFlagsCount * sizeScratchGrain);
 
     m_scratchFlagsCount = scratch_count(size);
@@ -358,7 +358,7 @@ size_t SYCLInternal::USMObjectMem<Kind>::reserve(size_t n) {
 
   if (m_capacity < n) {
     AllocationSpace alloc_space(*m_q);
-    if (m_data) alloc_space.deallocate(m_data, m_capacity);
+    if (m_data) alloc_space.deallocate("Kokkos::Experimental::SYCL::USMObjectMem", m_data, m_capacity);
 
     m_data =
         alloc_space.allocate("Kokkos::Experimental::SYCL::USMObjectMem", n);
@@ -377,7 +377,7 @@ void SYCLInternal::USMObjectMem<Kind>::reset() {
     // This implies a fence since this class is not copyable
     // and deallocating implies a fence across all registered queues.
     AllocationSpace alloc_space(*m_q);
-    alloc_space.deallocate(m_data, m_capacity);
+    alloc_space.deallocate("Kokkos::Experimental::SYCL::USMObjectMem", m_data, m_capacity);
 
     m_capacity = 0;
     m_data     = nullptr;
diff --git a/core/src/SYCL/Kokkos_SYCL_Space.cpp b/core/src/SYCL/Kokkos_SYCL_Space.cpp
index 9cc8008cd..387d64e78 100644
--- a/core/src/SYCL/Kokkos_SYCL_Space.cpp
+++ b/core/src/SYCL/Kokkos_SYCL_Space.cpp
@@ -197,14 +197,14 @@ void sycl_deallocate(const char* arg_label, void* const arg_alloc_ptr,
   }
 
   SYCL::impl_static_fence(
-      "Kokkos::Impl::sycl_deallocate: fence before deallocate");
+      std::string("Kokkos::Impl::sycl_deallocate: fence before deallocate ")+arg_label);
   sycl::free(arg_alloc_ptr, queue);
 }
 
-void SYCLDeviceUSMSpace::deallocate(void* const arg_alloc_ptr,
-                                    const size_t arg_alloc_size) const {
-  deallocate("[unlabeled]", arg_alloc_ptr, arg_alloc_size);
-}
+//void SYCLDeviceUSMSpace::deallocate(void* const arg_alloc_ptr,
+//                                    const size_t arg_alloc_size) const {
+//  deallocate("[unlabeled]", arg_alloc_ptr, arg_alloc_size);
+//}
 void SYCLDeviceUSMSpace::deallocate(const char* arg_label,
                                     void* const arg_alloc_ptr,
                                     const size_t arg_alloc_size,
@@ -213,10 +213,10 @@ void SYCLDeviceUSMSpace::deallocate(const char* arg_label,
                   Kokkos::Tools::make_space_handle(name()), m_queue);
 }
 
-void SYCLSharedUSMSpace::deallocate(void* const arg_alloc_ptr,
-                                    const size_t arg_alloc_size) const {
-  deallocate("[unlabeled]", arg_alloc_ptr, arg_alloc_size);
-}
+//void SYCLSharedUSMSpace::deallocate(void* const arg_alloc_ptr,
+//                                    const size_t arg_alloc_size) const {
+//  deallocate("[unlabeled]", arg_alloc_ptr, arg_alloc_size);
+//}
 
 void SYCLSharedUSMSpace::deallocate(const char* arg_label,
                                     void* const arg_alloc_ptr,
@@ -226,10 +226,10 @@ void SYCLSharedUSMSpace::deallocate(const char* arg_label,
                   Kokkos::Tools::make_space_handle(name()), m_queue);
 }
 
-void SYCLHostUSMSpace::deallocate(void* const arg_alloc_ptr,
-                                  const size_t arg_alloc_size) const {
-  deallocate("[unlabeled]", arg_alloc_ptr, arg_alloc_size);
-}
+//void SYCLHostUSMSpace::deallocate(void* const arg_alloc_ptr,
+//                                  const size_t arg_alloc_size) const {
+//  deallocate("[unlabeled]", arg_alloc_ptr, arg_alloc_size);
+//}
 
 void SYCLHostUSMSpace::deallocate(const char* arg_label,
                                   void* const arg_alloc_ptr,
diff --git a/core/src/SYCL/Kokkos_SYCL_Space.hpp b/core/src/SYCL/Kokkos_SYCL_Space.hpp
index b86cfca41..653bea53e 100644
--- a/core/src/SYCL/Kokkos_SYCL_Space.hpp
+++ b/core/src/SYCL/Kokkos_SYCL_Space.hpp
@@ -60,8 +60,8 @@ class SYCLDeviceUSMSpace {
   void* allocate(const char* arg_label, const size_t arg_alloc_size,
                  const size_t arg_logical_size = 0) const;
 
-  void deallocate(void* const arg_alloc_ptr,
-                  const std::size_t arg_alloc_size) const;
+  //void deallocate(void* const arg_alloc_ptr,
+  //                const std::size_t arg_alloc_size) const;
   void deallocate(const char* arg_label, void* const arg_alloc_ptr,
                   const size_t arg_alloc_size,
                   const size_t arg_logical_size = 0) const;
@@ -101,8 +101,8 @@ class SYCLSharedUSMSpace {
   void* allocate(const char* arg_label, const size_t arg_alloc_size,
                  const size_t arg_logical_size = 0) const;
 
-  void deallocate(void* const arg_alloc_ptr,
-                  const std::size_t arg_alloc_size) const;
+  //void deallocate(void* const arg_alloc_ptr,
+  //                const std::size_t arg_alloc_size) const;
   void deallocate(const char* arg_label, void* const arg_alloc_ptr,
                   const size_t arg_alloc_size,
                   const size_t arg_logical_size = 0) const;
@@ -142,8 +142,8 @@ class SYCLHostUSMSpace {
   void* allocate(const char* arg_label, const size_t arg_alloc_size,
                  const size_t arg_logical_size = 0) const;
 
-  void deallocate(void* const arg_alloc_ptr,
-                  const std::size_t arg_alloc_size) const;
+  //void deallocate(void* const arg_alloc_ptr,
+  //                const std::size_t arg_alloc_size) const;
   void deallocate(const char* arg_label, void* const arg_alloc_ptr,
                   const size_t arg_alloc_size,
                   const size_t arg_logical_size = 0) const;
```

**Comment by ajpowelsnl** [comment] 2024-02-27 19:49
@masterleinad , @ndellingwood - great team work!

**Comment by ajpowelsnl** [comment] 2024-04-08 20:19
@masterleinad , @masterleinad -- are we good to close this issue?

**Closed** 2024-04-08 20:23 UTC
Labels: Bug, InDevelop, Failure - Nightly, Backend - SYCL
