### ISSUE TITLE
Makefile.kokkos Can Have Issues with Compiler Selection

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#556] opened 2016-12-01 16:07 UTC
We have an potential issue with the compiler selection. The `ifeq ($(KOKKOS_INTERNAL_COMPILER_XL), 1)` can be an issue if the version outputs additional text (e.g. the XL Beta compiler). This should really be a greater than check rather than an equals.

**Comment by crtrott** [comment] 2016-12-01 16:12
yeah I know I fixed that internally already.

**Comment by crtrott** [comment] 2016-12-01 16:13
Duplicate of #553 so I close this again.

**Closed by crtrott** 2016-12-01 16:13 UTC
Labels: duplicate
