### ISSUE TITLE
DefaultInit tests failing when using CTest resource allocation feature

### ISSUE THREAD

**Issue by KyleFromKitware** [kokkos/kokkos#3040] opened 2020-05-15 19:06 UTC
Cc: @bartlettroscoe 

We've been testing trilinos/Trilinos#6840 with the [CTest resource allocation](https://cmake.org/cmake/help/latest/manual/ctest.1.html#resource-allocation) feature (added to Kokkos in #2765), and have had tremendous success in speeding up the testing process by spreading the tests evenly among GPUs.

One thing we noticed is that the `DefaultInit` tests are expecting the GPU ID to always be 0. However, CTest may set the ID to be something else depending on how it has allocated its resources, causing these tests to [fail](https://testing-dev.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=5450093). I am opening this issue to discuss ways to resolve this conflict of requirements.

We don't want to simply not run the tests so that we don't potentially introduce bugs. However, one thing that just occurred to me is that these tests might *only* be testing the GPU ID, in which case it may actually make sense to skip them when using resource allocation. I'm hoping that someone with expertise in these tests can give us some insight.

**Comment by KyleFromKitware** [comment] 2020-05-15 19:34
After taking a closer look at the code, I believe I may have an idea of what to do:

```patch
From a1c1104072d5b6e3a0ef8bd121124424e1562821 Mon Sep 17 00:00:00 2001
From: Kyle Edwards <kyle.edwards@kitware.com>
Date: Fri, 15 May 2020 15:32:42 -0400
Subject: [PATCH] Expect CTest GPU if no GPU is specified on command line

Note: Since get_ctest_gpu() returns 0 if CTest has not provided
anything, it is safe to always call it.
---
 core/unit_test/TestDefaultDeviceTypeInit.hpp | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

diff --git a/core/unit_test/TestDefaultDeviceTypeInit.hpp b/core/unit_test/TestDefaultDeviceTypeInit.hpp
index 33c736c..2ebe230 100644
--- a/core/unit_test/TestDefaultDeviceTypeInit.hpp
+++ b/core/unit_test/TestDefaultDeviceTypeInit.hpp
@@ -52,6 +52,14 @@
 
 #if !defined(KOKKOS_ENABLE_CUDA) || defined(__CUDACC__)
 
+namespace Kokkos {
+namespace Impl {
+
+int get_ctest_gpu(const char *local_rank_str);
+
+}  // namespace Impl
+}  // namespace Kokkos
+
 namespace Test {
 
 namespace Impl {
@@ -273,7 +281,7 @@ void check_correct_initialization(const Kokkos::InitArguments& argstruct) {
 
     int expected_device = argstruct.device_id;
     if (argstruct.device_id < 0) {
-      expected_device = 0;
+      expected_device = get_ctest_gpu();
     }
 
     ASSERT_EQ(expected_device, device);
-- 
2.7.4
```

@bartlettroscoe let's try this on the Trilinos branch and see if it helps.

**Comment by bartlettroscoe** [comment] 2020-05-15 19:36
@KyleFromKitware,

> let's try this on the Trilinos branch and see if it helps.

Can you please go ahead and push a commit for that to the branch in https://github.com/trilinos/Trilinos/pull/6840?  Then I will try that out.

**Comment by bartlettroscoe** [comment] 2020-05-15 19:37
Just to be clear, as of now, in order to merge https://github.com/trilinos/Trilinos/pull/6840, we are going to need to either disable all of these tests or we will have to allow them all to fail and create a lot of red on the dashboard.  Neither of these are good options if Kokkos is going to be running the ATDM Trilinos builds as a criteria to update Kokkos into Trilinos.

**Comment by bartlettroscoe** [comment] 2020-05-15 19:39
Note that the random failures we are seeing show:

```
/ascldap/users/rabartl/Trilinos.base/BUILDS/WATERMAN/CTEST_S/Trilinos-atdm-waterman_cuda-9.2_shared_opt/SRC_AND_BUILD/Trilinos/packages/kokkos/core/unit_test/TestDefaultDeviceTypeInit.hpp:279: Failure
Value of: device
  Actual: 1
Expected: expected_device
Which is: 0
```

That checks makes no sense when using the ctest GPU allocation approach (since we want rank-1 tests to be distributed to other GPUs on the node, not just the first GPU).

**Comment by KyleFromKitware** [comment] 2020-05-15 19:43
> That checks makes no sense when using the ctest GPU allocation approach

Right. This change causes it to expect whatever was assigned by CTest instead of a hard-coded 0.

**Comment by stanmoore1** [comment] 2020-05-15 19:44
I think this all depends on how you set the `CUDA_VISIBLE_DEVICES` env variable.

**Comment by KyleFromKitware** [comment] 2020-05-15 19:54
> I think this all depends on how you set the `CUDA_VISIBLE_DEVICES` env variable.

Our code does not set `CUDA_VISIBLE_DEVICES` in any way.

**Comment by stanmoore1** [comment] 2020-05-15 19:56
I mean you can set `CUDA_VISIBLE_DEVICES` to mask out all but a single GPU for each test (can be a different GPU for each test), then the device id should always be 0, right?

**Comment by KyleFromKitware** [comment] 2020-05-15 19:58
That is true, and it may be something to try if my proposed approach doesn't work. However, when we added the CTest feature to Kokkos, the behavior changed - instead of defaulting to a hard-coded 0 for a non-MPI test, it now defaults to whatever was assigned by CTest. Therefore, I think the test should be updated with this expectation. (It really should have been updated in the first place, but we didn't catch this when we tested it.)

**Comment by jjellio** [comment] 2020-05-15 21:45
`CUDA_VISIBLE_DEVICES` is the way the ATS2 job launchers work. The resource manager hands out GPU ids based on what `jsrun` requires.  If `-g1` is used, you will always see the nvidia device as zero, since `CUDA_VISIBLE_DEVICES` always has one id in it.

I'm curious how the CTest stuff is going work with platforms that set CUDA_VISIBLE_DEVICES. If you try to enforce a device id, but the job launcher gives you 1 device, (which will now become devid=0),  you will get a device id out of range error from Cuda.

**Comment by bartlettroscoe** [comment] 2020-05-15 22:17
> I'm curious how the CTest stuff is going work with platforms that set `CUDA_VISIBLE_DEVICES`

We will find out when I try this on 'vortex' next week.

So if `jsrun` is setting `CUDA_VISIBLE_DEVICES` correctly and knows to spread out work over the various GPUs for multiple **simultaneous** invocations of `jsrun` on the same node, we should see about prefect scaling when going from `ctest -j` to `ctest -j4` when running a bunch of MPI 1-rank tests, right?  A simple experiment with `jsrun` will tell us it if is being smart about that or not.  (Just need to run a shell script that prints out `CUDA_VISIBLE_DEVICES` for each MPI rank.)

**Comment by KyleFromKitware** [comment] 2020-05-15 22:40
> `CUDA_VISIBLE_DEVICES` is the way the ATS2 job launchers work. The resource manager hands out GPU ids based on what `jsrun` requires. If `-g1` is used, you will always see the nvidia device as zero, since `CUDA_VISIBLE_DEVICES` always has one id in it.
> 
> I'm curious how the CTest stuff is going work with platforms that set CUDA_VISIBLE_DEVICES. If you try to enforce a device id, but the job launcher gives you 1 device, (which will now become devid=0), you will get a device id out of range error from Cuda.

This sounds like a case of both CTest and ATS2 trying to manage the allocation of GPUs. Either CTest or ATS2 should assign a GPU, but not both. So, if ATS2 is assigning GPUs through `CUDA_VISIBLE_DEVICES`, then CTest should not be assigning them.

**Comment by jjellio** [comment] 2020-05-15 23:03
Ross, Jsrun does the right thing.  I've built on one node, and then allocated 4 nodes for unit testing. It will 'fan-out' and run multiple '-r4 -g1 -c4 -brs -p1' tests. That will enforce 4 possible tasks per node, and if p>4, it will start spanning nodes.

**Comment by bartlettroscoe** [comment] 2020-05-15 23:08
>  I've built on one node, and then allocated 4 nodes for unit testing. It will 'fan-out' and run multiple '-r4 -g1 -c4 -brs -p1' tests. That will enforce 4 possible tasks per node, and if p>4, it will start spanning nodes.

@jjellio, no, I mean allocate **1 node** and then run **4** `jsrun` commands at the same time on that **one** node, each for a rank-1 MPI test.  Does `jsrun` do the right thing in that case?   As each `jsrun` command starts up on the single node, will it know about the `jsrun` commands already running using GPUs?  I guess we will find out on Monday.

**Comment by jjellio** [comment] 2020-05-15 23:09
Kyle, Jsrun is just one platform though.  Unit testing on our testbeds usually requires direct mpirun usage (white/ride/waterman) - it was those platforms that motivated --kokkos-ndevices usage. 

Whatever solution you have, it'd be good to keep in mind non-nvidia platforms do exist. I'd hope going forward something like CUDA_VISIBLE_DEVICES is exposed... it allows a pretty sane way to go about this via ENV variables.

There's a github issue somewhere where I posted what JSRUN does with multiple invocations. I did the test by using jsrun,  but having it spawn a bunch of jsrun's in the background. E.g., for i in 1..100; jsrun ... &

**Comment by jjellio** [comment] 2020-05-15 23:11
Ross,

https://github.com/trilinos/Trilinos/pull/5598#issuecomment-516887866

**Comment by bartlettroscoe** [comment] 2020-05-16 15:41
> Getting the jsrun correct to do what you want may be another challenge. In the test, I used `-r1` which specifically says I want 1 resource set. I believe what I did should work with `-r4 -g1 -c4 -brs -p` (which can be the default `Trilinos_MPIEXEC_NUM_PROCS_FLAG`).

@jjellio, okay, I might need your help getting https://github.com/trilinos/Trilinos/pull/6840 to work correctly on ATS-2 systems with LSF and jsrun.  (Or just disabling this CTest feature if jsrun in already doing the right thing).

**Comment by bartlettroscoe** [comment] 2020-05-19 02:33
@KyleFromKitware, looking at the code in the file `packages/kokkos/core/src/impl/Kokkos_Core.cpp` in more detail, it seems obvious that a more significant refactoring will be needed to be able to return the ctest-set GPU ID.

**Comment by crtrott** [comment] 2020-05-19 03:11
I think that @KyleFromKitware proposal is totally fine. The whole idea is to see whether the GPU returned is the right one. Now we may need to make sure that if the ctest variables are not set (because you for example just run the executable in a shell instead of calling ctest) that it also has the right answer. But I looked at the code and the call returns 0 in that case, so we should be fine. If you just want to open a PR with that change that is fine with me.

**Comment by bartlettroscoe** [comment] 2020-05-19 12:14
I looked at the code in `packages/kokkos/core/src/impl/Kokkos_Core.cpp` a little more and it looks like it will be easy to extract out a function called `get_gpu()` that will do the right thing.  I will try that, test, and if it looks good, post PRs.

**Comment by crtrott** [comment] 2020-05-19 15:11
why does the current one not do that?

**Comment by bartlettroscoe** [comment] 2020-05-19 15:17
> why does the current one not do that?

@crtrott, see https://github.com/trilinos/Trilinos/pull/6840/commits/a3c3bb83c61653f7204fdd9c369d68c34a3602b8.

I will post a matching Kokkos PR shortly.

**Comment by bartlettroscoe** [comment] 2020-05-19 16:12
@KyleFromKitware and @crtrott, the full fix is in #3048.  I tested this on 'waterman' and the tests that were failing as shown in https://github.com/trilinos/Trilinos/pull/6840#issuecomment-628732349 are now passing with this patch to Kokkos.

**Comment by bartlettroscoe** [comment] 2020-05-19 22:47
Looks like we have a resolution in PR #3048, it was just approved to be merged.  I will then merge the matching changes in the Trilinos side as part of https://github.com/trilinos/Trilinos/pull/6840.

**Comment by masterleinad** [comment] 2020-05-19 22:49
Only @crtrott and @dalg24 have the rights to merge in `Kokkos`. You might want to wait a bit.

**Comment by crtrott** [comment] 2020-05-20 21:58
I merged this.

**Comment by bartlettroscoe** [comment] 2020-05-20 22:02
Thanks all!  We can close now.

**Comment by crtrott** [comment] 2020-05-20 22:45
Args. I overlooked that the PR was against master :-( …

**Comment by bartlettroscoe** [comment] 2020-05-20 22:47
>Args. I overlooked that the PR was against master :-( …

Sorry about that.

Just revert the merge commit and push and then I will rebase the topic branch and post a new PR.

**Comment by bartlettroscoe** [comment] 2020-05-22 17:36
> Args. I overlooked that the PR was against master :-( …

@crtrott, the PR #3061 against 'develop' takes care of any problems that might have been caused by the incorrect merge of PR #3048 to the 'master' branch.

**Closed** 2020-08-20 01:11 UTC
Labels: InDevelop, enhancement
