### ISSUE TITLE
Remove need for volatile overloads for types in Kokkos reductions

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos#4077] opened 2021-06-07 08:16 UTC
- [ ] identify where reductions are implemented
- [ ] remove volatile overloads
- [ ] ensure all tests work 

@PhilMiller commented: the tests should ideally not just pass, but also exhibit no errors from ThreadSanitizer or a comparable dynamic data race analysis. This may be complicated by the fact that ThreadSanitizer doesn't directly support atomic fence operations, only actual atomic loads and stores (cf https://github.com/google/sanitizers/issues/1352 since this deficiency isn't actually documented otherwise!)

**Comment by PhilMiller** [comment] 2021-07-25 22:37
The casts to `volatile` types occur in places like `Kokkos_{Cuda,HIP}_Team.hpp` in their global reductions to obtain the final results. Conversion of the non-`volatile` `join` operators to use `atomic` operations would seemingly accomplish the same  goals, though possibly at the expense of performance for the steps of the reduction that occur in non-concurrent shared memory access.

**Comment by PhilMiller** [comment] 2021-07-25 22:38
Conversely, a lot of operations on compound types can be performed piece-wise atomically, whereever the member elements don't interact in how the operator behaves. E.g. sum, difference, point-wise min, max

**Comment by masterleinad** [comment] 2021-07-26 13:36
> The casts to `volatile` types occur in places like `Kokkos_{Cuda,HIP}_Team.hpp` in their global reductions to obtain the final results. Conversion of the non-`volatile` `join` operators to use `atomic` operations would seemingly accomplish the same goals, though possibly at the expense of performance for the steps of the reduction that occur in non-concurrent shared memory access.

AFAICT, `__syncthread` and `__syncwarp` should be enough to make sure that access to shared memory works correctly. I would be curious to hear why this might not be sufficient.

**Comment by PhilMiller** [comment] 2021-07-27 03:23
The same overloads appear in documentation and examples for `parallel_scan` functors as well. I haven't yet gone over their implementation to see whether the `volatile` bits can just be dropped there, too.

**Comment by PhilMiller** [comment] 2021-07-27 22:22
In my ongoing implementation effort, I’ve reached a point where I can displace the volatile qualifiers from the join operations on every reduce functor to copy and/or assignment operations on the underlying value types. If forming a reference through a volatile T* is sufficient to actually guarantee the code will access the shared memory location, then I don’t need volatile-qualified copy/assignment of the value type, either

**Comment by PhilMiller** [comment] 2021-08-04 01:46
In discussion with @crtrott we concluded that for the nasty case in CUDA, we can replace the `join` calls on `volatile T&` with special memcopy calls with `volatile` source pointers to make suitable temporary objects, and then `join` from those.

**Comment by PhilMiller** [comment] 2021-11-08 21:08
This was predated by #1554!

**Comment by PhilMiller** [comment] 2022-03-02 20:20
With upcoming changes to `FunctorValueTraits/FunctorValueAnalysis`, we could perhaps embed the CUDA-specific logic to do scalar copies as `volatile memcpy` in there. That would sidestep the scalar/array distinction, and cover all call sites by design.

**Comment by PhilMiller** [comment] 2022-03-03 22:44
https://github.com/kokkos/kokkos/pull/4838 doesn't end up covering all of the array cases, because the provided functor can implement an overload of `join()` that takes an array directly.

Anyway, it mostly ends up demonstrating, again, that there's a race condition elsewhere in the reduction code.

**Comment by PhilMiller** [comment] 2022-04-12 03:40
Addressed by #4931

**Closed by PhilMiller** 2022-04-12 03:40 UTC
Labels: Enhancement
