### ISSUE TITLE
4.2 compilation with cuda

### ISSUE THREAD

**Issue by VictorEijkhout** [kokkos/kokkos#6757] opened 2024-01-29 19:49 UTC
```CMake Error at /opt/apps/cmake/3.24.2/share/cmake-3.24/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/work/00434/eijkhout/kokkos/kokkos-4.2.00/bin/nvcc_wrapper"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /work/00434/eijkhout/kokkos/build-4.2.00-milan-intel24-cuda/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_840b2/fast && gmake[3]: Entering directory '/work/00434/eijkhout/kokkos/build-4.2.00-milan-intel24-cuda/CMakeFiles/CMakeTmp'
    /usr/bin/gmake  -f CMakeFiles/cmTC_840b2.dir/build.make CMakeFiles/cmTC_840b2.dir/build
    gmake[4]: Entering directory '/work/00434/eijkhout/kokkos/build-4.2.00-milan-intel24-cuda/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_840b2.dir/testCXXCompiler.cxx.o
    /work/00434/eijkhout/kokkos/kokkos-4.2.00/bin/nvcc_wrapper   -std=c++20 -allow-unsupported-compiler  -o CMakeFiles/cmTC_840b2.dir/testCXXCompiler.cxx.o -c /work/00434/eijkhout/kokkos/build-4.2.00-milan-intel24-cuda/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    /scratch/tacc/apps/gcc/13.2.0/lib/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/type_traits(1543): error: identifier "__remove_cv" is undefined
```

I notice that you define your own `struct remove_cv` while this is part of the c++20 standard. Is this a conflict?

Here's my cmake line:
```
cmdline=cmake 
-D CMAKE_INSTALL_PREFIX=/work/00434/eijkhout/kokkos/installation-kokkos-4.2.00-milan-intel24-cuda/cuda                     
-D CMAKE_VERBOSE_MAKEFILE=ON                    
 -D BUILD_SHARED_LIBS=ON                     
-D CMAKE_CXX_COMPILER=/work/00434/eijkhout/kokkos/kokkos-4.2.00/bin/nvcc_wrapper       
-D CMAKE_CXX_FLAGS='-std=c++20 -allow-unsupported-compiler'       
-D Kokkos_ENABLE_SERIAL=ON -D Kokkos_ENABLE_CUDA=ON       
-D Kokkos_ARCH_TURING75=ON -D Kokkos_ENABLE_CUDA_LAMBDA=ON       
-D KOKKOS_CUDA_OPTIONS=-allow-unsupported-compiler                             
/work/00434/eijkhout/kokkos/kokkos-4.2.00/
```

**Comment by masterleinad** [comment] 2024-01-29 20:04
Please follow our issue template. In particular, the version of all compilers (host and device) would be helpful here.

You have `-allow-unsupported-compiler` in your compile flags which sounds very suspicious if you are running into these kinds of errors.

> I notice that you define your own struct remove_cv while this is part of the c++20 standard. Is this a conflict?

You probably mean `remove_cvref` instead. Our implementation in namespace `Kokkos::Impl` looks like https://github.com/kokkos/kokkos/blob/71a9bcae52543bd065522bf3e41b5bfa467d8015/core/src/impl/Kokkos_Utilities.hpp#L68-L80 so we defer to `std::remove_cvref` and the test in question doesn't use  `Kokkos` anyway.

**Comment by dalg24** [comment] 2024-01-29 20:58
Looks like a duplicate of #6759 
This is clearly an issue with your toolchain, not Kokkos

**Comment by ajpowelsnl** [comment] 2024-02-12 16:13
@VictorEijkhout - Please us know (via #6759 ) within the next or so if we can help further.

**Comment by ajpowelsnl** [comment] 2024-02-12 16:14
@VictorEijkhout - Please us know (via #6759 ) within the next or so if we can help further.

**Closed by ajpowelsnl** 2024-02-12 16:13 UTC
