### ISSUE TITLE
Would like a Kokkos wrapper for "cudaDeviceSetLimit (cudaLimitStackSize, new_stack_size);"

### ISSUE THREAD

**Issue by overfelt** [kokkos/kokkos#2373] opened 2019-09-24 21:52 UTC
Our application was running out of stack space on a cuda launch.  Kokkos sets the stack size for cuda on each kernel launch but this appears to be too small for our application.  Now we have a call in main: 

#ifdef KOKKOS_ENABLE_CUDA
   cudaDeviceSetLimit (cudaLimitStackSize, new_stack_size);
#endif

And we would simply like to push the ifdef into the Kokkos library by having this in a kokkos function call.  We do not need to reset the stack size on each kernel launch as we are using relocatable device code and do not want to determine the optimal stack size for each launch.  A fixed global stack size is sufficient for now.

**Comment by stanmoore1** [comment] 2019-09-24 21:59
Duplicate of #2214

**Comment by overfelt** [comment] 2019-09-24 22:01
Did not notice #2214

**Closed** 2019-09-24 22:00 UTC
