### ISSUE TITLE
All move constructors and assignment operators in Kokkos should be `noexcept`

### ISSUE THREAD

**Issue by dhollman** [kokkos/kokkos#2240] opened 2019-08-21 16:23 UTC
Almost all of Kokkos should be `noexcept`, but let's break it up into pieces that can be tackled in reasonable-sized issues.  This one is the most urgent.

**Comment by crtrott** [comment] 2019-08-21 17:27
The bug label is for stuff which is broken. I.e. we said this works and it doesn't.

**Comment by dhollman** [comment] 2019-08-22 01:20
Are we claiming that `std::vector<Kokkos::View<...>>` is not guaranteed to work on the CPU? Because that's essentially the issue the user was coming across.  That feels like a bug to me, not an enhancement

**Comment by crtrott** [comment] 2019-08-22 15:41
We never claimed it does work. It never did work. Hence it was the status quo from the beginning of Kokkos and is not a bug. The fact that I cant write `typedef double[][5][] my_array_t` is also not a bug in C++ it is just how it works. And if we want to allow that in C++ its an improvement.

**Comment by khpierson** [comment] 2020-08-16 20:53
Was wondering about this very quetion for SIERRA; stumbled on an article or 2 discussing the issues with performance with stl when move constructors are not marked as noexcept.

http://www.hlsl.co.uk/blog/2017/12/1/c-noexcept-and-move-constructors-effect-on-performance-in-stl-containers

**Comment by masterleinad** [comment] 2022-01-07 22:25
We decided in #3306 that we don't want to mark all move constructors and assignment operators `noexcept`.

**Closed by masterleinad** 2022-01-07 22:25 UTC
Labels: Enhancement
