### ISSUE TITLE
Colons in filenames are invalid characters on Windows

### ISSUE THREAD

**Issue by jwillenbring** [kokkos/kokkos#1675] opened 2018-06-27 19:32 UTC
A large number of files were added to

kokkos/core/src/eti/ROCm

that have "::" in the filename itself. This is invalid on Windows, and is crashing Trilinos Windows testing.

**Comment by crtrott** [comment] 2018-06-27 20:45
duplicate of #1671

**Closed by crtrott** 2018-06-27 20:45 UTC
Labels: duplicate
