### ISSUE TITLE
Should I be concerned with all these warnings?

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#1473] opened 2018-03-15 14:15 UTC
There are lots of cuda warnings on these functions

KOKKOS_INLINE_FUNTION
foo()=default;

listed below, seems like a bad thing

```
e
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/Intrepid2_Orientation.hpp(120): warning: __device__ annotation on a defaulted function("Orientation") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/Intrepid2_Orientation.hpp(120): warning: __host__ annotation on a defaulted function("Orientation") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad_Contiguous.hpp(1000): warning: __device__ annotation on a defaulted function("ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad_Contiguous.hpp(1000): warning: __host__ annotation on a defaulted function("ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad_Contiguous.hpp(1001): warning: __device__ annotation on a defaulted function("operator=") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad_Contiguous.hpp(1001): warning: __host__ annotation on a defaulted function("operator=") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad_Contiguous.hpp(994): warning: __device__ annotation on a defaulted function("~ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad_Contiguous.hpp(994): warning: __host__ annotation on a defaulted function("~ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad_Contiguous.hpp(997): warning: __device__ annotation on a defaulted function("ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad_Contiguous.hpp(997): warning: __host__ annotation on a defaulted function("ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad_Contiguous.hpp(998): warning: __device__ annotation on a defaulted function("operator=") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad_Contiguous.hpp(998): warning: __host__ annotation on a defaulted function("operator=") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad.hpp(1014): warning: __device__ annotation on a defaulted function("~ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad.hpp(1014): warning: __host__ annotation on a defaulted function("~ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad.hpp(1017): warning: __device__ annotation on a defaulted function("ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad.hpp(1017): warning: __host__ annotation on a defaulted function("ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad.hpp(1018): warning: __device__ annotation on a defaulted function("operator=") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad.hpp(1018): warning: __host__ annotation on a defaulted function("operator=") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad.hpp(1020): warning: __device__ annotation on a defaulted function("ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad.hpp(1020): warning: __host__ annotation on a defaulted function("ViewMapping") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad.hpp(1021): warning: __device__ annotation on a defaulted function("operator=") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/KokkosExp_View_Fad.hpp(1021): warning: __host__ annotation on a defaulted function("operator=") is ignored

```

**Comment by bathmatt** [comment] 2018-03-15 14:15
@kyungjoo-kim  adding you to this as well

**Comment by bathmatt** [comment] 2018-03-15 14:16
@rppawlo some for you..

/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/Phalanx_DeviceEvaluator.hpp(15): warning: __device__ annotation on a defaulted function("~DeviceEvaluator") is ignored
/home/mbetten/installs/install-for-panzer/cuda-RELEASE-STATIC/include/Phalanx_DeviceEvaluator.hpp(15): warning: __host__ annotation on a defaulted function("~DeviceEvaluator") is ignored

**Comment by rppawlo** [comment] 2018-03-15 14:24
@bathmatt - is this with cuda 9.0 or is it reproducible in 8.0?
adding @etphipp  for sacado objects

**Comment by mhoemmen** [comment] 2018-03-15 14:36
Is this related to https://github.com/kokkos/kokkos/issues/1470 ?

**Comment by ibaned** [comment] 2018-03-15 15:24
@mhoemmen it is. I assume the special Sacado View objects have defaulted constructors, which are currently still marked with `KOKKOS_INLINE_FUNCTION`. That marking causes compiler warnings but gives correct behavior. We tried to create a `KOKKOS_INLINE_FUNCTION_DEFAULTED` to avoid the warnings, but it turns out NVIDIA's compiler is broken and the not-warning version actually crashes. So, the only answer I've been able to come up with is to not use defaulted members, rather define the constructors etc. explicitly. https://github.com/kokkos/kokkos/pull/1471 will fix this in Kokkos, but that fix needs to be propagated to the Kokkos copy in Trilinos and to Sacado.

**Comment by etphipp** [comment] 2018-03-15 15:39
Replacing defaulted functions with their default implementations does not seem like the right solution to me.  Doing so can have implications for compiler optimization.  For example, adding an implementation of a defaulted function, even if it is identical to the default implementation, will make is_pod<>::value for that type false.  

I've already removed some usage of KOKKOS_INLINE_FUNCTION in Sacado (although not the ones referenced here) to eliminate warnings that Sparc was seeing since it didn't seem to have any negative consequences, but apparently that wasn't the right thing to do.

Note that you can disable individual warnings with nvcc by adding to your CXX_FLAGS -Xcudafe "--diag_suppress=token" where "token" is a token for the individual error.  There is an older list of such tokens here:

http://www.ssl.berkeley.edu/~jimm/grizzly_docs/SSL/opt/intel/cc/9.0/lib/locale/en_US/mcpcom.msg

however it hasn't been updated for recent versions of Cuda (this particular warning is not in the list).  Perhaps someone can ask Nvidia what the token is to disable this particular warning until the whole issue is resolved by Nvidia?

And to answer Roger's question, this is a new warning that appeared with Cuda 9.

**Comment by ibaned** [comment] 2018-03-15 15:41
@crtrott

**Comment by etphipp** [comment] 2018-03-15 16:22
Here's an example of what I mean:
```
#include <iostream>
#include <type_traits>

struct Foo {
  Foo() = default;
};

struct Bar {
  Bar() {}
};

int main() {
  std::cout << std::is_pod<Foo>::value << std::endl;
  std::cout << std::is_pod<Bar>::value << std::endl;
  return 0;
}
```
Compiling this with GCC 4.9 and running it results in the output:
```
etphipp@elbert c++ $ g++-4.9 -std=c++11 -o pod_default_test pod_default_test.cpp 
etphipp@elbert c++ $ ./pod_default_test 
1
0
```
I realize this isn't so much an issue for Kokkos View's, but it does matter for Sacado objects.

**Comment by ibaned** [comment] 2018-03-15 16:27
@etphipp I'm doing a thorough search for the right diagnostic suppression token, but not having much luck. Do you have an example that shows actual serious performance impacts (or worse) of making this change?

**Comment by ibaned** [comment] 2018-03-15 16:35
@etphipp Good news! I found the new token:
```
-Xcudafe --diag_suppress=esa_on_defaulted_function_ignored
```
Right now we're pursuing custom implementations in Kokkos, but we may do a two-front approach where we also try to introduce this flag automatically somewhere in the build system, or in `nvcc_wrapper` itself.

**Comment by etphipp** [comment] 2018-03-15 16:50
Great!  Might I ask how you found that?  There are other red-herring NVCC warnings that I would like to be able to suppress that weren't in the list I posted earlier.

I'm not sure what I want to do with Sacado.  I don't have evidence the replacing defaulted functions with their default implementations actually reduces performance.  On the other hand, I don't like changing the code just because NVCC doesn't handle it correctly (assuming Nvidia agrees this is a bug and is willing to fix it eventually).

**Comment by ibaned** [comment] 2018-03-15 16:58
We're planning to introduce the macro `KOKKOS_CUDA_9_DEFAULTED_BUG_WORKAROUND` in Kokkos, so one option would be put code in Sacado that does manual implementations only if that macro is defined, else use `= default;` (that's what we'll do in Kokkos). Or we can just rely on some part of the build system suppressing these warnings and just carry on as-is.

**Comment by ibaned** [comment] 2018-03-21 13:53
All the Kokkos changes I discussed are in Kokkos develop and Trilinos develop.

**Closed** 2018-03-21 17:33 UTC
Labels: question

**Comment by bartgol** [comment] 2019-05-02 21:42
@ibaned  This issue seems to be back in `Kokkos_Crs.hpp`:

`Kokkos_Crs.hpp(109): warning: __device__ annotation on a defaulted function("operator=") is ignored`

Some detail:
- nvcc version:  9.1.85
- kokkos version: current develop (da7428a)
- cmake 3.9.6

**Comment by ibaned** [comment] 2019-05-02 21:48
@bartgol that is a bug in the CUDA compiler:

1. If you say `__host__ __device__ foo() = default;` then it prints this warning, claiming that `__device__` is ignored, which is a lie because:
2. If you say `foo() = default`, then it only generates the host one and when you try to call it on the device it will crash.
3. If you don't use `= default` then you break C++ type checks like `std::is_trivially constructible`.

Basically, the compiler is actually not doing at all what the warning says and the warning is just plain wrong. That is why in the Kokkos build system we introduce a flag to silence this warning: 
```cpp
Makefile.kokkos:620:      KOKKOS_CXXFLAGS += -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored
```
So really the issue here is you must be using a build system that isn't getting this flag from Kokkos' build system.
Finally, its better to open a new issue than to comment on a closed one.
