### ISSUE TITLE
Pick device at random feature

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#2254] opened 2019-08-28 13:34 UTC
https://github.com/trilinos/Trilinos/pull/5799

I created a patch for Kokkos in Trilinos.  See above.  It selects a device at random between [0,KOKKOS_RAND_DEVICES).  This is to help LB ctest runs.

**Comment by crtrott** [comment] 2019-08-29 15:01
@dhollman yes we can more or less reliably get the number of devices. I am actually not sure why we don't do that by default. Also what @bathmatt asks is not within a single process. Each process only gets one GPU. The problem is oversubscribed testing. Say you run 16 test processes at the same time with a mix of different MPI rank numbers (some are 4 ranks, many are 1 rank). How do you get a reasonable distribution of processes per GPU.

**Comment by dhollman** [comment] 2019-08-29 18:00
In that case, you do something deterministic, or if you really need random behavior, do your deterministic mapping and do a random shuffle with the same seed on each process.  But otherwise I don't see how what you're talking about relates to selecting a device at random.

**Comment by crtrott** [comment] 2019-08-29 21:52
No the problem is that I don't know how long each of these processes runs etc. Say you allow 4x oversubscription to enable 16 concurrent processes on a node with 4 GPUs, but you got in total 150 processes with some distribution of 1-rank, 2-rank, 3-rank and 4-rank jobs. From within each job you can't figure out which GPU has the fewest processes using it already. If you just go by rank-id, you may have 16 single rank processes crowding on GPU 0, while the other 3 are empty. The idea behind random assignment is that, sure you would get sometimes 5 or 6 processes on a single GPU, but 16,0,0,0 as the distribution is highly unlikely.

**Comment by bathmatt** [comment] 2019-08-31 14:30
I've got a PR on trilinos, I tagged @crtrott 

As for the number of devices, I've set it up so you setenv KOKKOS_RAND_DEVICES=NDEVICES, just like the num_devices env var

**Comment by bathmatt** [comment] 2019-09-03 19:51
If there is no issues with this code, i.e., not going to make new bugs, can we merge it into trilinos and then discuss how it should go in, if at all, into kokkos and then we can erase our sins when you snapshot a new version in??

**Comment by crtrott** [comment] 2019-09-03 20:21
Yeah we can do this. I think this option is harmless enough that it shouldn't be too bad. We just need to set up a test to make sure this actually works. One option might be to name this: KOKKOS_EXPERIMENTAL_RAND_DEVICES to denote it as an untested / inofficial capability. It is unlikely anybody would break it, but we would rely on you to tell us if we did ...

**Comment by bathmatt** [comment] 2019-09-03 20:40
OK, I tested this with our testing on vortex.  Ran cutest -j8 and nvidia-s
I and see all sorts of random configs.

**Comment by masterleinad** [comment] 2019-10-22 22:20
Let's discuss if we want this in the release or not.

**Comment by ndellingwood** [comment] 2019-10-25 15:34
Addressed by @masterleinad in #2498

**Closed** 2019-12-20 23:46 UTC
Labels: Feature Request, InDevelop, question
