### ISSUE TITLE
fatal error: Cuda/Kokkos_Cuda_abort.hpp: No such file or directory

### ISSUE THREAD

**Issue by ambrad** [kokkos/kokkos#157] opened 2015-12-10 01:06 UTC
I may be building the standalone Kokkos library incorrectly; apologies if this is user error. In any case, when I don't build --with-cuda, in my app I get this compiler error:

/include/impl/Kokkos_Error.hpp:49:38: fatal error: Cuda/Kokkos_Cuda_abort.hpp: No such file or directory

An example Kokkos build that gives this error is this one:

./generate_makefile.bash --with-openmp --with-serial --compiler=g++-4.7 --with-options=aggressive_vectorization --prefix=/home/ambradl/lib/kokkos/cpu

Thanks.

**Comment by crtrott** [comment] 2015-12-10 04:57
Ah I see the issue. It was introduced on 11/12, and is caused by a missing guard. That doesn't hurt in the case of an embedded build (where all the header files, including unused execution spaces are always available), but it doesn't work for the actual TPL install, since that only installs files for the existing execution spaces. I'll fix it tomorrow and get it into the develop branch.

**Comment by crtrott** [comment] 2015-12-10 16:36
I pushed a fix to develop. Please let me know if it works for you (if you can work of the develop branch from kokkos). It will take a couple days to get it to Trilinos, since I have to run an integration cycle.

**Comment by ambrad** [comment] 2015-12-10 16:46
Yes, it works. Thanks.

**Comment by crtrott** [comment] 2015-12-10 16:46
Reopening until we got it in master.

**Comment by crtrott** [comment] 2015-12-10 16:47
And thanks for confirming so fast :+1:

**Comment by crtrott** [comment] 2015-12-11 08:17
Pushed to master

**Closed by crtrott** 2015-12-11 08:17 UTC
Labels: bug, bug - fix pushed to develop branch, InDevelop
