### ISSUE TITLE
Is it possible to get the number of team members/thread about outside parallel_for?

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#1457] opened 2018-03-02 19:15 UTC
It will be great if I can ask the number of Kokkos threads/team members (or something equivalent)  in the current scope. Is there any API for that?

**Comment by mhoemmen** [comment] 2018-03-02 20:51
Do you mean the amount of hardware concurrency, or the integer range that you gave to parallel_for?

**Comment by crtrott** [comment] 2018-03-03 03:27
If you mean the number of threads participating inside Hierarchical Parallelism:
```c++
void operator() (const TeamPolicy<>::member_type& team) const {
  int n = team.team_size();
}
```

You can not ask for the number of currently concurrently running things outside of the team scope. And that is by design because it would open up to much space for non-portable code, and it would also make it really easy to break Kokkos's semantics for its parallel patterns. You can ask for the maximum amount of concurrency for a given execution space though:
```c++
Kokkos::DefaultExecutionSpace::concurrency();
```
Each Execution Space has that function.

**Comment by crtrott** [comment] 2018-03-09 06:43
Closing the issue assuming it answered your question. If not feel free to reopen.

**Closed by crtrott** 2018-03-09 06:43 UTC
Labels: question
