### ISSUE TITLE
KOKKOS_RESTRICT...

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#2038] opened 2019-03-18 16:08 UTC
Why do we KOKKOS_RESTRICT is defined for Intel architectures ? NVCC suppports the ``__restrict__`` keyword, too.

**Comment by kyungjoo-kim** [comment] 2019-03-19 23:01
@crtrott Can we add the ``#define KOKKOS_RESTRICT __restrict__`` keyword if a compiler does not complain about it ? 

@lucbv , put your hands up if u like this !!

**Comment by mhoemmen** [comment] 2019-03-19 23:26
We would need to add a CMake test for this, but it's not hard:
```
INCLUDE(CheckCXXSourceCompiles)

FUNCTION(CHECK_RESTRICT_COMPILES VARNAME)
  SET(SOURCE
  "
#define KOKKOS_RESTRICT_LOCAL __restrict__

double test_restrict (const double* KOKKOS_RESTRICT_LOCAL x, const int N) {
  double sum = 0.0;
  for (int i = 0; i < N; ++i) {
    sum += x[i];
  }
  return sum;
}

int main() {
  constexpr int N = 10;
  const double arr[] = { 1.0, 2.0, 3.0, 4.0, 5.0 };
  const double sum = test_restrict (arr, N);
  return sum == 15.0 ? 0 : -1; 
}
  "
  )
  
  # This is a local variable name.  ${VARNAME} is the output variable.
  CHECK_CXX_SOURCE_COMPILES("${SOURCE}" KOKKOS_ENABLE_RESTRICT_LOCAL)

  IF(KOKKOS_ENABLE_RESTRICT_LOCAL)
    GLOBAL_SET(${VARNAME} TRUE)
    MESSAGE(STATUS "C++ compiler supports __restrict__")
  ELSE()
    GLOBAL_SET(${VARNAME} FALSE)
    MESSAGE(STATUS "C++ compiler does NOT support __restrict__")
  ENDIF()
ENDFUNCTION()
```

**Comment by lucbv** [comment] 2019-03-19 23:33
@kyungjoo-kim thanks for adding this issue, I am in favor of allowing restrict in kokkos/kokkos-kernels. It is often useful for vectorization.
Also it would be nice to have this type of macro being maintained for GNU compiler, not only intel...

**Comment by mhoemmen** [comment] 2019-03-19 23:39
@lucbv The above CMake test should work fine for any compiler.

**Comment by nmhamster** [comment] 2019-03-19 23:56
You need to check which restrict is supported and if flags are needed to enable it. If memory serves, the compilers don’t all agree on how this is written.

**Comment by mhoemmen** [comment] 2019-03-20 05:06
@nmhamster I don't know how to do that in Kokkos' raw Makefiles-based build system, but the above CMake test could be modified easily enough to cover variations on `__restrict__`.

**Comment by kyungjoo-kim** [comment] 2019-03-20 17:01
When I have this kind of problem (cmake can test certain compiler options while makefile cannot do so), I just give a overriding option to users in the makefile configuration. Mostly, when people use makefile, we generally assume that those users know what they are doing.

**Comment by ibaned** [comment] 2019-03-20 18:24
This is a duplicate of #1922, I'm going to close this one since it came later but we do want to start defining `KOKKOS_RESTRICT` for non-Intel compilers. Exactly how we do this may still be up for debate.

**Closed by ibaned** 2019-03-20 18:24 UTC
