### ISSUE TITLE
openmp.UnorderedMap_insert test fails on aarch64 rhel8

### ISSUE THREAD

**Issue by junghans** [kokkos/kokkos#2354] opened 2019-09-19 00:54 UTC
```
[ RUN      ] openmp.UnorderedMap_insert
/builddir/build/BUILD/kokkos-d93e239baee253fca66b8b7f2196edaa40a2ef17/containers/unit_tests/TestUnorderedMap.hpp:209: Failure
Value of: map_size
  Actual: 901
Expected: expected_inserts
Which is: 900
/builddir/build/BUILD/kokkos-d93e239baee253fca66b8b7f2196edaa40a2ef17/containers/unit_tests/TestUnorderedMap.hpp:224: Failure
Value of: map.size()
  Actual: 1
Expected: 0u
Which is: 0
[  FAILED  ] openmp.UnorderedMap_insert (4150 ms)
```

From https://koji.fedoraproject.org/koji/taskinfo?taskID=37726619 details 
[here](https://github.com/kokkos/kokkos/files/3628880/build_aarch64.log.txt)

**Comment by PhilMiller** [comment] 2022-12-22 19:09
Attempted to reproduce this on SNL's 'stria' aarch64 system with Kokkos 3.7.00 and GCC 7.2.0. Hundreds of iterations of the test ran successfully on 4 and 16 threads, with and without contention for the cores. So, while we have many known race conditions in the OpenMP and Threads backends, I'm closing this as no longer reproducible.

Whatever the root cause is/was will probably eventually get addressed as part of #4322

**Closed by PhilMiller** 2022-12-22 19:09 UTC
Labels: Bug
