### ISSUE TITLE
building with nvcc and clang (or clang based XL) as host compiler: "Kokkos::atomic_fetch_min(volatile int *, int)" has already been defined

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2903] opened 2020-03-23 19:27 UTC
Compilation error:
```
13:19:07 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_xl_161_kepler/kokkos/core/src/impl/Kokkos_Atomic_MinMax.hpp(104): error: function "Kokkos::atomic_fetch_min(volatile int *, int)" has already been defined
```

Reproducer sample:
```
   #   Load modules:
         module load cmake/3.12.3 cuda/9.2.88 gcc/7.2.0 ibm/xl/16.1.1

   #   Use generate_makefile line below to call cmake which generates makefile for this build:

         <KOKKOS_PATH>/generate_makefile.bash --with-devices=Cuda,OpenMP --arch=Power8,Kepler37 --compiler=<KOKKOS_PATH>/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -ccbin xlc++" --cxxstandard="11" --ldflags="" --with-cuda --kokkos-path=<KOKKOS_PATH> --no-examples --with-options=enable_large_mem_tests
```

**Comment by crtrott** [comment] 2020-03-23 22:21
Fix is in #2904

**Comment by ndellingwood** [comment] 2020-03-24 16:26
@crtrott the fix from #2904 now allows the failing build to compile, but the `openmp.Random_XorShift64` test has now failed two consecutive rounds of testing (very unlikely to occur), should a new issue be opened for that?

https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/809/display/redirect

https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/810/display/redirect

**Comment by crtrott** [comment] 2020-03-24 23:43
Yeah I am looking into those as well as a segfault ...

**Comment by masterleinad** [comment] 2020-04-02 21:15
Hmm.. Can't reproduce on `Summit`.

**Closed** 2020-04-14 21:38 UTC
Labels: DevelopOnly, InDevelop, bug
