### ISSUE TITLE
[question] task scheduler constructor

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#770] opened 2017-05-04 16:58 UTC
@hcedwar 

The constructor of task scheduler has three arguments.
```
template<exec_space>
TaskScheduler( memory_space, memory_pool_capacity, memory_pool_log2_superblock = 12);
```

- memory_space : naturally mapped to device space what ever is given as execution space. Can I use other memory space (such as fast memory space) here ? any reason that we need this memory space arguments ?

- memory_pool_capacity : I confuse about this. previously this is the memory pool size for task queue. is this capacity still approximates the number of tasks generated ? (or do I need to include shared memory space that can be allocated in tasks ?) 

- if the memory pool capacity is for task queue, I think that this memory pool should be resizable and automatically grow when it is necessary. without growable memory pool for task queue, the code is not robust and robustness is more important than scalability.

- memory_pool_log2_superblock : I guess that this is the memory pool allocator block size.  

- do I need to pass separate memory pool to allocate temporal memory used in tasks ? or attach it to task scheduler (or use embeded in the task scheduler) ?

**Comment by hcedwar** [comment] 2017-05-04 18:02
1. for now just use
```c++
TaskScheduler t( TaskScheduler::memory_space() , ... )
```

1. within the GPU cannot do a new allocation to increase the capacity - functionality does not exist.  For device portability if the memory pool size estimate is too small then must resize from the host side and re-run the algorithm.

1. the TaskScheduler and MemoryPool in the develop branch has revised the memory pool tuning parameters to be ordinary sizes - not power of two values.

**Comment by kyungjoo-kim** [comment] 2017-05-04 19:29
Yeah.... I am going to do what I can do algorithmically but the scheduler may need to prepare for the worst case (slow but the code should be finished somehow).  

Another problem.


```
              const size_type alloc_size = isize*sizeof(future_type);
              future_type *dep = (future_type*)_pool.allocate(alloc_size);

              for (ordinal_type i=0;i<isize;++i) {
                const ordinal_type child = _info.stree_children(i+ibeg);
                future_type f = Kokkos::task_spawn(Kokkos::TaskSingle(_sched, i ? Kokkos::TaskPriority::Low : Kokkos::TaskPriority::High),
                                                   TaskFunctor_CholeskySuperNodes(_sched, _pool, _info,
                                                                                  child, _sid));
                dep[i] = f;
              }
              future_type dep_all = Kokkos::when_all(dep, isize);
              ++_state;
              printf("this task is respawned\n");
              Kokkos::respawn(this, dep_all, Kokkos::TaskPriority::High);
              _pool.deallocate((void*)dep, alloc_size);
```

**Comment by kyungjoo-kim** [comment] 2017-05-04 19:36
BTW, I use develop branch. It seems that task-dag branch is merged into there.

**Comment by kyungjoo-kim** [comment] 2017-05-04 19:43
I just realized that the host space may be Serial. Is this wrong ? or this use case is acceptable ?

**Comment by hcedwar** [comment] 2017-05-04 23:24
The problem is the 'when_all' returns a Future with `void` value type.  So you need to:
```c++
auto dep_all = Kokkos::when_all(dep, isize);
Kokkos::respawn(this, dep_all, Kokkos::TaskPriority::High);
```
or even:
```c++
Kokkos::respawn(this, Kokkos::when_all(dep, isize), Kokkos::TaskPriority::High);
```

**Comment by kyungjoo-kim** [comment] 2017-05-05 03:46
@hcedwar 

How can I spawn task with a depedence ? 
```
auto f0 =  Kokkos::host_spawn(Kokkos::TaskSingle(sched), functor(args));
auto f1 = Kokkos::host_spawn(Kokkos::TaskSingle(sched), functor(args), f0);
```
This syntax is no long avail and I could not find out any example from unit test that actaully spawns a task with a dependence. All examples are respawn with depedence.

**Comment by kyungjoo-kim** [comment] 2017-05-05 03:57
ummmm...

```
  auto f_allocate = Kokkos::host_spawn(Kokkos::TaskSingle(sched),                                                     
                                       functor_allocate(pool, bufsize));                                              
  auto f_deallocate = Kokkos::host_spawn(Kokkos::TaskSingle(f_allocate),                                              
                                         functor_deallocate(pool, bufsize, f_allocate));     
```
I tried this as seen in the code but it is not working.

**Comment by kyungjoo-kim** [comment] 2017-05-05 07:03
Thank you @hcedwar 

when_all mystery is resolved. Sorry for my not being careful enough.

The problem of spawning a task with dependence is still mystery. For your information, the error message is as follows:
```
/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/Kokkos_TaskScheduler.hpp(717): error: no instance of constructor "Kokkos::Impl::TaskPolicyData<TaskEnum, DepFutureType>::TaskPolicyData [with TaskEnum=1, DepFutureType=Kokkos::Future<Kokkos::Serial, void>]" matches the argument list
            argument types are: (const Kokkos::Future<Kokkos::Serial, void>, const Kokkos::TaskPriority)
      Kokkos::Impl::TaskPolicyData
      ^
          detected during instantiation of "Kokkos::Impl::TaskPolicyData<1, std::conditional<Kokkos::is_future<T, void>::value, T, Kokkos::Future<T::execution_space, void>>::type> Kokkos::TaskSingle(const T &, const Kokkos::TaskPriority &) [with T=Kokkos::Future<Kokkos::Serial, void>]" at line 59 of "/home/kyukim/Work/lib/trilinos/trunk/packages/shylu/tacho/refactor/unit-test/Tacho_TestTaskFunctor.hpp"
```
I found that constructor from Kokkos but somehow it does not see it.

**Comment by hcedwar** [comment] 2017-05-05 19:51
This is a bug, fix and new unit test in progress.

**Comment by kyungjoo-kim** [comment] 2017-05-05 23:44
IMHO, That still has a bug.

```
  template< class Space>
  struct TestTaskSpawnKJ {
    typedef Kokkos::TaskScheduler< Space >  sched_type;
    typedef Kokkos::Future<void*, Space >     future_type;
    typedef void*                             value_type;

    KOKKOS_INLINE_FUNCTION
    TestTaskSpawnKJ() {}

    KOKKOS_INLINE_FUNCTION
    void operator()( typename sched_type::member_type &, value_type (&r_val) )
    {
      r_val = NULL;
      printf("TaskSpawnKJ executing\n");
    }

  };

template< class Space >
struct TestTaskSpawn {
  typedef Kokkos::TaskScheduler< Space >  sched_type;
  typedef Kokkos::Future< Space >         future_type;
  typedef void                            value_type;
  typedef Kokkos::Future< int, Space >    future_int_type;

  sched_type   m_sched ;
  future_int_type  m_future ;

  KOKKOS_INLINE_FUNCTION
  TestTaskSpawn( const sched_type & arg_sched
               , const future_int_type & arg_future
               )
    : m_sched( arg_sched )
    , m_future( arg_future )
    {}

  KOKKOS_INLINE_FUNCTION
  void operator()( typename sched_type::member_type & )
  {
    printf("TaskSpawn is executing\n");
  }

  static void run()
  {
    typedef typename sched_type::memory_space memory_space;

    // enum { MemoryCapacity = 4000 }; // Triggers infinite loop in memory pool.
    enum { MemoryCapacity = 16000 };
    enum { MinBlockSize   =   64 };
    enum { MaxBlockSize   = 1024 };
    enum { SuperBlockSize = 1u << 12 };

    sched_type sched( memory_space()
                    , MemoryCapacity
                    , MinBlockSize
                    , MaxBlockSize
                    , SuperBlockSize );

    auto f = Kokkos::host_spawn( Kokkos::TaskSingle( sched ), TestTaskSpawnKJ<Space>() );
    Kokkos::host_spawn( Kokkos::TaskSingle( f ), TestTaskSpawn( sched, f ) );

    Kokkos::wait( sched );
  }
};
```

This is a small modification of your unit test where two future are different types included.
Compiler error follows.
```
[ 63%] Building CXX object packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_OpenMP.dir/openmp/TestOpenMP_Other.cpp.o
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/Kokkos_TaskScheduler.hpp(247): error: static assertion failed with "Assigned Futures must have the same value_type"
        static_assert
        ^
          detected during:
            instantiation of "Kokkos::Future<Arg1, Arg2>::Future(const Kokkos::Future<A1, A2> &) [with Arg1=int, Arg2=Kokkos::OpenMP, A1=void *, A2=Kokkos::OpenMP]" at line 238 of "/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/unit_test/TestTaskScheduler.hpp"
            instantiation of "void TestTaskScheduler::TestTaskSpawn<Space>::run() [with Space=Kokkos::OpenMP]" at line 144 of "/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/unit_test/openmp/TestOpenMP_Other.cpp"

/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/impl/Kokkos_TaskQueue.hpp(228): error: a value of type "Kokkos::Impl::TaskBase<Kokkos::DefaultExecutionSpace, void *, void> *" cannot be assigned to an entity of type "task_lhs *"
        *static_cast< task_lhs * volatile * >(lhs) = rhs ;
                                                   ^
          detected during:
            instantiation of "void Kokkos::Impl::TaskQueue<ExecSpace>::assign(Kokkos::Impl::TaskBase<ExecSpace, LV, void> **, Kokkos::Impl::TaskBase<ExecSpace, RV, void> *) [with ExecSpace=Kokkos::OpenMP, LV=int, RV=void *]" at line 252 of "/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/Kokkos_TaskScheduler.hpp"
            instantiation of "Kokkos::Future<Arg1, Arg2>::Future(const Kokkos::Future<A1, A2> &) [with Arg1=int, Arg2=Kokkos::OpenMP, A1=void *, A2=Kokkos::OpenMP]" at line 238 of "/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/unit_test/TestTaskScheduler.hpp"
            instantiation of "void TestTaskScheduler::TestTaskSpawn<Space>::run() [with Space=Kokkos::OpenMP]" at line 144 of "/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/unit_test/openmp/TestOpenMP_Other.cpp"

compilation aborted for /home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/unit_test/openmp/TestOpenMP_Other.cpp (code 2)
make[2]: *** [packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_OpenMP.dir/openmp/TestOpenMP_Other.cpp.o] Error 2
make[1]: *** [packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_OpenMP.dir/all] Error 2
```

**Comment by hcedwar** [comment] 2017-05-08 17:46
The TestTaskSpawn constructor takes a Future<int,space> and you are passing Future<void*,space>.  These are not compatible types.

Sent from my iPad

On May 5, 2017, at 5:44 PM, kyungjoo-kim <notifications@github.com<mailto:notifications@github.com>> wrote:


IMHO, That still has a bug.

  template< class Space>
  struct TestTaskSpawnKJ {
    typedef Kokkos::TaskScheduler< Space >  sched_type;
    typedef Kokkos::Future<void*, Space >     future_type;
    typedef void*                             value_type;

    KOKKOS_INLINE_FUNCTION
    TestTaskSpawnKJ() {}

    KOKKOS_INLINE_FUNCTION
    void operator()( typename sched_type::member_type &, value_type (&r_val) )
    {
      r_val = NULL;
      printf("TaskSpawnKJ executing\n");
    }

  };

template< class Space >
struct TestTaskSpawn {
  typedef Kokkos::TaskScheduler< Space >  sched_type;
  typedef Kokkos::Future< Space >         future_type;
  typedef void                            value_type;
  typedef Kokkos::Future< int, Space >    future_int_type;

  sched_type   m_sched ;
  future_int_type  m_future ;

  KOKKOS_INLINE_FUNCTION
  TestTaskSpawn( const sched_type & arg_sched
               , const future_int_type & arg_future
               )
    : m_sched( arg_sched )
    , m_future( arg_future )
    {}

  KOKKOS_INLINE_FUNCTION
  void operator()( typename sched_type::member_type & )
  {
    printf("TaskSpawn is executing\n");
  }

  static void run()
  {
    typedef typename sched_type::memory_space memory_space;

    // enum { MemoryCapacity = 4000 }; // Triggers infinite loop in memory pool.
    enum { MemoryCapacity = 16000 };
    enum { MinBlockSize   =   64 };
    enum { MaxBlockSize   = 1024 };
    enum { SuperBlockSize = 1u << 12 };

    sched_type sched( memory_space()
                    , MemoryCapacity
                    , MinBlockSize
                    , MaxBlockSize
                    , SuperBlockSize );

    auto f = Kokkos::host_spawn( Kokkos::TaskSingle( sched ), TestTaskSpawnKJ<Space>() );
    Kokkos::host_spawn( Kokkos::TaskSingle( f ), TestTaskSpawn( sched, f ) );

    Kokkos::wait( sched );
  }
};


This is a small modification of your unit test where two future are different types included.
Compiler error follows.

[ 63%] Building CXX object packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_OpenMP.dir/openmp/TestOpenMP_Other.cpp.o
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/Kokkos_TaskScheduler.hpp(247): error: static assertion failed with "Assigned Futures must have the same value_type"
        static_assert
        ^
          detected during:
            instantiation of "Kokkos::Future<Arg1, Arg2>::Future(const Kokkos::Future<A1, A2> &) [with Arg1=int, Arg2=Kokkos::OpenMP, A1=void *, A2=Kokkos::OpenMP]" at line 238 of "/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/unit_test/TestTaskScheduler.hpp"
            instantiation of "void TestTaskScheduler::TestTaskSpawn<Space>::run() [with Space=Kokkos::OpenMP]" at line 144 of "/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/unit_test/openmp/TestOpenMP_Other.cpp"

/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/impl/Kokkos_TaskQueue.hpp(228): error: a value of type "Kokkos::Impl::TaskBase<Kokkos::DefaultExecutionSpace, void *, void> *" cannot be assigned to an entity of type "task_lhs *"
        *static_cast< task_lhs * volatile * >(lhs) = rhs ;
                                                   ^
          detected during:
            instantiation of "void Kokkos::Impl::TaskQueue<ExecSpace>::assign(Kokkos::Impl::TaskBase<ExecSpace, LV, void> **, Kokkos::Impl::TaskBase<ExecSpace, RV, void> *) [with ExecSpace=Kokkos::OpenMP, LV=int, RV=void *]" at line 252 of "/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/Kokkos_TaskScheduler.hpp"
            instantiation of "Kokkos::Future<Arg1, Arg2>::Future(const Kokkos::Future<A1, A2> &) [with Arg1=int, Arg2=Kokkos::OpenMP, A1=void *, A2=Kokkos::OpenMP]" at line 238 of "/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/unit_test/TestTaskScheduler.hpp"
            instantiation of "void TestTaskScheduler::TestTaskSpawn<Space>::run() [with Space=Kokkos::OpenMP]" at line 144 of "/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/unit_test/openmp/TestOpenMP_Other.cpp"

compilation aborted for /home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/unit_test/openmp/TestOpenMP_Other.cpp (code 2)
make[2]: *** [packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_OpenMP.dir/openmp/TestOpenMP_Other.cpp.o] Error 2
make[1]: *** [packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_OpenMP.dir/all] Error 2


-

**Closed** 2017-05-27 16:18 UTC
Labels: bug, bug - fix pushed to develop branch, InDevelop, question
