### ISSUE TITLE
Error when switching to P100

### ISSUE THREAD

**Issue by ArVictor** [kokkos/kokkos#1686] opened 2018-07-05 15:12 UTC
I developed a code on a machine with a K40m GPU (CC Kepler 3.5). Everything runs perfectly.
After switching to a P100 (Pascal 6.0), I got an illegal memory access. I found that this occurs when I use a View of a class.
I tried to make a reproducer containing just the View of class. But I did not reproduce the exact same error. This code gives me "Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized" on both machines... (commenting out View<test*> removes the error)

```C++
class test {
  public :
  int a;
  test() {a = 0;};
};

int main(int argc, char *argv[]) {
  Kokkos::initialize (argc, argv);  //Just to make sure it compiles with Kokkos

  //WORKS
  Kokkos::View<double[3]> xyz("xyz");
  auto xyz_host = Kokkos::create_mirror_view(xyz);
  xyz_host(0) = 2;
  Kokkos::deep_copy(xyz, xyz_host);
  Kokkos::parallel_for(1, KOKKOS_LAMBDA (const int i) {
    printf("%lf\n", xyz(0));
    #ifdef __CUDA_ARCH__
      printf("CUDA\n");
    #else
      printf("CPU");
    #endif
  });

  Kokkos::View<test*> t("t", 1);  //ERROR

  Kokkos::finalize ();
  return 0;
}
```

Output:

```
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
2.000000
CUDA
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
```
Is there any known issue regarding Views of class and/or Pascal architecture?

**Comment by mhoemmen** [comment] 2018-07-05 15:17
How did you set `KOKKOS_ARCH`?

**Comment by mhoemmen** [comment] 2018-07-05 15:18
Also, you should not create `Kokkos::View` instances at `main` scope, since their destructors will be called after `Kokkos::finalize` has been called.

**Comment by ArVictor** [comment] 2018-07-05 15:25
I have KOKKOS_ARCH = "Power8, Pascal60" for the P100 and "SNB, Kepler35" on the K40m.

Ok, I have wrapped the example in my first message in a function, and it removes the error.
In the "real" code, the View of class is a member of another class.

**Comment by ArVictor** [comment] 2018-07-05 15:41
So in the real case, I have this error
```========= CUDA-MEMCHECK
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
******************Kokkos******************
========= Program hit cudaErrorLaunchFailure (error 4) due to "unspecified launch failure" on CUDA API call to cudaDeviceSynchronize. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib64/libcuda.so.1 [0x374b3c]
=========     Host Frame:/usr/local/cuda-9.1/lib64/libcudart.so.9.1 (cudaDeviceSynchronize + 0x19c) [0x3f2ac]
=========     Host Frame:./main.cuda [0x4c0a8]
=========     Host Frame:./main.cuda [0x12718]
=========     Host Frame:./main.cuda [0x2f8ac]
=========     Host Frame:./main.cuda [0x4bd4]
=========     Host Frame:/usr/lib64/libc.so.6 [0x24980]
=========     Host Frame:/usr/lib64/libc.so.6 (__libc_start_main + 0xc4) [0x24b74]
=========
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorLaunchFailure): unspecified launch failure /home/varti/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119
Traceback functionality not available

========= Error: process didn't terminate successfully
========= No CUDA-MEMCHECK results found
```
and returning before the following line removes the issue
```
this->view_group = Kokkos::View<particle_group_base*>("view_group", 1);

**Comment by mhoemmen** [comment] 2018-07-05 15:47
1. Does that line of code occur inside of a `Kokkos::parallel_*`?
2. Does `particle_group_base` have a nontrivial constructor or destructor?  Does it try to allocate memory?

**Comment by ArVictor** [comment] 2018-07-05 15:52
1. No, this line is inside a class constructor.
2. It has an empty constructor `` particle_group_base(){};`` and a second constructor ``particle_group_base(string, long, bool);`` which allocates memory (standard C++ array) and initializes Views.

**Comment by mhoemmen** [comment] 2018-07-05 16:10
See https://github.com/kokkos/kokkos/issues/1591 , which is about a similar issue.  The problem is that the outer View allocation requires invoking Kokkos::View constructors.

Best practice in this case would be the following:
  1. Make the outer View have memory space CudaUVMSpace.
  2. Allocate the outer View without initializing.
  3. Fence (so host sees the UVM allocation).
  4. For all struct instances in the outer View, invoke their constructor on host, in a sequential or host-thread-parallel loop, using placement new.  (If the "standard C++ array" is dynamically allocated, it had better be a device or UVM allocation, if you intend to access it on device.)
  5. Fence again (so device can see the changes to the UVM allocation).

Now you have structs with valid Views inside.  Once you're done with the outer View, you'll need to repeat this process, but invoke the inner structs' destructors explicitly.

If you have trouble, search for "placement new" in Kokkos' issues and wiki.

**Comment by crtrott** [comment] 2018-07-05 18:09
Mark described what you probably need to do. Note that your crash is most likely because of his point 4. Note that you must allocate the nested array with device visible memory. Either make that a View itself, or use something like `Kokkos::kokkos_malloc<CudaSpace>(num_bytes)`

**Comment by ArVictor** [comment] 2018-07-05 18:11
Thank you, I will look into it. But what surprised me is that it works on a different GPU.

**Comment by crtrott** [comment] 2018-07-05 20:59
Did it truly work or did just not crash? Pascal is somewhat better in tracking and reporting illegal memory accesses.

**Comment by ArVictor** [comment] 2018-07-06 13:37
@mhoemmen 's instructions worked, thank you !
Before
```c++
this->view_group = Kokkos::View<particle_group_base*>("view_group", 1);
```
After
```c++
this->view_group = Kokkos::View<particle_group_base*, Kokkos::CudaUVMSpace>(Kokkos::ViewAllocateWithoutInitializing ("view_group"), 1);
Kokkos::fence();
new(&this->view_group(0)) particle_group_base(folder_name, frame, is_using_views);
Kokkos::fence();
```

@crtrott , I used this code for over 2 months on a K40m without any issue regarding this View.

**Comment by mhoemmen** [comment] 2018-07-06 17:43
@ArVictor It's incorrect code that just happened to work.

**Comment by crtrott** [comment] 2018-07-08 17:05
Sounds like the issue is resolved. Closing this now.

**Closed by crtrott** 2018-07-08 17:05 UTC
