### ISSUE TITLE
How to use parallel_* with TeamThreadRange and functor?

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1706] opened 2018-07-23 21:47 UTC
For example, I'm trying to do
```
Kokkos::parallel_scan(Kokkos::TeamThreadRange(team,N),Functor{});
```
with 
```
struct Functor {
  KOKKOS_INLINE_FUNCTION Functor() {};
  KOKKOS_INLINE_FUNCTION void operator()(const int& i, int& update, const bool& bFinal) const { ... }

}
```
which compiles and run fines on CPU but gives compilation error with Cuda:
```
In file included from /home/aznb/mycodes/scbmc/tests/testSCBMC.cpp:19:
/home/aznb/mycodes/scbmc/scbmc.hpp:248:7: error: no matching function for call to 'parallel_scan'
      Kokkos::parallel_scan(Kokkos::TeamThreadRange(team,nCells()),
      ^~~~~~~~~~~~~~~~~~~~~
/home/aznb/mycodes/scbmc/tests/testSCBMC.cpp:120:11: note: in instantiation of function template specialization 'SCBMC<VirtualInherit<SCBMCData<Particles<double, 3, 1000, 2, Kokkos::Cuda, OrthorhombicPBC>, Harmonic<double, 3, Kokkos::Cuda, 1>, HarmonicBond<double, 3, Kokkos::Cuda, 1>, HarmonicCosAngle<double, 3, Kokkos::Cuda, 1>, 4, 4> >, LinearEndMove<Particles<double, 3, 1000, 2, Kokkos::Cuda, OrthorhombicPBC>, Harmonic<double, 3, Kokkos::Cuda, 1>, HarmonicBond<double, 3, Kokkos::Cuda, 1>, HarmonicCosAngle<double, 3, Kokkos::Cuda, 1>, 4, 4> >::move<Kokkos::Cuda>' requested here
  moveSet.move<ExecutionSpace>();
          ^
/home/aznb/mycodes/kokkos/core/src/Kokkos_Parallel.hpp:447:6: note: candidate function not viable: no known conversion from 'Impl::TeamThreadRangeBoundariesStruct<int, Impl::CudaTeamMember>' to 'const size_t' (aka 'const unsigned long') for 1st argument
void parallel_scan( const size_t        work_count
     ^
/home/aznb/mycodes/kokkos/core/src/Kokkos_Parallel.hpp:417:6: note: candidate template ignored: substitution failure [with ExecutionPolicy = Kokkos::Impl::TeamThreadRangeBoundariesStruct<int, Kokkos::Impl::CudaTeamMember>, FunctorType = SCBMC<VirtualInherit<SCBMCData<Particles<double, 3, 1000, 2, Kokkos::Cuda, OrthorhombicPBC>, Harmonic<double, 3, Kokkos::Cuda, 1>, HarmonicBond<double, 3, Kokkos::Cuda, 1>, HarmonicCosAngle<double, 3, Kokkos::Cuda, 1>, 4, 4> >, LinearEndMove<Particles<double, 3, 1000, 2, Kokkos::Cuda, OrthorhombicPBC>, Harmonic<double, 3, Kokkos::Cuda, 1>, HarmonicBond<double, 3, Kokkos::Cuda, 1>, HarmonicCosAngle<double, 3, Kokkos::Cuda, 1>, 4, 4> >::ScanDomainParticles<Kokkos::Cuda>]: implicit instantiation of undefined template 'Kokkos::Impl::enable_if<false, void>'
void parallel_scan( const ExecutionPolicy & policy
     ^
/home/aznb/mycodes/kokkos/core/src/impl/Kokkos_HostThreadTeam.hpp:1001:6: note: candidate template ignored: could not match 'HostThreadTeamMember<type-parameter-0-1>' against 'Kokkos::Impl::CudaTeamMember'
void parallel_scan
     ^
/home/aznb/mycodes/kokkos/core/src/impl/Kokkos_HostThreadTeam.hpp:1036:6: note: candidate template ignored: could not match 'ThreadVectorRangeBoundariesStruct' against 'TeamThreadRangeBoundariesStruct'
void parallel_scan
     ^
/home/aznb/mycodes/kokkos/core/src/Cuda/Kokkos_Cuda_Team.hpp:892:6: note: candidate template ignored: could not match 'ThreadVectorRangeBoundariesStruct' against 'TeamThreadRangeBoundariesStruct'
void parallel_scan
     ^
/home/aznb/mycodes/kokkos/core/src/Kokkos_Parallel.hpp:481:6: note: candidate function template not viable: requires 3 arguments, but 2 were provided
void parallel_scan( const std::string& str
     ^
/home/aznb/mycodes/kokkos/core/src/Kokkos_Parallel.hpp:502:6: note: candidate function template not viable: requires at least 3 arguments, but 2 were provided
void parallel_scan( const ExecutionPolicy & policy
     ^
/home/aznb/mycodes/kokkos/core/src/Kokkos_Parallel.hpp:533:6: note: candidate function template not viable: requires at least 3 arguments, but 2 were provided
void parallel_scan( const size_t        work_count
     ^
/home/aznb/mycodes/kokkos/core/src/Kokkos_Parallel.hpp:568:6: note: candidate function template not viable: requires 4 arguments, but 2 were provided
void parallel_scan( const std::string& str
     ^
1 error generated when compiling for sm_61.
make[2]: *** [tests/CMakeFiles/testSCBMC.dir/build.make:63: tests/CMakeFiles/testSCBMC.dir/testSCBMC.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1443: tests/CMakeFiles/testSCBMC.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by Char-Aznable** [comment] 2018-07-23 22:07
May be related to https://github.com/kokkos/kokkos/issues/433 and https://github.com/kokkos/kokkos/issues/45

**Comment by ibaned** [comment] 2018-07-26 15:50
Yea, I think unfortunately this is still an open issue #45, and this issue is just a duplicate of that one.

**Comment by ibaned** [comment] 2018-08-01 18:56
I'll close this as a duplicate of #45 , please comment if that isn't appropriate

**Closed by ibaned** 2018-08-01 18:56 UTC
