### ISSUE TITLE
kokkosresize.host_space_access test failing with ibm/xl/16.1.0 compiler on White (Power8 system)

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2763] opened 2020-02-14 20:48 UTC
The `KokkosCore_UnitTest_Default` test is failing on the White testbed (Power8 system) with the xl/16.1.0 compiler.

Reproducer instructions:

**Modules**
`module load cmake/3.12.3 ibm/xl/16.1.0 gcc/7.2.0`

**generate_makefile.bash**:
`<KOKKOS_PATH>/generate_makefile.bash --with-devices=OpenMP --arch=Power8,Kepler37 --compiler=/home/projects/ppc64le/ibm/xlC/16.1.0/bin/xlC --cxxflags="-O3 -Wall -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="11" --ldflags="" --kokkos-path=<KOKKOS_PATH> --no-examples --with-options=enable_large_mem_tests`

**Resultant CMake line**:
`cmake -DCMAKE_CXX_COMPILER=/home/projects/ppc64le/ibm/xlC/16.1.0/bin/xlC -DCMAKE_CXX_FLAGS=-O3 -Wall -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized  -DCMAKE_EXE_LINKER_FLAGS= -DCMAKE_INSTALL_PREFIX= -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_POWER8=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DKokkos_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=RELEASE <KOKKOS_PATH>`

Test failure output:
`ctest -R KokkosCore_UnitTest_Default -V`

```bash
3: [----------] 1 test from kokkosresize
3: [ RUN      ] kokkosresize.host_space_access
3: /ascldap/users/ndellin/kokkos/core/unit_test/TestResize.hpp:193: Failure
3: Value of: test == true
3:   Actual: false
3: Expected: true
3: /ascldap/users/ndellin/kokkos/core/unit_test/TestResize.hpp:218: Failure
3: Value of: test == true
3:   Actual: false
3: Expected: true
3: /ascldap/users/ndellin/kokkos/core/unit_test/TestResize.hpp:245: Failure
3: Value of: test == true
3:   Actual: false
3: Expected: true
3: /ascldap/users/ndellin/kokkos/core/unit_test/TestResize.hpp:311: Failure
3: Value of: test == true
3:   Actual: false
3: Expected: true
3: /ascldap/users/ndellin/kokkos/core/unit_test/TestResize.hpp:347: Failure
3: Value of: test == true
3:   Actual: false
3: Expected: true
3: /ascldap/users/ndellin/kokkos/core/unit_test/TestResize.hpp:385: Failure
3: Value of: test == true
3:   Actual: false
3: Expected: true
3: /ascldap/users/ndellin/kokkos/core/unit_test/TestResize.hpp:193: Failure
3: Value of: test == true
3:   Actual: false
3: Expected: true
3: /ascldap/users/ndellin/kokkos/core/unit_test/TestResize.hpp:245: Failure
3: Value of: test == true
3:   Actual: false
3: Expected: true
3: /ascldap/users/ndellin/kokkos/core/unit_test/TestResize.hpp:385: Failure
3: Value of: test == true
3:   Actual: false
3: Expected: true
3: [  FAILED  ] kokkosresize.host_space_access (23 ms)
3: [----------] 1 test from kokkosresize (23 ms total)
```

**Comment by crtrott** [comment] 2020-03-12 22:06
I can't reproduce it this with 16.1.1 on Power9.

**Comment by ndellingwood** [comment] 2020-03-12 22:11
Must be specific to Power8 then? I'm going to update the compiler version in the title, had a typo (should be xl/16.1.0). White is a mess, are you able to test Ride?

**Comment by crtrott** [comment] 2020-03-12 23:01
But it might also be fixed by the 64bit fix we recently did ...

**Comment by crtrott** [comment] 2020-03-12 23:54
reproduced the issue on ride. Trying 16.1.1 now. Also I was using xlc++ before have to check that too.

**Comment by crtrott** [comment] 2020-03-13 00:19
works with 16.1.1 we may just call this a compiler bug and go to 16.1.1 as the minimum ...

**Comment by ndellingwood** [comment] 2020-03-13 00:26
> works with 16.1.1

yeah, we haven't had nightly fails with 16.1.1, only 16.1.0

**Comment by ndellingwood** [comment] 2020-04-09 16:25
Dropped 16.1.0 testing, relabeled as Compiler Issue.

**Closed** 2020-08-19 21:03 UTC
Labels: Compiler Issue, wontfix
