### ISSUE TITLE
Flag to force separate address space in dual view, even on CPU?

### ISSUE THREAD

**Issue by tcfisher** [kokkos/kokkos#933] opened 2017-07-06 21:31 UTC
I am wondering if there is a build flag available in Kokkos to force a host and dual view to have separate address spaces on architectures that don't have separate host and device memories? If not, will you please consider this a feature request?

This would be useful for debugging synchronization of views for the gpu without having to actually use the gpu architecture.

**Comment by ibaned** [comment] 2017-07-06 21:48
There isn't right now, but you're not the first one to ask.

This request is basically the same as #783 originally proposed by @stanmoore1.

We now have at least two users asking for this, so it will likely be implemented soon.

**Comment by ibaned** [comment] 2017-09-13 20:22
See discussion in #783, I think we'll need to introduce new execution and / or memory spaces to really get this to work...

**Comment by ibaned** [comment] 2018-03-14 19:16
This is really a duplicate of #783, which based on attempts still seems pretty hard. I'll close this one and efforts can continue in #783.

**Closed by ibaned** 2018-03-14 19:16 UTC
Labels: Feature Request
